/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as activeWorkerJobs from "../activeWorkerJobs.js";
import type * as adjustNotificationUnreadSummary from "../adjustNotificationUnreadSummary.js";
import type * as aggregateBackfills from "../aggregateBackfills.js";
import type * as aggregateCounts from "../aggregateCounts.js";
import type * as assertProductBelongsToOwner from "../assertProductBelongsToOwner.js";
import type * as assignLegacyRecordsToProduct from "../assignLegacyRecordsToProduct.js";
import type * as auth_assertAutomationWorkerSecret from "../auth/assertAutomationWorkerSecret.js";
import type * as auth_assertMediaWorkerSecret from "../auth/assertMediaWorkerSecret.js";
import type * as auth_assertProviderWorkerSecret from "../auth/assertProviderWorkerSecret.js";
import type * as auth_assertRateLimitApiSecret from "../auth/assertRateLimitApiSecret.js";
import type * as auth_getAuthenticatedOwnerId from "../auth/getAuthenticatedOwnerId.js";
import type * as automationAvatarPhoto from "../automationAvatarPhoto.js";
import type * as automationBudget from "../automationBudget.js";
import type * as automationClipr from "../automationClipr.js";
import type * as automationCreateRun from "../automationCreateRun.js";
import type * as automationCreateTask from "../automationCreateTask.js";
import type * as automationGlobalWindow from "../automationGlobalWindow.js";
import type * as automationLimits from "../automationLimits.js";
import type * as automationMarkRunSkipped from "../automationMarkRunSkipped.js";
import type * as automationPlannerCandidates from "../automationPlannerCandidates.js";
import type * as automationPreferences from "../automationPreferences.js";
import type * as automationRuns from "../automationRuns.js";
import type * as automationScheduler from "../automationScheduler.js";
import type * as automationStitchr from "../automationStitchr.js";
import type * as automationStitchrPairScoring from "../automationStitchrPairScoring.js";
import type * as automationSwapr from "../automationSwapr.js";
import type * as automationSwipr from "../automationSwipr.js";
import type * as automationTasks from "../automationTasks.js";
import type * as avatarPreferences from "../avatarPreferences.js";
import type * as avatars from "../avatars.js";
import type * as blogPostCards_estimateBlogPostReadingTimeMinutes from "../blogPostCards/estimateBlogPostReadingTimeMinutes.js";
import type * as blogPostCards_getBlogPostCardFields from "../blogPostCards/getBlogPostCardFields.js";
import type * as blogPostCards_upsertBlogPostCardBySlug from "../blogPostCards/upsertBlogPostCardBySlug.js";
import type * as blogPosts from "../blogPosts.js";
import type * as clearPostBridgeSocialAccountIdsForOwner from "../clearPostBridgeSocialAccountIdsForOwner.js";
import type * as cliAuth_approveDeviceAuthorization from "../cliAuth/approveDeviceAuthorization.js";
import type * as cliAuth_createDeviceAuthorization from "../cliAuth/createDeviceAuthorization.js";
import type * as cliAuth_exchangeDeviceAuthorization from "../cliAuth/exchangeDeviceAuthorization.js";
import type * as cliAuth_getActiveSessionByTokenHash from "../cliAuth/getActiveSessionByTokenHash.js";
import type * as cliAuth_revokeSessionByTokenHash from "../cliAuth/revokeSessionByTokenHash.js";
import type * as cliLibrary_addCliStitchPostBridgePost from "../cliLibrary/addCliStitchPostBridgePost.js";
import type * as cliLibrary_addCliSwipePostBridgePost from "../cliLibrary/addCliSwipePostBridgePost.js";
import type * as cliLibrary_cliLibraryListLimit from "../cliLibrary/cliLibraryListLimit.js";
import type * as cliLibrary_getCliStitch from "../cliLibrary/getCliStitch.js";
import type * as cliLibrary_getCliSwipe from "../cliLibrary/getCliSwipe.js";
import type * as cliLibrary_listCliClips from "../cliLibrary/listCliClips.js";
import type * as cliLibrary_listCliStitches from "../cliLibrary/listCliStitches.js";
import type * as cliLibrary_listCliSwipes from "../cliLibrary/listCliSwipes.js";
import type * as cliPostBridge_getCliPostBridgeSecret from "../cliPostBridge/getCliPostBridgeSecret.js";
import type * as cliProducts_createCliProduct from "../cliProducts/createCliProduct.js";
import type * as cliProducts_getCliProduct from "../cliProducts/getCliProduct.js";
import type * as cliProducts_getCliProductDocument from "../cliProducts/getCliProductDocument.js";
import type * as cliProducts_listCliProducts from "../cliProducts/listCliProducts.js";
import type * as cliQueue_listCliQueueSourceSummaries from "../cliQueue/listCliQueueSourceSummaries.js";
import type * as cliRateLimits_consumeCliPostBridgeMediaUpload from "../cliRateLimits/consumeCliPostBridgeMediaUpload.js";
import type * as cliRateLimits_consumeCliPostBridgeRead from "../cliRateLimits/consumeCliPostBridgeRead.js";
import type * as cliRateLimits_consumeCliPostBridgeSchedule from "../cliRateLimits/consumeCliPostBridgeSchedule.js";
import type * as cliSwipr_getIsCliSwiprBatchRunId from "../cliSwipr/getIsCliSwiprBatchRunId.js";
import type * as cliSwipr_planCliSwiprBatch from "../cliSwipr/planCliSwiprBatch.js";
import type * as cliUploads_getCliUploadStatus from "../cliUploads/getCliUploadStatus.js";
import type * as cliprJobs from "../cliprJobs.js";
import type * as cliprPreferences from "../cliprPreferences.js";
import type * as createActiveAutomationBatchJobSummary from "../createActiveAutomationBatchJobSummary.js";
import type * as createAutomationRunSummaryFields from "../createAutomationRunSummaryFields.js";
import type * as createAutomationTaskSummaryFields from "../createAutomationTaskSummaryFields.js";
import type * as createCliprJobSummaryFields from "../createCliprJobSummaryFields.js";
import type * as createCompletedRunNotification from "../createCompletedRunNotification.js";
import type * as createNotification from "../createNotification.js";
import type * as createProductCardFields from "../createProductCardFields.js";
import type * as createQuickEditSuggestionsFromMetadata from "../createQuickEditSuggestionsFromMetadata.js";
import type * as createSoundTrackSnapshot from "../createSoundTrackSnapshot.js";
import type * as createStitchCardFields from "../createStitchCardFields.js";
import type * as createSwipeCardFields from "../createSwipeCardFields.js";
import type * as createSwiprBackgroundCardFields from "../createSwiprBackgroundCardFields.js";
import type * as createVideoClipCardFields from "../createVideoClipCardFields.js";
import type * as createWorkerJobSummaryFields from "../createWorkerJobSummaryFields.js";
import type * as crons from "../crons.js";
import type * as dashboardSummary from "../dashboardSummary.js";
import type * as defaultAutomationCliprVoiceId from "../defaultAutomationCliprVoiceId.js";
import type * as deleteAutomationRunSummary from "../deleteAutomationRunSummary.js";
import type * as deleteAutomationTaskSummary from "../deleteAutomationTaskSummary.js";
import type * as deleteCliprJobSummary from "../deleteCliprJobSummary.js";
import type * as deleteProductCard from "../deleteProductCard.js";
import type * as deleteStitchCard from "../deleteStitchCard.js";
import type * as deleteSwipeCard from "../deleteSwipeCard.js";
import type * as deleteSwiprBackgroundCard from "../deleteSwiprBackgroundCard.js";
import type * as deleteVideoClipCard from "../deleteVideoClipCard.js";
import type * as deleteWorkerJobSummary from "../deleteWorkerJobSummary.js";
import type * as getActiveWorkerJobSummary from "../getActiveWorkerJobSummary.js";
import type * as getAutomationBatchJobProgress from "../getAutomationBatchJobProgress.js";
import type * as getAutomationBatchJobStage from "../getAutomationBatchJobStage.js";
import type * as getAutomationBatchJobStatus from "../getAutomationBatchJobStatus.js";
import type * as getAutomationBatchJobType from "../getAutomationBatchJobType.js";
import type * as getAutomationPreferenceForProduct from "../getAutomationPreferenceForProduct.js";
import type * as getAutomationProductScopeKey from "../getAutomationProductScopeKey.js";
import type * as getAutomationRunHasIncompleteTasks from "../getAutomationRunHasIncompleteTasks.js";
import type * as getAutomationRunHasTasks from "../getAutomationRunHasTasks.js";
import type * as getAutomationTaskProductId from "../getAutomationTaskProductId.js";
import type * as getAutomationToolDisabledReason from "../getAutomationToolDisabledReason.js";
import type * as getAvatarNotificationCopy from "../getAvatarNotificationCopy.js";
import type * as getCliprGeneratedClipStorageFields from "../getCliprGeneratedClipStorageFields.js";
import type * as getCompletedRunAssetLabel from "../getCompletedRunAssetLabel.js";
import type * as getCompletedRunToolLabel from "../getCompletedRunToolLabel.js";
import type * as getDefaultAvatarForOwner from "../getDefaultAvatarForOwner.js";
import type * as getDefaultProductForOwner from "../getDefaultProductForOwner.js";
import type * as getEnabledAutomationToolsForPreference from "../getEnabledAutomationToolsForPreference.js";
import type * as getFirstStitchScoreUpdate from "../getFirstStitchScoreUpdate.js";
import type * as getOwnerHasContent from "../getOwnerHasContent.js";
import type * as getOwnerHasLegacyProductRecords from "../getOwnerHasLegacyProductRecords.js";
import type * as getOwnerHasStitches from "../getOwnerHasStitches.js";
import type * as getPhotoNotificationCopy from "../getPhotoNotificationCopy.js";
import type * as getPrimaryProductForOwner from "../getPrimaryProductForOwner.js";
import type * as getProductForOwner from "../getProductForOwner.js";
import type * as getProductNameFromAutomationTasks from "../getProductNameFromAutomationTasks.js";
import type * as getQuickEditOverlayText from "../getQuickEditOverlayText.js";
import type * as getQuickEditWithRemoveRanges from "../getQuickEditWithRemoveRanges.js";
import type * as getReadLimitedPaginationOpts from "../getReadLimitedPaginationOpts.js";
import type * as getRequiredVideoClipProductId from "../getRequiredVideoClipProductId.js";
import type * as getStitchNotificationCopy from "../getStitchNotificationCopy.js";
import type * as getStitchProductId from "../getStitchProductId.js";
import type * as getStitchRecipeByIdeaOrTemplate from "../getStitchRecipeByIdeaOrTemplate.js";
import type * as getSwipeCardSearchText from "../getSwipeCardSearchText.js";
import type * as getSwipeNotificationCopy from "../getSwipeNotificationCopy.js";
import type * as getSwiprBackgroundCardSearchText from "../getSwiprBackgroundCardSearchText.js";
import type * as getSwiprSwipeReferencedBackgroundIds from "../getSwiprSwipeReferencedBackgroundIds.js";
import type * as getVideoClipCanBePosted from "../getVideoClipCanBePosted.js";
import type * as getVideoClipCardSearchText from "../getVideoClipCardSearchText.js";
import type * as getVideoClipLibraryKind from "../getVideoClipLibraryKind.js";
import type * as getVideoClipNotificationCopy from "../getVideoClipNotificationCopy.js";
import type * as hookLabDefaults_get from "../hookLabDefaults/get.js";
import type * as hookLabDefaults_set from "../hookLabDefaults/set.js";
import type * as hookLabIdeaUses_create from "../hookLabIdeaUses/create.js";
import type * as hookLabIdeaUses_get from "../hookLabIdeaUses/get.js";
import type * as hookLabIdeaUses_getHookLabVariationCount from "../hookLabIdeaUses/getHookLabVariationCount.js";
import type * as hookLabIdeaVariants_attachProviderJob from "../hookLabIdeaVariants/attachProviderJob.js";
import type * as hookLabIdeaVariants_completeFromMediaWorker from "../hookLabIdeaVariants/completeFromMediaWorker.js";
import type * as hookLabIdeaVariants_dispatchProviderJob from "../hookLabIdeaVariants/dispatchProviderJob.js";
import type * as hookLabIdeaVariants_failDispatch from "../hookLabIdeaVariants/failDispatch.js";
import type * as hookLabIdeaVariants_failFinalizationJobFromMediaWorker from "../hookLabIdeaVariants/failFinalizationJobFromMediaWorker.js";
import type * as hookLabIdeaVariants_failFromMediaWorker from "../hookLabIdeaVariants/failFromMediaWorker.js";
import type * as hookLabIdeaVariants_failFromProvider from "../hookLabIdeaVariants/failFromProvider.js";
import type * as hookLabIdeaVariants_failGenerationJobFromProvider from "../hookLabIdeaVariants/failGenerationJobFromProvider.js";
import type * as hookLabIdeaVariants_getInputForProvider from "../hookLabIdeaVariants/getInputForProvider.js";
import type * as hookLabIdeaVariants_markFinalizingFromProvider from "../hookLabIdeaVariants/markFinalizingFromProvider.js";
import type * as hookLabIdeaVariants_markGeneratingFromProvider from "../hookLabIdeaVariants/markGeneratingFromProvider.js";
import type * as hookLabIdeaVariants_recalculateHookLabIdeaUse from "../hookLabIdeaVariants/recalculateHookLabIdeaUse.js";
import type * as hookLabIdeaVariants_recordGeneratedImageFromProvider from "../hookLabIdeaVariants/recordGeneratedImageFromProvider.js";
import type * as hookLabIdeaVariants_recordGeneratedVideoFromProvider from "../hookLabIdeaVariants/recordGeneratedVideoFromProvider.js";
import type * as hookLabIdeas_archive from "../hookLabIdeas/archive.js";
import type * as hookLabIdeas_completeAnalysisFromProvider from "../hookLabIdeas/completeAnalysisFromProvider.js";
import type * as hookLabIdeas_create from "../hookLabIdeas/create.js";
import type * as hookLabIdeas_createHookLabIdeaSearchText from "../hookLabIdeas/createHookLabIdeaSearchText.js";
import type * as hookLabIdeas_createHookLabStitchRecipeFromStitch from "../hookLabIdeas/createHookLabStitchRecipeFromStitch.js";
import type * as hookLabIdeas_failAnalysisFromProvider from "../hookLabIdeas/failAnalysisFromProvider.js";
import type * as hookLabIdeas_failAnalysisJobFromProvider from "../hookLabIdeas/failAnalysisJobFromProvider.js";
import type * as hookLabIdeas_getForProvider from "../hookLabIdeas/getForProvider.js";
import type * as hookLabIdeas_getHookLabIdeaDefaultName from "../hookLabIdeas/getHookLabIdeaDefaultName.js";
import type * as hookLabIdeas_getHookLabIdeaMatchesListFilters from "../hookLabIdeas/getHookLabIdeaMatchesListFilters.js";
import type * as hookLabIdeas_getHookLabOriginalTextFromStitch from "../hookLabIdeas/getHookLabOriginalTextFromStitch.js";
import type * as hookLabIdeas_getHookLabPromptBlueprints from "../hookLabIdeas/getHookLabPromptBlueprints.js";
import type * as hookLabIdeas_linkHookOptionToIdea from "../hookLabIdeas/linkHookOptionToIdea.js";
import type * as hookLabIdeas_list from "../hookLabIdeas/list.js";
import type * as hookLabIdeas_listPromptMemory from "../hookLabIdeas/listPromptMemory.js";
import type * as hookLabIdeas_listStitchSources from "../hookLabIdeas/listStitchSources.js";
import type * as hookLabIdeas_markAnalysisDispatchFailed from "../hookLabIdeas/markAnalysisDispatchFailed.js";
import type * as hookLabIdeas_prepareProviderRun from "../hookLabIdeas/prepareProviderRun.js";
import type * as hookLabIdeas_recordProviderRun from "../hookLabIdeas/recordProviderRun.js";
import type * as hookLabIdeas_remove from "../hookLabIdeas/remove.js";
import type * as hookLabIdeas_retry from "../hookLabIdeas/retry.js";
import type * as hookLabIdeas_update from "../hookLabIdeas/update.js";
import type * as isWithinAutomationGlobalWindow from "../isWithinAutomationGlobalWindow.js";
import type * as libraryCounts from "../libraryCounts.js";
import type * as listActiveAutomationBatchJobSummaries from "../listActiveAutomationBatchJobSummaries.js";
import type * as listActiveWorkerJobSummaries from "../listActiveWorkerJobSummaries.js";
import type * as listProductsForOwnerByIds from "../listProductsForOwnerByIds.js";
import type * as listRecentAvatarPhotoAssets from "../listRecentAvatarPhotoAssets.js";
import type * as listRecentProductsForOwner from "../listRecentProductsForOwner.js";
import type * as listRecentVideoClipCardsByLibraryKind from "../listRecentVideoClipCardsByLibraryKind.js";
import type * as listRecentVideoClipsByLibraryKind from "../listRecentVideoClipsByLibraryKind.js";
import type * as logConvexTransactionMetrics from "../logConvexTransactionMetrics.js";
import type * as markAutomationRunCompletedIfAllTasksDone from "../markAutomationRunCompletedIfAllTasksDone.js";
import type * as markAutomationRunCompletedWhenTasksDone from "../markAutomationRunCompletedWhenTasksDone.js";
import type * as markAutomationRunStatus from "../markAutomationRunStatus.js";
import type * as mediaJobs from "../mediaJobs.js";
import type * as mediaWorkerLaunch from "../mediaWorkerLaunch.js";
import type * as migrations_createHookLabStitchRecipeFromTemplate from "../migrations/createHookLabStitchRecipeFromTemplate.js";
import type * as migrations_createMigratedHookLabCreativeBeat from "../migrations/createMigratedHookLabCreativeBeat.js";
import type * as migrations_createMigratedHookLabTextBlueprint from "../migrations/createMigratedHookLabTextBlueprint.js";
import type * as migrations_getHookLabMigrationStatus from "../migrations/getHookLabMigrationStatus.js";
import type * as migrations_getHookLabTemplateOriginalText from "../migrations/getHookLabTemplateOriginalText.js";
import type * as migrations_migrateStitchTemplatesToHookLabIdeas from "../migrations/migrateStitchTemplatesToHookLabIdeas.js";
import type * as migrations_migrateStitchrHookOptions from "../migrations/migrateStitchrHookOptions.js";
import type * as migrations_migrateWinningHooksToHookLabIdeas from "../migrations/migrateWinningHooksToHookLabIdeas.js";
import type * as normalizeQuickEditRemoveRanges from "../normalizeQuickEditRemoveRanges.js";
import type * as notifications from "../notifications.js";
import type * as photoAssets from "../photoAssets.js";
import type * as postBridgePostProductMappings from "../postBridgePostProductMappings.js";
import type * as postBridgeSettings from "../postBridgeSettings.js";
import type * as productPreferences from "../productPreferences.js";
import type * as products from "../products.js";
import type * as providerJobAttempts_retryAfterFailure from "../providerJobAttempts/retryAfterFailure.js";
import type * as providerJobs from "../providerJobs.js";
import type * as providerWorkerLaunch from "../providerWorkerLaunch.js";
import type * as rateLimiter from "../rateLimiter.js";
import type * as rateLimits from "../rateLimits.js";
import type * as readModelBackfills from "../readModelBackfills.js";
import type * as recordStitchrBatchPairHistory from "../recordStitchrBatchPairHistory.js";
import type * as replicateJobs from "../replicateJobs.js";
import type * as sharedMusicTracks from "../sharedMusicTracks.js";
import type * as soundPreferences from "../soundPreferences.js";
import type * as stitchTemplates_createAutomaticStitchTemplateFromAcceptedHookPlan from "../stitchTemplates/createAutomaticStitchTemplateFromAcceptedHookPlan.js";
import type * as stitchTemplates_createAutomaticStitchTemplateFromAcceptedHookStitch from "../stitchTemplates/createAutomaticStitchTemplateFromAcceptedHookStitch.js";
import type * as stitchTemplates_createFromStitch from "../stitchTemplates/createFromStitch.js";
import type * as stitchTemplates_createStitchTemplateDocumentFromStitch from "../stitchTemplates/createStitchTemplateDocumentFromStitch.js";
import type * as stitchTemplates_get from "../stitchTemplates/get.js";
import type * as stitchTemplates_getAcceptedHookTemplateId from "../stitchTemplates/getAcceptedHookTemplateId.js";
import type * as stitchTemplates_getAcceptedHookTemplateName from "../stitchTemplates/getAcceptedHookTemplateName.js";
import type * as stitchTemplates_getAcceptedHookTextFromPlan from "../stitchTemplates/getAcceptedHookTextFromPlan.js";
import type * as stitchTemplates_getStitchTemplateBatchTextOverlay from "../stitchTemplates/getStitchTemplateBatchTextOverlay.js";
import type * as stitchTemplates_getStitchTemplateTextOverlaysForAcceptedHook from "../stitchTemplates/getStitchTemplateTextOverlaysForAcceptedHook.js";
import type * as stitchTemplates_list from "../stitchTemplates/list.js";
import type * as stitchTemplates_remove from "../stitchTemplates/remove.js";
import type * as stitchTemplates_updateName from "../stitchTemplates/updateName.js";
import type * as stitches from "../stitches.js";
import type * as stitches_saveHookLabVariantFromMediaWorker from "../stitches/saveHookLabVariantFromMediaWorker.js";
import type * as stitchrBatch from "../stitchrBatch.js";
import type * as stitchrBatchRunId from "../stitchrBatchRunId.js";
import type * as stitchrHookOptions_listReview from "../stitchrHookOptions/listReview.js";
import type * as stitchrHookOptions_markNotForMe from "../stitchrHookOptions/markNotForMe.js";
import type * as stitchrHookOptions_select from "../stitchrHookOptions/select.js";
import type * as stitchrHookOptions_syncStitchrHookOptionsFromPlan from "../stitchrHookOptions/syncStitchrHookOptionsFromPlan.js";
import type * as stitchrHookOptions_undoFeedback from "../stitchrHookOptions/undoFeedback.js";
import type * as stitchrHookPlans from "../stitchrHookPlans.js";
import type * as swipes from "../swipes.js";
import type * as swiprBackgrounds from "../swiprBackgrounds.js";
import type * as upsertAutomationRunSummary from "../upsertAutomationRunSummary.js";
import type * as upsertAutomationTaskSummary from "../upsertAutomationTaskSummary.js";
import type * as upsertCliprJobSummary from "../upsertCliprJobSummary.js";
import type * as upsertProductCard from "../upsertProductCard.js";
import type * as upsertStitchCard from "../upsertStitchCard.js";
import type * as upsertSwipeCard from "../upsertSwipeCard.js";
import type * as upsertSwiprBackgroundCard from "../upsertSwiprBackgroundCard.js";
import type * as upsertVideoClipCard from "../upsertVideoClipCard.js";
import type * as upsertWorkerJobSummary from "../upsertWorkerJobSummary.js";
import type * as validators_assetTags from "../validators/assetTags.js";
import type * as validators_automationCliprGenerationMode from "../validators/automationCliprGenerationMode.js";
import type * as validators_automationGenerationCount from "../validators/automationGenerationCount.js";
import type * as validators_automationProvenance from "../validators/automationProvenance.js";
import type * as validators_automationRunStatus from "../validators/automationRunStatus.js";
import type * as validators_automationSelectionMode from "../validators/automationSelectionMode.js";
import type * as validators_automationStitchrTemplateAllocation from "../validators/automationStitchrTemplateAllocation.js";
import type * as validators_automationStitchrTextStyleChoice from "../validators/automationStitchrTextStyleChoice.js";
import type * as validators_automationTaskStatus from "../validators/automationTaskStatus.js";
import type * as validators_automationTaskType from "../validators/automationTaskType.js";
import type * as validators_automationTool from "../validators/automationTool.js";
import type * as validators_avatarWardrobeStyle from "../validators/avatarWardrobeStyle.js";
import type * as validators_blogPostContentFormat from "../validators/blogPostContentFormat.js";
import type * as validators_cliDeviceAuthorizationStatus from "../validators/cliDeviceAuthorizationStatus.js";
import type * as validators_clipPerformanceScore from "../validators/clipPerformanceScore.js";
import type * as validators_clipType from "../validators/clipType.js";
import type * as validators_cliprDurationSeconds from "../validators/cliprDurationSeconds.js";
import type * as validators_cliprGenerationMode from "../validators/cliprGenerationMode.js";
import type * as validators_cliprJobStage from "../validators/cliprJobStage.js";
import type * as validators_cliprJobStatus from "../validators/cliprJobStatus.js";
import type * as validators_cliprMetadata from "../validators/cliprMetadata.js";
import type * as validators_cliprMusicMetadata from "../validators/cliprMusicMetadata.js";
import type * as validators_cliprResolvedGenerationMode from "../validators/cliprResolvedGenerationMode.js";
import type * as validators_cliprScenePlan from "../validators/cliprScenePlan.js";
import type * as validators_cliprVideoModelId from "../validators/cliprVideoModelId.js";
import type * as validators_hookLabCreativeBeat from "../validators/hookLabCreativeBeat.js";
import type * as validators_hookLabIdeaScope from "../validators/hookLabIdeaScope.js";
import type * as validators_hookLabIdeaScopeFilter from "../validators/hookLabIdeaScopeFilter.js";
import type * as validators_hookLabIdeaSourceType from "../validators/hookLabIdeaSourceType.js";
import type * as validators_hookLabIdeaStatus from "../validators/hookLabIdeaStatus.js";
import type * as validators_hookLabIdeaStatusFilter from "../validators/hookLabIdeaStatusFilter.js";
import type * as validators_hookLabIdeaUseStatus from "../validators/hookLabIdeaUseStatus.js";
import type * as validators_hookLabIdeaVariantStatus from "../validators/hookLabIdeaVariantStatus.js";
import type * as validators_hookLabReviewState from "../validators/hookLabReviewState.js";
import type * as validators_hookLabStitchRecipe from "../validators/hookLabStitchRecipe.js";
import type * as validators_hookLabTextBlueprint from "../validators/hookLabTextBlueprint.js";
import type * as validators_hookLabTextDecision from "../validators/hookLabTextDecision.js";
import type * as validators_librarySortOrder from "../validators/librarySortOrder.js";
import type * as validators_mediaJobStatus from "../validators/mediaJobStatus.js";
import type * as validators_mediaJobType from "../validators/mediaJobType.js";
import type * as validators_musicTrackSource from "../validators/musicTrackSource.js";
import type * as validators_notificationSourceType from "../validators/notificationSourceType.js";
import type * as validators_postBridgeMediaKind from "../validators/postBridgeMediaKind.js";
import type * as validators_postBridgePlatform from "../validators/postBridgePlatform.js";
import type * as validators_postBridgePostReference from "../validators/postBridgePostReference.js";
import type * as validators_postBridgePostStatus from "../validators/postBridgePostStatus.js";
import type * as validators_postBridgeSourceType from "../validators/postBridgeSourceType.js";
import type * as validators_providerJobStatus from "../validators/providerJobStatus.js";
import type * as validators_providerJobType from "../validators/providerJobType.js";
import type * as validators_quickEditBaseline from "../validators/quickEditBaseline.js";
import type * as validators_quickEditCandidate from "../validators/quickEditCandidate.js";
import type * as validators_quickEditCandidateSignal from "../validators/quickEditCandidateSignal.js";
import type * as validators_quickEditCrop from "../validators/quickEditCrop.js";
import type * as validators_quickEditMetadata from "../validators/quickEditMetadata.js";
import type * as validators_quickEditOverlayText from "../validators/quickEditOverlayText.js";
import type * as validators_quickEditRemoveRange from "../validators/quickEditRemoveRange.js";
import type * as validators_quickEditSuggestions from "../validators/quickEditSuggestions.js";
import type * as validators_r2Object from "../validators/r2Object.js";
import type * as validators_replicateJobPurpose from "../validators/replicateJobPurpose.js";
import type * as validators_replicatePredictionStatus from "../validators/replicatePredictionStatus.js";
import type * as validators_stitchMusicMetadata from "../validators/stitchMusicMetadata.js";
import type * as validators_stitchScore from "../validators/stitchScore.js";
import type * as validators_stitchScoreReassessment from "../validators/stitchScoreReassessment.js";
import type * as validators_stitchSequenceSegment from "../validators/stitchSequenceSegment.js";
import type * as validators_stitchrHookFeedbackStatus from "../validators/stitchrHookFeedbackStatus.js";
import type * as validators_stitchrHookPlanSource from "../validators/stitchrHookPlanSource.js";
import type * as validators_stitchrHookPlanStatus from "../validators/stitchrHookPlanStatus.js";
import type * as validators_stitchrHookVariant from "../validators/stitchrHookVariant.js";
import type * as validators_stitchrMode from "../validators/stitchrMode.js";
import type * as validators_swaprMetadata from "../validators/swaprMetadata.js";
import type * as validators_swiprBackgroundSource from "../validators/swiprBackgroundSource.js";
import type * as validators_swiprCallToActionStyle from "../validators/swiprCallToActionStyle.js";
import type * as validators_swiprProductSourceType from "../validators/swiprProductSourceType.js";
import type * as validators_swiprSlide from "../validators/swiprSlide.js";
import type * as validators_textOverlay from "../validators/textOverlay.js";
import type * as validators_videoClipLibraryKind from "../validators/videoClipLibraryKind.js";
import type * as validators_videoPlaybackRate from "../validators/videoPlaybackRate.js";
import type * as validators_videoTrimRange from "../validators/videoTrimRange.js";
import type * as videoClips from "../videoClips.js";
import type * as videoClips_getHookLabVariantForMediaWorker from "../videoClips/getHookLabVariantForMediaWorker.js";
import type * as videoClips_saveHookLabVariantFromMediaWorker from "../videoClips/saveHookLabVariantFromMediaWorker.js";
import type * as waitlist from "../waitlist.js";
import type * as workerContinuationDelayMs from "../workerContinuationDelayMs.js";
import type * as workerDispatch from "../workerDispatch.js";
import type * as workerLaunch from "../workerLaunch.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  activeWorkerJobs: typeof activeWorkerJobs;
  adjustNotificationUnreadSummary: typeof adjustNotificationUnreadSummary;
  aggregateBackfills: typeof aggregateBackfills;
  aggregateCounts: typeof aggregateCounts;
  assertProductBelongsToOwner: typeof assertProductBelongsToOwner;
  assignLegacyRecordsToProduct: typeof assignLegacyRecordsToProduct;
  "auth/assertAutomationWorkerSecret": typeof auth_assertAutomationWorkerSecret;
  "auth/assertMediaWorkerSecret": typeof auth_assertMediaWorkerSecret;
  "auth/assertProviderWorkerSecret": typeof auth_assertProviderWorkerSecret;
  "auth/assertRateLimitApiSecret": typeof auth_assertRateLimitApiSecret;
  "auth/getAuthenticatedOwnerId": typeof auth_getAuthenticatedOwnerId;
  automationAvatarPhoto: typeof automationAvatarPhoto;
  automationBudget: typeof automationBudget;
  automationClipr: typeof automationClipr;
  automationCreateRun: typeof automationCreateRun;
  automationCreateTask: typeof automationCreateTask;
  automationGlobalWindow: typeof automationGlobalWindow;
  automationLimits: typeof automationLimits;
  automationMarkRunSkipped: typeof automationMarkRunSkipped;
  automationPlannerCandidates: typeof automationPlannerCandidates;
  automationPreferences: typeof automationPreferences;
  automationRuns: typeof automationRuns;
  automationScheduler: typeof automationScheduler;
  automationStitchr: typeof automationStitchr;
  automationStitchrPairScoring: typeof automationStitchrPairScoring;
  automationSwapr: typeof automationSwapr;
  automationSwipr: typeof automationSwipr;
  automationTasks: typeof automationTasks;
  avatarPreferences: typeof avatarPreferences;
  avatars: typeof avatars;
  "blogPostCards/estimateBlogPostReadingTimeMinutes": typeof blogPostCards_estimateBlogPostReadingTimeMinutes;
  "blogPostCards/getBlogPostCardFields": typeof blogPostCards_getBlogPostCardFields;
  "blogPostCards/upsertBlogPostCardBySlug": typeof blogPostCards_upsertBlogPostCardBySlug;
  blogPosts: typeof blogPosts;
  clearPostBridgeSocialAccountIdsForOwner: typeof clearPostBridgeSocialAccountIdsForOwner;
  "cliAuth/approveDeviceAuthorization": typeof cliAuth_approveDeviceAuthorization;
  "cliAuth/createDeviceAuthorization": typeof cliAuth_createDeviceAuthorization;
  "cliAuth/exchangeDeviceAuthorization": typeof cliAuth_exchangeDeviceAuthorization;
  "cliAuth/getActiveSessionByTokenHash": typeof cliAuth_getActiveSessionByTokenHash;
  "cliAuth/revokeSessionByTokenHash": typeof cliAuth_revokeSessionByTokenHash;
  "cliLibrary/addCliStitchPostBridgePost": typeof cliLibrary_addCliStitchPostBridgePost;
  "cliLibrary/addCliSwipePostBridgePost": typeof cliLibrary_addCliSwipePostBridgePost;
  "cliLibrary/cliLibraryListLimit": typeof cliLibrary_cliLibraryListLimit;
  "cliLibrary/getCliStitch": typeof cliLibrary_getCliStitch;
  "cliLibrary/getCliSwipe": typeof cliLibrary_getCliSwipe;
  "cliLibrary/listCliClips": typeof cliLibrary_listCliClips;
  "cliLibrary/listCliStitches": typeof cliLibrary_listCliStitches;
  "cliLibrary/listCliSwipes": typeof cliLibrary_listCliSwipes;
  "cliPostBridge/getCliPostBridgeSecret": typeof cliPostBridge_getCliPostBridgeSecret;
  "cliProducts/createCliProduct": typeof cliProducts_createCliProduct;
  "cliProducts/getCliProduct": typeof cliProducts_getCliProduct;
  "cliProducts/getCliProductDocument": typeof cliProducts_getCliProductDocument;
  "cliProducts/listCliProducts": typeof cliProducts_listCliProducts;
  "cliQueue/listCliQueueSourceSummaries": typeof cliQueue_listCliQueueSourceSummaries;
  "cliRateLimits/consumeCliPostBridgeMediaUpload": typeof cliRateLimits_consumeCliPostBridgeMediaUpload;
  "cliRateLimits/consumeCliPostBridgeRead": typeof cliRateLimits_consumeCliPostBridgeRead;
  "cliRateLimits/consumeCliPostBridgeSchedule": typeof cliRateLimits_consumeCliPostBridgeSchedule;
  "cliSwipr/getIsCliSwiprBatchRunId": typeof cliSwipr_getIsCliSwiprBatchRunId;
  "cliSwipr/planCliSwiprBatch": typeof cliSwipr_planCliSwiprBatch;
  "cliUploads/getCliUploadStatus": typeof cliUploads_getCliUploadStatus;
  cliprJobs: typeof cliprJobs;
  cliprPreferences: typeof cliprPreferences;
  createActiveAutomationBatchJobSummary: typeof createActiveAutomationBatchJobSummary;
  createAutomationRunSummaryFields: typeof createAutomationRunSummaryFields;
  createAutomationTaskSummaryFields: typeof createAutomationTaskSummaryFields;
  createCliprJobSummaryFields: typeof createCliprJobSummaryFields;
  createCompletedRunNotification: typeof createCompletedRunNotification;
  createNotification: typeof createNotification;
  createProductCardFields: typeof createProductCardFields;
  createQuickEditSuggestionsFromMetadata: typeof createQuickEditSuggestionsFromMetadata;
  createSoundTrackSnapshot: typeof createSoundTrackSnapshot;
  createStitchCardFields: typeof createStitchCardFields;
  createSwipeCardFields: typeof createSwipeCardFields;
  createSwiprBackgroundCardFields: typeof createSwiprBackgroundCardFields;
  createVideoClipCardFields: typeof createVideoClipCardFields;
  createWorkerJobSummaryFields: typeof createWorkerJobSummaryFields;
  crons: typeof crons;
  dashboardSummary: typeof dashboardSummary;
  defaultAutomationCliprVoiceId: typeof defaultAutomationCliprVoiceId;
  deleteAutomationRunSummary: typeof deleteAutomationRunSummary;
  deleteAutomationTaskSummary: typeof deleteAutomationTaskSummary;
  deleteCliprJobSummary: typeof deleteCliprJobSummary;
  deleteProductCard: typeof deleteProductCard;
  deleteStitchCard: typeof deleteStitchCard;
  deleteSwipeCard: typeof deleteSwipeCard;
  deleteSwiprBackgroundCard: typeof deleteSwiprBackgroundCard;
  deleteVideoClipCard: typeof deleteVideoClipCard;
  deleteWorkerJobSummary: typeof deleteWorkerJobSummary;
  getActiveWorkerJobSummary: typeof getActiveWorkerJobSummary;
  getAutomationBatchJobProgress: typeof getAutomationBatchJobProgress;
  getAutomationBatchJobStage: typeof getAutomationBatchJobStage;
  getAutomationBatchJobStatus: typeof getAutomationBatchJobStatus;
  getAutomationBatchJobType: typeof getAutomationBatchJobType;
  getAutomationPreferenceForProduct: typeof getAutomationPreferenceForProduct;
  getAutomationProductScopeKey: typeof getAutomationProductScopeKey;
  getAutomationRunHasIncompleteTasks: typeof getAutomationRunHasIncompleteTasks;
  getAutomationRunHasTasks: typeof getAutomationRunHasTasks;
  getAutomationTaskProductId: typeof getAutomationTaskProductId;
  getAutomationToolDisabledReason: typeof getAutomationToolDisabledReason;
  getAvatarNotificationCopy: typeof getAvatarNotificationCopy;
  getCliprGeneratedClipStorageFields: typeof getCliprGeneratedClipStorageFields;
  getCompletedRunAssetLabel: typeof getCompletedRunAssetLabel;
  getCompletedRunToolLabel: typeof getCompletedRunToolLabel;
  getDefaultAvatarForOwner: typeof getDefaultAvatarForOwner;
  getDefaultProductForOwner: typeof getDefaultProductForOwner;
  getEnabledAutomationToolsForPreference: typeof getEnabledAutomationToolsForPreference;
  getFirstStitchScoreUpdate: typeof getFirstStitchScoreUpdate;
  getOwnerHasContent: typeof getOwnerHasContent;
  getOwnerHasLegacyProductRecords: typeof getOwnerHasLegacyProductRecords;
  getOwnerHasStitches: typeof getOwnerHasStitches;
  getPhotoNotificationCopy: typeof getPhotoNotificationCopy;
  getPrimaryProductForOwner: typeof getPrimaryProductForOwner;
  getProductForOwner: typeof getProductForOwner;
  getProductNameFromAutomationTasks: typeof getProductNameFromAutomationTasks;
  getQuickEditOverlayText: typeof getQuickEditOverlayText;
  getQuickEditWithRemoveRanges: typeof getQuickEditWithRemoveRanges;
  getReadLimitedPaginationOpts: typeof getReadLimitedPaginationOpts;
  getRequiredVideoClipProductId: typeof getRequiredVideoClipProductId;
  getStitchNotificationCopy: typeof getStitchNotificationCopy;
  getStitchProductId: typeof getStitchProductId;
  getStitchRecipeByIdeaOrTemplate: typeof getStitchRecipeByIdeaOrTemplate;
  getSwipeCardSearchText: typeof getSwipeCardSearchText;
  getSwipeNotificationCopy: typeof getSwipeNotificationCopy;
  getSwiprBackgroundCardSearchText: typeof getSwiprBackgroundCardSearchText;
  getSwiprSwipeReferencedBackgroundIds: typeof getSwiprSwipeReferencedBackgroundIds;
  getVideoClipCanBePosted: typeof getVideoClipCanBePosted;
  getVideoClipCardSearchText: typeof getVideoClipCardSearchText;
  getVideoClipLibraryKind: typeof getVideoClipLibraryKind;
  getVideoClipNotificationCopy: typeof getVideoClipNotificationCopy;
  "hookLabDefaults/get": typeof hookLabDefaults_get;
  "hookLabDefaults/set": typeof hookLabDefaults_set;
  "hookLabIdeaUses/create": typeof hookLabIdeaUses_create;
  "hookLabIdeaUses/get": typeof hookLabIdeaUses_get;
  "hookLabIdeaUses/getHookLabVariationCount": typeof hookLabIdeaUses_getHookLabVariationCount;
  "hookLabIdeaVariants/attachProviderJob": typeof hookLabIdeaVariants_attachProviderJob;
  "hookLabIdeaVariants/completeFromMediaWorker": typeof hookLabIdeaVariants_completeFromMediaWorker;
  "hookLabIdeaVariants/dispatchProviderJob": typeof hookLabIdeaVariants_dispatchProviderJob;
  "hookLabIdeaVariants/failDispatch": typeof hookLabIdeaVariants_failDispatch;
  "hookLabIdeaVariants/failFinalizationJobFromMediaWorker": typeof hookLabIdeaVariants_failFinalizationJobFromMediaWorker;
  "hookLabIdeaVariants/failFromMediaWorker": typeof hookLabIdeaVariants_failFromMediaWorker;
  "hookLabIdeaVariants/failFromProvider": typeof hookLabIdeaVariants_failFromProvider;
  "hookLabIdeaVariants/failGenerationJobFromProvider": typeof hookLabIdeaVariants_failGenerationJobFromProvider;
  "hookLabIdeaVariants/getInputForProvider": typeof hookLabIdeaVariants_getInputForProvider;
  "hookLabIdeaVariants/markFinalizingFromProvider": typeof hookLabIdeaVariants_markFinalizingFromProvider;
  "hookLabIdeaVariants/markGeneratingFromProvider": typeof hookLabIdeaVariants_markGeneratingFromProvider;
  "hookLabIdeaVariants/recalculateHookLabIdeaUse": typeof hookLabIdeaVariants_recalculateHookLabIdeaUse;
  "hookLabIdeaVariants/recordGeneratedImageFromProvider": typeof hookLabIdeaVariants_recordGeneratedImageFromProvider;
  "hookLabIdeaVariants/recordGeneratedVideoFromProvider": typeof hookLabIdeaVariants_recordGeneratedVideoFromProvider;
  "hookLabIdeas/archive": typeof hookLabIdeas_archive;
  "hookLabIdeas/completeAnalysisFromProvider": typeof hookLabIdeas_completeAnalysisFromProvider;
  "hookLabIdeas/create": typeof hookLabIdeas_create;
  "hookLabIdeas/createHookLabIdeaSearchText": typeof hookLabIdeas_createHookLabIdeaSearchText;
  "hookLabIdeas/createHookLabStitchRecipeFromStitch": typeof hookLabIdeas_createHookLabStitchRecipeFromStitch;
  "hookLabIdeas/failAnalysisFromProvider": typeof hookLabIdeas_failAnalysisFromProvider;
  "hookLabIdeas/failAnalysisJobFromProvider": typeof hookLabIdeas_failAnalysisJobFromProvider;
  "hookLabIdeas/getForProvider": typeof hookLabIdeas_getForProvider;
  "hookLabIdeas/getHookLabIdeaDefaultName": typeof hookLabIdeas_getHookLabIdeaDefaultName;
  "hookLabIdeas/getHookLabIdeaMatchesListFilters": typeof hookLabIdeas_getHookLabIdeaMatchesListFilters;
  "hookLabIdeas/getHookLabOriginalTextFromStitch": typeof hookLabIdeas_getHookLabOriginalTextFromStitch;
  "hookLabIdeas/getHookLabPromptBlueprints": typeof hookLabIdeas_getHookLabPromptBlueprints;
  "hookLabIdeas/linkHookOptionToIdea": typeof hookLabIdeas_linkHookOptionToIdea;
  "hookLabIdeas/list": typeof hookLabIdeas_list;
  "hookLabIdeas/listPromptMemory": typeof hookLabIdeas_listPromptMemory;
  "hookLabIdeas/listStitchSources": typeof hookLabIdeas_listStitchSources;
  "hookLabIdeas/markAnalysisDispatchFailed": typeof hookLabIdeas_markAnalysisDispatchFailed;
  "hookLabIdeas/prepareProviderRun": typeof hookLabIdeas_prepareProviderRun;
  "hookLabIdeas/recordProviderRun": typeof hookLabIdeas_recordProviderRun;
  "hookLabIdeas/remove": typeof hookLabIdeas_remove;
  "hookLabIdeas/retry": typeof hookLabIdeas_retry;
  "hookLabIdeas/update": typeof hookLabIdeas_update;
  isWithinAutomationGlobalWindow: typeof isWithinAutomationGlobalWindow;
  libraryCounts: typeof libraryCounts;
  listActiveAutomationBatchJobSummaries: typeof listActiveAutomationBatchJobSummaries;
  listActiveWorkerJobSummaries: typeof listActiveWorkerJobSummaries;
  listProductsForOwnerByIds: typeof listProductsForOwnerByIds;
  listRecentAvatarPhotoAssets: typeof listRecentAvatarPhotoAssets;
  listRecentProductsForOwner: typeof listRecentProductsForOwner;
  listRecentVideoClipCardsByLibraryKind: typeof listRecentVideoClipCardsByLibraryKind;
  listRecentVideoClipsByLibraryKind: typeof listRecentVideoClipsByLibraryKind;
  logConvexTransactionMetrics: typeof logConvexTransactionMetrics;
  markAutomationRunCompletedIfAllTasksDone: typeof markAutomationRunCompletedIfAllTasksDone;
  markAutomationRunCompletedWhenTasksDone: typeof markAutomationRunCompletedWhenTasksDone;
  markAutomationRunStatus: typeof markAutomationRunStatus;
  mediaJobs: typeof mediaJobs;
  mediaWorkerLaunch: typeof mediaWorkerLaunch;
  "migrations/createHookLabStitchRecipeFromTemplate": typeof migrations_createHookLabStitchRecipeFromTemplate;
  "migrations/createMigratedHookLabCreativeBeat": typeof migrations_createMigratedHookLabCreativeBeat;
  "migrations/createMigratedHookLabTextBlueprint": typeof migrations_createMigratedHookLabTextBlueprint;
  "migrations/getHookLabMigrationStatus": typeof migrations_getHookLabMigrationStatus;
  "migrations/getHookLabTemplateOriginalText": typeof migrations_getHookLabTemplateOriginalText;
  "migrations/migrateStitchTemplatesToHookLabIdeas": typeof migrations_migrateStitchTemplatesToHookLabIdeas;
  "migrations/migrateStitchrHookOptions": typeof migrations_migrateStitchrHookOptions;
  "migrations/migrateWinningHooksToHookLabIdeas": typeof migrations_migrateWinningHooksToHookLabIdeas;
  normalizeQuickEditRemoveRanges: typeof normalizeQuickEditRemoveRanges;
  notifications: typeof notifications;
  photoAssets: typeof photoAssets;
  postBridgePostProductMappings: typeof postBridgePostProductMappings;
  postBridgeSettings: typeof postBridgeSettings;
  productPreferences: typeof productPreferences;
  products: typeof products;
  "providerJobAttempts/retryAfterFailure": typeof providerJobAttempts_retryAfterFailure;
  providerJobs: typeof providerJobs;
  providerWorkerLaunch: typeof providerWorkerLaunch;
  rateLimiter: typeof rateLimiter;
  rateLimits: typeof rateLimits;
  readModelBackfills: typeof readModelBackfills;
  recordStitchrBatchPairHistory: typeof recordStitchrBatchPairHistory;
  replicateJobs: typeof replicateJobs;
  sharedMusicTracks: typeof sharedMusicTracks;
  soundPreferences: typeof soundPreferences;
  "stitchTemplates/createAutomaticStitchTemplateFromAcceptedHookPlan": typeof stitchTemplates_createAutomaticStitchTemplateFromAcceptedHookPlan;
  "stitchTemplates/createAutomaticStitchTemplateFromAcceptedHookStitch": typeof stitchTemplates_createAutomaticStitchTemplateFromAcceptedHookStitch;
  "stitchTemplates/createFromStitch": typeof stitchTemplates_createFromStitch;
  "stitchTemplates/createStitchTemplateDocumentFromStitch": typeof stitchTemplates_createStitchTemplateDocumentFromStitch;
  "stitchTemplates/get": typeof stitchTemplates_get;
  "stitchTemplates/getAcceptedHookTemplateId": typeof stitchTemplates_getAcceptedHookTemplateId;
  "stitchTemplates/getAcceptedHookTemplateName": typeof stitchTemplates_getAcceptedHookTemplateName;
  "stitchTemplates/getAcceptedHookTextFromPlan": typeof stitchTemplates_getAcceptedHookTextFromPlan;
  "stitchTemplates/getStitchTemplateBatchTextOverlay": typeof stitchTemplates_getStitchTemplateBatchTextOverlay;
  "stitchTemplates/getStitchTemplateTextOverlaysForAcceptedHook": typeof stitchTemplates_getStitchTemplateTextOverlaysForAcceptedHook;
  "stitchTemplates/list": typeof stitchTemplates_list;
  "stitchTemplates/remove": typeof stitchTemplates_remove;
  "stitchTemplates/updateName": typeof stitchTemplates_updateName;
  stitches: typeof stitches;
  "stitches/saveHookLabVariantFromMediaWorker": typeof stitches_saveHookLabVariantFromMediaWorker;
  stitchrBatch: typeof stitchrBatch;
  stitchrBatchRunId: typeof stitchrBatchRunId;
  "stitchrHookOptions/listReview": typeof stitchrHookOptions_listReview;
  "stitchrHookOptions/markNotForMe": typeof stitchrHookOptions_markNotForMe;
  "stitchrHookOptions/select": typeof stitchrHookOptions_select;
  "stitchrHookOptions/syncStitchrHookOptionsFromPlan": typeof stitchrHookOptions_syncStitchrHookOptionsFromPlan;
  "stitchrHookOptions/undoFeedback": typeof stitchrHookOptions_undoFeedback;
  stitchrHookPlans: typeof stitchrHookPlans;
  swipes: typeof swipes;
  swiprBackgrounds: typeof swiprBackgrounds;
  upsertAutomationRunSummary: typeof upsertAutomationRunSummary;
  upsertAutomationTaskSummary: typeof upsertAutomationTaskSummary;
  upsertCliprJobSummary: typeof upsertCliprJobSummary;
  upsertProductCard: typeof upsertProductCard;
  upsertStitchCard: typeof upsertStitchCard;
  upsertSwipeCard: typeof upsertSwipeCard;
  upsertSwiprBackgroundCard: typeof upsertSwiprBackgroundCard;
  upsertVideoClipCard: typeof upsertVideoClipCard;
  upsertWorkerJobSummary: typeof upsertWorkerJobSummary;
  "validators/assetTags": typeof validators_assetTags;
  "validators/automationCliprGenerationMode": typeof validators_automationCliprGenerationMode;
  "validators/automationGenerationCount": typeof validators_automationGenerationCount;
  "validators/automationProvenance": typeof validators_automationProvenance;
  "validators/automationRunStatus": typeof validators_automationRunStatus;
  "validators/automationSelectionMode": typeof validators_automationSelectionMode;
  "validators/automationStitchrTemplateAllocation": typeof validators_automationStitchrTemplateAllocation;
  "validators/automationStitchrTextStyleChoice": typeof validators_automationStitchrTextStyleChoice;
  "validators/automationTaskStatus": typeof validators_automationTaskStatus;
  "validators/automationTaskType": typeof validators_automationTaskType;
  "validators/automationTool": typeof validators_automationTool;
  "validators/avatarWardrobeStyle": typeof validators_avatarWardrobeStyle;
  "validators/blogPostContentFormat": typeof validators_blogPostContentFormat;
  "validators/cliDeviceAuthorizationStatus": typeof validators_cliDeviceAuthorizationStatus;
  "validators/clipPerformanceScore": typeof validators_clipPerformanceScore;
  "validators/clipType": typeof validators_clipType;
  "validators/cliprDurationSeconds": typeof validators_cliprDurationSeconds;
  "validators/cliprGenerationMode": typeof validators_cliprGenerationMode;
  "validators/cliprJobStage": typeof validators_cliprJobStage;
  "validators/cliprJobStatus": typeof validators_cliprJobStatus;
  "validators/cliprMetadata": typeof validators_cliprMetadata;
  "validators/cliprMusicMetadata": typeof validators_cliprMusicMetadata;
  "validators/cliprResolvedGenerationMode": typeof validators_cliprResolvedGenerationMode;
  "validators/cliprScenePlan": typeof validators_cliprScenePlan;
  "validators/cliprVideoModelId": typeof validators_cliprVideoModelId;
  "validators/hookLabCreativeBeat": typeof validators_hookLabCreativeBeat;
  "validators/hookLabIdeaScope": typeof validators_hookLabIdeaScope;
  "validators/hookLabIdeaScopeFilter": typeof validators_hookLabIdeaScopeFilter;
  "validators/hookLabIdeaSourceType": typeof validators_hookLabIdeaSourceType;
  "validators/hookLabIdeaStatus": typeof validators_hookLabIdeaStatus;
  "validators/hookLabIdeaStatusFilter": typeof validators_hookLabIdeaStatusFilter;
  "validators/hookLabIdeaUseStatus": typeof validators_hookLabIdeaUseStatus;
  "validators/hookLabIdeaVariantStatus": typeof validators_hookLabIdeaVariantStatus;
  "validators/hookLabReviewState": typeof validators_hookLabReviewState;
  "validators/hookLabStitchRecipe": typeof validators_hookLabStitchRecipe;
  "validators/hookLabTextBlueprint": typeof validators_hookLabTextBlueprint;
  "validators/hookLabTextDecision": typeof validators_hookLabTextDecision;
  "validators/librarySortOrder": typeof validators_librarySortOrder;
  "validators/mediaJobStatus": typeof validators_mediaJobStatus;
  "validators/mediaJobType": typeof validators_mediaJobType;
  "validators/musicTrackSource": typeof validators_musicTrackSource;
  "validators/notificationSourceType": typeof validators_notificationSourceType;
  "validators/postBridgeMediaKind": typeof validators_postBridgeMediaKind;
  "validators/postBridgePlatform": typeof validators_postBridgePlatform;
  "validators/postBridgePostReference": typeof validators_postBridgePostReference;
  "validators/postBridgePostStatus": typeof validators_postBridgePostStatus;
  "validators/postBridgeSourceType": typeof validators_postBridgeSourceType;
  "validators/providerJobStatus": typeof validators_providerJobStatus;
  "validators/providerJobType": typeof validators_providerJobType;
  "validators/quickEditBaseline": typeof validators_quickEditBaseline;
  "validators/quickEditCandidate": typeof validators_quickEditCandidate;
  "validators/quickEditCandidateSignal": typeof validators_quickEditCandidateSignal;
  "validators/quickEditCrop": typeof validators_quickEditCrop;
  "validators/quickEditMetadata": typeof validators_quickEditMetadata;
  "validators/quickEditOverlayText": typeof validators_quickEditOverlayText;
  "validators/quickEditRemoveRange": typeof validators_quickEditRemoveRange;
  "validators/quickEditSuggestions": typeof validators_quickEditSuggestions;
  "validators/r2Object": typeof validators_r2Object;
  "validators/replicateJobPurpose": typeof validators_replicateJobPurpose;
  "validators/replicatePredictionStatus": typeof validators_replicatePredictionStatus;
  "validators/stitchMusicMetadata": typeof validators_stitchMusicMetadata;
  "validators/stitchScore": typeof validators_stitchScore;
  "validators/stitchScoreReassessment": typeof validators_stitchScoreReassessment;
  "validators/stitchSequenceSegment": typeof validators_stitchSequenceSegment;
  "validators/stitchrHookFeedbackStatus": typeof validators_stitchrHookFeedbackStatus;
  "validators/stitchrHookPlanSource": typeof validators_stitchrHookPlanSource;
  "validators/stitchrHookPlanStatus": typeof validators_stitchrHookPlanStatus;
  "validators/stitchrHookVariant": typeof validators_stitchrHookVariant;
  "validators/stitchrMode": typeof validators_stitchrMode;
  "validators/swaprMetadata": typeof validators_swaprMetadata;
  "validators/swiprBackgroundSource": typeof validators_swiprBackgroundSource;
  "validators/swiprCallToActionStyle": typeof validators_swiprCallToActionStyle;
  "validators/swiprProductSourceType": typeof validators_swiprProductSourceType;
  "validators/swiprSlide": typeof validators_swiprSlide;
  "validators/textOverlay": typeof validators_textOverlay;
  "validators/videoClipLibraryKind": typeof validators_videoClipLibraryKind;
  "validators/videoPlaybackRate": typeof validators_videoPlaybackRate;
  "validators/videoTrimRange": typeof validators_videoTrimRange;
  videoClips: typeof videoClips;
  "videoClips/getHookLabVariantForMediaWorker": typeof videoClips_getHookLabVariantForMediaWorker;
  "videoClips/saveHookLabVariantFromMediaWorker": typeof videoClips_saveHookLabVariantFromMediaWorker;
  waitlist: typeof waitlist;
  workerContinuationDelayMs: typeof workerContinuationDelayMs;
  workerDispatch: typeof workerDispatch;
  workerLaunch: typeof workerLaunch;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  videoClipCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"videoClipCounts">;
  videoClipProductCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"videoClipProductCounts">;
  stitchCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"stitchCounts">;
  stitchProductCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"stitchProductCounts">;
};
