import type { PublicVideoExample } from "@/lib/clipstitchr/types/PublicVideoExample";

const publishedAt = "2026-05-27T00:00:00-04:00";

export const publicVideoExamples: PublicVideoExample[] = [
  {
    id: "clipstitchr-example-11",
    slug: "stitchr-boyfriend-ten-out-of-ten",
    title: "Stitchr Boyfriend 10 Out Of 10 Fitness Ad Example",
    description:
      "A Stitchr example that opens with a creator reaction hook, then moves into a dark fitness-app demo that measures strength progress.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-11.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-11.jpg",
    durationSeconds: 13,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "fitness app", "creator hook", "product demo"],
  },
  {
    id: "clipstitchr-example-02",
    slug: "stitchr-boyfriend-strength-demo",
    title: "Stitchr Boyfriend Strength Demo Ad Example",
    description:
      "A vertical Stitchr output where a creator hook about strength leads into a fitness-app progress screen.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-02.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-02.jpg",
    durationSeconds: 16,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "fitness app", "creator reaction", "demo"],
  },
  {
    id: "clipstitchr-example-06",
    slug: "stitchr-motivation-fitness-demo",
    title: "Stitchr Motivation Hook Fitness Demo Example",
    description:
      "A Stitchr sample that pairs a close-up motivation hook with a fitness-app scoring demo for a short-form ad flow.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-06.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-06.jpg",
    durationSeconds: 17,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "fitness app", "motivation", "ugc hook"],
  },
  {
    id: "clipstitchr-example-15",
    slug: "stitchr-calisthenics-body-scan",
    title: "Stitchr Calisthenics Body Scan Ad Example",
    description:
      "A Stitchr output that combines calisthenics transformation footage with a body-scan style product demo.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-15.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-15.jpg",
    durationSeconds: 20,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "calisthenics", "body scan", "fitness demo"],
  },
  {
    id: "clipstitchr-example-10",
    slug: "stitchr-fitness-change-score",
    title: "Stitchr Fitness Change Score Ad Example",
    description:
      "A Stitchr sample where a creator reaction hook transitions into a fitness score screen and starting recommendations.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-10.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-10.jpg",
    durationSeconds: 11,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "fitness score", "creator reaction", "app demo"],
  },
  {
    id: "clipstitchr-example-03",
    slug: "stitchr-never-work-fitness-demo",
    title: "Stitchr Never Work Fitness Demo Example",
    description:
      "A creator-style Stitchr ad example that uses a skeptical hook before showing a fitness-app progress demo.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-03.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-03.jpg",
    durationSeconds: 15,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "skeptical hook", "fitness app", "short-form ad"],
  },
  {
    id: "clipstitchr-example-07",
    slug: "stitchr-people-quit-demo",
    title: "Stitchr People Quit Fitness Demo Example",
    description:
      "A Stitchr output that places a high-energy creator hook before a fitness-app demo for vertical ad testing.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-07.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-07.jpg",
    durationSeconds: 19,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "fitness app", "ugc-style hook", "demo"],
  },
  {
    id: "clipstitchr-example-13",
    slug: "clipr-calisthenics-talking-head",
    title: "Clipr Calisthenics Talking Head Clip Example",
    description:
      "A Clipr example clip with a creator speaking directly to camera about calisthenics from a home workout setting.",
    kind: "Clipr clip",
    videoSrc: "/example-outputs/clipstitchr-example-13.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-13.jpg",
    durationSeconds: 42,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["clipr", "calisthenics", "talking head", "source clip"],
  },
  {
    id: "clipstitchr-example-14",
    slug: "clipr-home-gym-talking-head",
    title: "Clipr Home Gym Talking Head Clip Example",
    description:
      "A Clipr generated talking-head example filmed in a home gym setting for use as reusable source footage.",
    kind: "Clipr clip",
    videoSrc: "/example-outputs/clipstitchr-example-14.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-14.jpg",
    durationSeconds: 37,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["clipr", "home gym", "talking head", "creator clip"],
  },
  {
    id: "clipstitchr-example-20",
    slug: "stitchr-before-after-calisthenics",
    title: "Stitchr Before And After Calisthenics Ad Example",
    description:
      "A Stitchr fitness example that cuts from before-and-after calisthenics footage into an app-style progress moment.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-20.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-20.jpg",
    durationSeconds: 9,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "before after", "calisthenics", "fitness app"],
  },
  {
    id: "clipstitchr-example-17",
    slug: "swapr-maribel-fitness-hook",
    title: "Swapr Fitness Hook Swap Example",
    description:
      "A Swapr-style creator variation showing an indoor fitness hook that can be saved back into the UGC library.",
    kind: "Swapr swap",
    videoSrc: "/example-outputs/clipstitchr-example-17.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-17.jpg",
    durationSeconds: 11,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["swapr", "creator variation", "fitness hook", "ugc source"],
  },
  {
    id: "clipstitchr-example-16",
    slug: "swapr-surprised-closeup-reaction",
    title: "Swapr Surprised Close-Up Reaction Example",
    description:
      "A short Swapr-style reaction variation with a close-up surprised expression for use as UGC-style source footage.",
    kind: "Swapr swap",
    videoSrc: "/example-outputs/clipstitchr-example-16.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-16.jpg",
    durationSeconds: 4,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["swapr", "reaction", "close-up", "ugc source"],
  },
  {
    id: "clipstitchr-example-08",
    slug: "stitchr-partner-training-demo",
    title: "Stitchr Partner Training Fitness Demo Example",
    description:
      "A Stitchr example that pairs a partner-training hook with a fitness-app progress demo for short-form ad output.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-08.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-08.jpg",
    durationSeconds: 18,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "partner training", "fitness app", "ugc hook"],
  },
  {
    id: "clipstitchr-example-04",
    slug: "stitchr-waste-money-demo",
    title: "Stitchr Waste Of Money Fitness Demo Example",
    description:
      "A Stitchr ad example using a money-objection creator hook before moving into a fitness-app result screen.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-04.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-04.jpg",
    durationSeconds: 14,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "objection hook", "fitness app", "demo"],
  },
  {
    id: "clipstitchr-example-19",
    slug: "stitchr-calisthenics-before-hook",
    title: "Stitchr Calisthenics Before Hook Ad Example",
    description:
      "A compact Stitchr sample where a calisthenics before-state hook leads into a fitness-app demo moment.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-19.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-19.jpg",
    durationSeconds: 9,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "calisthenics", "before state", "fitness demo"],
  },
  {
    id: "clipstitchr-example-18",
    slug: "clipr-indoor-talking-head",
    title: "Clipr Indoor Talking Head Clip Example",
    description:
      "A Clipr example clip with a creator speaking indoors, ready to use as source footage in Stitchr.",
    kind: "Clipr clip",
    videoSrc: "/example-outputs/clipstitchr-example-18.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-18.jpg",
    durationSeconds: 30,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["clipr", "talking head", "indoor creator", "source clip"],
  },
  {
    id: "clipstitchr-example-09",
    slug: "stitchr-doing-it-wrong-demo",
    title: "Stitchr Doing It Wrong Fitness Demo Example",
    description:
      "A Stitchr sample that uses a corrective creator hook before showing a fitness-app progress demo.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-09.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-09.jpg",
    durationSeconds: 17,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "fitness app", "corrective hook", "product demo"],
  },
  {
    id: "clipstitchr-example-21",
    slug: "clipr-solo-quest-xp-hook",
    title: "Clipr Solo Quest XP Hook Clip Example",
    description:
      "A longer Clipr talking-head example built around a solo quest and XP-style hook for reusable source footage.",
    kind: "Clipr clip",
    videoSrc: "/example-outputs/clipstitchr-example-21.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-21.jpg",
    durationSeconds: 48,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["clipr", "solo quest", "talking head", "source clip"],
  },
  {
    id: "clipstitchr-example-05",
    slug: "stitchr-gym-routine-demo",
    title: "Stitchr Gym Routine Fitness Demo Example",
    description:
      "A Stitchr ad example where a gym-routine hook transitions into a dark fitness-app analysis screen.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-05.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-05.jpg",
    durationSeconds: 16,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "gym routine", "fitness app", "analysis"],
  },
  {
    id: "clipstitchr-example-01",
    slug: "stitchr-fitness-score-reaction",
    title: "Stitchr Fitness Score Reaction Ad Example",
    description:
      "A Stitchr output that combines a creator reaction hook with a fitness-app percentage score demo.",
    kind: "Stitchr stitch",
    videoSrc: "/example-outputs/clipstitchr-example-01.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-01.jpg",
    durationSeconds: 13,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["stitchr", "reaction hook", "fitness score", "app demo"],
  },
  {
    id: "clipstitchr-example-12",
    slug: "swapr-surprised-reaction-clip",
    title: "Swapr Surprised Reaction Swap Example",
    description:
      "A short Swapr-style surprised reaction variation that can work as a UGC hook or reaction insert.",
    kind: "Swapr swap",
    videoSrc: "/example-outputs/clipstitchr-example-12.webm",
    thumbnailSrc: "/example-outputs/posters/clipstitchr-example-12.jpg",
    durationSeconds: 4,
    uploadDate: publishedAt,
    width: 540,
    height: 960,
    tags: ["swapr", "reaction", "ugc hook", "creator variation"],
  },
];
