import type { ShortFormVideoSpecRecord } from "@/lib/clipstitchr/tools/shortFormVideoSpecs/ShortFormVideoSpecRecord";

const notStated = "Not stated on the linked source page";

export const shortFormVideoSpecRecords: readonly ShortFormVideoSpecRecord[] = [
  {
    audio: "Use sound or music",
    codec: notStated,
    containers: notStated,
    dimensions: "At least 720p; the page does not give a pixel pair",
    duration: notStated,
    fileLimit: notStated,
    frameRate: notStated,
    id: "tiktok-performance-creative",
    lastVerified: "2026-07-12",
    placement: "Performance ads — creative starting point",
    platform: "TikTok",
    practicalNotes: [
      "Shoot vertically in 9:16 and keep content visible inside the interface safe zone.",
      "TikTok recommends introducing the proposition in the first three seconds and prioritizing the hook in the first six seconds.",
      "This page presents general best practices, not a complete delivery specification.",
    ],
    ratio: "9:16 vertical",
    sourceTitle: "Creative best practices for performance ads",
    sourceUrl: "https://ads.tiktok.com/help/article/creative-best-practices",
  },
  {
    audio: "Required for all video creatives",
    codec: notStated,
    containers: ".mp4, .mov, .mpeg, .3gp",
    dimensions: "Vertical: at least 540 × 960 px",
    duration: "5–60 seconds; TikTok recommends 9–15 seconds",
    fileLimit: "500 MB maximum; bitrate at least 2,500 kbps",
    frameRate: notStated,
    id: "tiktok-reservation-push",
    lastVerified: "2026-07-12",
    placement: "Reservation In-Feed — Non-Spark and Spark Ads Push",
    platform: "TikTok",
    practicalNotes: [
      "Vertical is recommended; the same source also lists horizontal and square minimums.",
      "Keep key text and logos inside the matching TikTok safe-zone file for your dimensions, caption length, and add-ons.",
      "Avoid watermarks and do not make the creative imitate TikTok's interface.",
    ],
    ratio: "9:16 recommended",
    sourceTitle:
      "TikTok reservation in-feed ad specifications (including Reach & Frequency)",
    sourceUrl:
      "https://ads.tiktok.com/help/article/tiktok-reservation-in-feed-ads-reach-frequency",
  },
  {
    audio: "Required for all video creatives",
    codec: notStated,
    containers: ".mp4 or .mov normally",
    dimensions:
      "No separate restriction stated for a successfully published TikTok video",
    duration:
      "No separate restriction stated; the organic video must publish successfully",
    fileLimit: notStated,
    frameRate: notStated,
    id: "tiktok-reservation-spark-pull",
    lastVerified: "2026-07-12",
    placement: "Reservation In-Feed — Spark Ads Pull",
    platform: "TikTok",
    practicalNotes: [
      "The ad pulls an existing organic TikTok video, so the source defers to what the app accepted.",
      "This is not permission to ignore safe placement; TikTok still warns that interface elements may cover or crop key content.",
      "Use TikTok's placement preview before launch.",
    ],
    ratio: "Determined by the successfully published organic video",
    sourceTitle:
      "TikTok reservation in-feed ad specifications (including Reach & Frequency)",
    sourceUrl:
      "https://ads.tiktok.com/help/article/tiktok-reservation-in-feed-ads-reach-frequency",
  },
  {
    audio: notStated,
    codec: notStated,
    containers: notStated,
    dimensions: "Minimum resolution of 720 pixels; no exact pixel pair stated",
    duration: notStated,
    fileLimit: notStated,
    frameRate: "Minimum 30 FPS",
    id: "instagram-organic-reels",
    lastVerified: "2026-07-12",
    placement: "Organic Instagram Reels",
    platform: "Instagram Reels",
    practicalNotes: [
      "Instagram accepts ratios from 1.91:1 through 9:16 on this help page.",
      "For a full-screen vertical workflow, record and compose in 9:16.",
      "The recommended cover is 420 × 654 px (1:1.55), and the page says it cannot currently be edited after upload.",
    ],
    ratio: "1.91:1 through 9:16 accepted",
    sourceTitle: "Reel size & aspect ratios on Instagram",
    sourceUrl: "https://www.facebook.com/help/1038071743007909",
  },
  {
    audio: "Quality audio is part of Meta's stated Reels creative essentials",
    codec: notStated,
    containers: notStated,
    dimensions: notStated,
    duration: notStated,
    fileLimit: notStated,
    frameRate: notStated,
    id: "meta-reels-ads-creative",
    lastVerified: "2026-07-12",
    placement: "Facebook and Instagram Reels ads — creative essentials",
    platform: "Instagram Reels",
    practicalNotes: [
      "Meta recommends vertical 9:16 video, quality audio, and key messages inside the safe zone.",
      "The linked page is creative guidance, not a complete upload-specification table.",
      "Use Ads Manager's current placement preview and safe-zone checker for the final asset.",
    ],
    ratio: "9:16 vertical recommended",
    sourceTitle: "Instagram & Facebook Reels: Create Short Video Ads",
    sourceUrl:
      "https://www.facebook.com/business/ads/facebook-instagram-reels-ads",
  },
  {
    audio: "Use sound: music, voiceover, or both",
    codec: notStated,
    containers: notStated,
    dimensions: notStated,
    duration:
      "Up to 3 minutes; only the first 60 seconds play in the Shorts feed; less than 60 seconds recommended",
    fileLimit: notStated,
    frameRate: notStated,
    id: "youtube-shorts-ads",
    lastVerified: "2026-07-12",
    placement: "YouTube Shorts ads — general asset guidance",
    platform: "YouTube Shorts",
    practicalNotes: [
      "Upload the video to YouTube as public or unlisted before using it as an ad.",
      "Vertical assets are recommended; horizontal assets can appear with blurred areas above and below.",
      "For action-oriented ads, Google recommends 10–30 second vertical videos, while campaign eligibility can vary by campaign type.",
    ],
    ratio: "9:16 vertical recommended",
    sourceTitle: "YouTube Shorts ads: Asset specs and best practices",
    sourceUrl: "https://support.google.com/google-ads/answer/16041697",
  },
  {
    audio: notStated,
    codec: "MPEG-2 or MPEG-4 (source wording)",
    containers: "MPG (source wording)",
    dimensions: "1080 × 1920 px recommended for HD",
    duration: "Minimum 5 seconds",
    fileLimit: "256 GB maximum video file",
    frameRate: notStated,
    id: "youtube-demand-gen-shorts",
    lastVerified: "2026-07-12",
    placement: "YouTube Shorts inventory — Demand Gen video asset",
    platform: "YouTube Shorts",
    practicalNotes: [
      "Google lists 9:16 as the recommended vertical orientation for YouTube Shorts.",
      "Videos shorter than 10 seconds are ineligible for YouTube In-stream, which is a separate placement consideration.",
      "Google says its format mocks are not exhaustive and recommends checking the in-platform preview.",
    ],
    ratio: "9:16",
    sourceTitle:
      "Video asset specifications and ad format guidelines for Demand Gen campaigns",
    sourceUrl: "https://support.google.com/google-ads/answer/17141078",
  },
];
