export const OAUTH_STATE_ENTROPY_BYTES = 32;
export const OAUTH_PKCE_VERIFIER_BYTES = 32;
export const OAUTH_STATE_DEFAULT_TTL_SECONDS = 300;
export const OAUTH_STATE_MIN_TTL_SECONDS = 60;
export const OAUTH_STATE_MAX_TTL_SECONDS = 600;
export const OAUTH_STATE_STORAGE_ATTEMPTS = 3;
