import type { CollectionResourceItem } from "@/lib/clipstitchr/tools/resources/CollectionResourceItem";

const appCategoryHookPackEntries = [
  [
    "Fitness",
    "The repeatable starting point",
    "When I do not know what to train, I open [app] and start with [visible choice].",
    "When I do not know what to train, I open MoveNote and start with the routine I already saved.",
    "Show a planning choice, not a promise that the workout is medically appropriate or effective.",
  ],
  [
    "Fitness",
    "The workout record",
    "This is how I remember [specific workout detail] from my last session.",
    "This is how I remember which weight and variation I logged last time.",
    "Describe recorded data only; do not imply progress, strength, or health improvement.",
  ],
  [
    "Fitness",
    "The routine adjustment",
    "My plan changed today, so I changed [one routine detail] here.",
    "My plan changed today, so I moved the long session and kept the short mobility block.",
    "Do not frame an app adjustment as medical or professional exercise advice.",
  ],
  [
    "Fitness",
    "The no-perfect-streak restart",
    "I missed [time period]. Here is where I restart without pretending the streak never broke.",
    "I missed a week. Here is where I choose today's routine without hiding the gap.",
    "Avoid habit, motivation, or health guarantees; show the real restart flow.",
  ],
  [
    "Fitness",
    "The exercise note",
    "I save [form cue or preference] here so I can read it before the next set.",
    "I save my coach's setup cue here so I can read it before the next set.",
    "Do not create safety instructions or present a personal note as expert guidance.",
  ],
  [
    "Fitness",
    "The plan overview",
    "One screen shows how I arranged [days, routines, or sessions] this week.",
    "One screen shows how I arranged two gym days and one at-home routine this week.",
    "The view can show a plan; it cannot guarantee completion or results.",
  ],
  [
    "Fitness",
    "The equipment filter",
    "I only have [equipment], so I filter the options before choosing.",
    "I only have resistance bands today, so I filter the saved routines before choosing.",
    "Do not imply a filter verifies suitability, safety, or equivalent training outcomes.",
  ],
  [
    "Fitness",
    "The personal comparison",
    "Here is what I logged for [activity] then, and what I logged today.",
    "Here is the duration I logged for Tuesday's walk, and what I logged today.",
    "Keep it to accurate personal records and avoid transformation or performance promises.",
  ],
  [
    "Fitness",
    "The coach handoff",
    "Before I talk with [coach or trainer], I bring this record of [specific information].",
    "Before I talk with my trainer, I bring the routine notes and completed-set history.",
    "Do not imply records replace professional evaluation or medical history.",
  ],
  [
    "Fitness",
    "The honest app boundary",
    "[App] does not choose what is safe for me. It helps me [supported planning or tracking job].",
    "MoveNote does not choose what is safe for me. It helps me organize the routines I already use.",
    "Keep the boundary explicit and never imply diagnosis, treatment, or guaranteed body changes.",
  ],
  [
    "Finance",
    "The transaction context",
    "I add [note or label] here so I remember what this transaction was for.",
    "I add the client and project here so I remember what this software charge supported.",
    "Describe organization only; do not imply bookkeeping accuracy, tax treatment, or financial advice.",
  ],
  [
    "Finance",
    "The upcoming view",
    "This is where I look before [bill, renewal, or planned purchase] comes up.",
    "This is where I look before annual software renewals come up.",
    "A reminder view does not guarantee payment, sufficient funds, or avoidance of fees.",
  ],
  [
    "Finance",
    "The category check",
    "I thought I spent mostly on [category], so I checked the actual entries.",
    "I thought I spent mostly on ads, so I checked the actual campaign and production entries.",
    "Present the user's own records without drawing investment, tax, or credit conclusions.",
  ],
  [
    "Finance",
    "The assumption toggle",
    "I changed [one assumption] to see how this planning scenario moved.",
    "I changed the monthly subscription assumption to see how the runway scenario moved.",
    "Label scenarios clearly and do not present them as forecasts or guaranteed outcomes.",
  ],
  [
    "Finance",
    "The shared money question",
    "Before we discuss [shared expense], I put the same numbers in one view.",
    "Before we discuss the campaign budget, I put media and creative costs in one view.",
    "Do not imply shared visibility resolves disputes or establishes legal responsibility.",
  ],
  [
    "Finance",
    "The manual check",
    "Before I trust [summary number], I open the entries behind it.",
    "Before I trust the monthly total, I open the charges and refunds behind it.",
    "Do not claim accuracy, bank-grade security, or completeness unless independently supported.",
  ],
  [
    "Finance",
    "The personal threshold",
    "I set my own [budget or alert threshold] here, then review what crosses it.",
    "I set my own monthly contractor threshold here, then review what crosses it.",
    "Make clear the threshold is user-chosen, not financial guidance.",
  ],
  [
    "Finance",
    "The export question",
    "Before using a finance app, I check how to export [my records].",
    "Before using a finance app, I check how to export the transaction list as a CSV.",
    "Show the actual export and disclose format, plan, retention, and completeness limits.",
  ],
  [
    "Finance",
    "The contribution view",
    "This view separates [money in] from [costs] using the assumptions I entered.",
    "This view separates subscription revenue from media and creative costs using my entries.",
    "Do not call arithmetic a forecast, profit guarantee, or investment recommendation.",
  ],
  [
    "Finance",
    "The honest finance boundary",
    "[App] helps me organize [financial information]; it does not decide [high-stakes action].",
    "LedgerLite helps me organize recurring costs; it does not decide what I should invest or deduct.",
    "Never imply guaranteed returns, credit changes, tax outcomes, or professional advice.",
  ],
  [
    "Productivity",
    "The next visible action",
    "I turn '[vague project]' into this one next action before I close the app.",
    "I turn 'launch prep' into 'record the billing-screen demo' before I close the app.",
    "A clearer task does not guarantee completion, focus, or productivity gains.",
  ],
  [
    "Productivity",
    "The daily shortlist",
    "Instead of staring at the whole list, I open [small view] for today.",
    "Instead of staring at the whole backlog, I open the three items marked for today.",
    "Do not imply the app knows the correct priority unless the rule is explicit.",
  ],
  [
    "Productivity",
    "The restart note",
    "Before I stop [task], I leave one line for where to restart.",
    "Before I stop editing, I leave one line naming the next clip to review.",
    "Frame it as a personal method, not a guaranteed focus or memory improvement.",
  ],
  [
    "Productivity",
    "The recurring setup",
    "I reuse this [template or checklist] whenever [recurring project] comes back.",
    "I reuse this launch checklist whenever a new app version needs creative.",
    "Do not imply templates remove review or make every project identical.",
  ],
  [
    "Productivity",
    "The meeting outcome",
    "A meeting is not done for me until [decision or owner] is recorded here.",
    "A creative review is not done for me until the next test and its owner are recorded here.",
    "Describe your process, not a universal management rule or guaranteed follow-through.",
  ],
  [
    "Productivity",
    "The interruption capture",
    "When [new request] interrupts me, I put it here instead of switching tasks immediately.",
    "When a new hook idea interrupts me, I put it in the inbox instead of opening the editor.",
    "Do not claim the technique treats attention conditions or improves focus for everyone.",
  ],
  [
    "Productivity",
    "The owner filter",
    "I filter by [owner or status] before asking who is waiting on what.",
    "I filter by review owner before asking which ads are waiting on feedback.",
    "Do not imply an assignment guarantees responsibility, timing, or completion.",
  ],
  [
    "Productivity",
    "The done definition",
    "This field tells our team what 'ready' means for [work item].",
    "This field tells our team what 'ready to edit' means for a raw UGC take.",
    "A definition can clarify expectations but cannot guarantee quality or agreement.",
  ],
  [
    "Productivity",
    "The low-capacity plan",
    "On a busy week, I reduce the plan to [small realistic commitment].",
    "On a busy week, I reduce the content plan to one demo and two opening takes.",
    "Avoid promising reduced stress, better health, or increased output.",
  ],
  [
    "Productivity",
    "The honest productivity boundary",
    "[App] shows me [work information]; it cannot make me [human outcome].",
    "FocusBoard shows me the next approved task; it cannot make me concentrate or finish it.",
    "Never promise hours saved, mental-health effects, or guaranteed productivity.",
  ],
  [
    "Dating",
    "The profile detail check",
    "Before I publish my profile, I reread [specific section] for what it actually says about me.",
    "Before I publish my profile, I reread the prompt answers for specific details someone can respond to.",
    "Do not promise matches, attention, compatibility, or relationship outcomes.",
  ],
  [
    "Dating",
    "The preference control",
    "This is where I set [real preference] instead of hoping the app guesses.",
    "This is where I set my distance preference instead of assuming every suggestion is nearby.",
    "Show real controls without implying filters guarantee compatibility or safety.",
  ],
  [
    "Dating",
    "The conversation reminder",
    "I save [non-sensitive detail] here so I remember what we already talked about.",
    "I save the book recommendation here so I remember what we already talked about.",
    "Avoid surveillance-like framing and never expose another person's private information.",
  ],
  [
    "Dating",
    "The opening prompt",
    "Instead of sending '[generic opener],' I start from this detail in their profile.",
    "Instead of sending 'hey,' I ask about the trail in their weekend photo.",
    "Do not promise replies or encourage manipulative, harassing, or copied messages.",
  ],
  [
    "Dating",
    "The safety setting",
    "Before meeting anyone, I check where [safety or privacy control] lives.",
    "Before meeting anyone, I check how to share the plan and report a concern.",
    "Do not imply interface controls guarantee personal safety; point to official guidance.",
  ],
  [
    "Dating",
    "The boundary update",
    "I changed [preference or boundary] here when my situation changed.",
    "I changed the relationship-intent field when what I was looking for changed.",
    "Do not shame preferences or imply settings control other people's behavior.",
  ],
  [
    "Dating",
    "The honest profile",
    "This prompt helped me replace [vague answer] with one true example.",
    "This prompt helped me replace 'I love travel' with the train trip I keep talking about.",
    "Do not invent experiences or suggest authenticity guarantees better matches.",
  ],
  [
    "Dating",
    "The pause control",
    "This is how I pause [visibility or notifications] when I want a break.",
    "This is how I pause profile visibility without deleting my notes and settings.",
    "Confirm what is actually paused, retained, or visible; avoid privacy guarantees.",
  ],
  [
    "Dating",
    "The expectation check",
    "Before I use [feature], I check what it does not tell me about a person.",
    "Before I use a compatibility label, I remember it cannot tell me how a real conversation will feel.",
    "Do not present scores, badges, or matching logic as proof of compatibility.",
  ],
  [
    "Dating",
    "The honest dating boundary",
    "[App] can help with [supported connection job]; it cannot promise [human outcome].",
    "MeetNote can help me remember conversation details; it cannot promise a reply or relationship.",
    "Never guarantee matches, dates, replies, attraction, compatibility, or safety.",
  ],
  [
    "Education",
    "The lesson starting point",
    "When I open [topic], this is the first example I work through.",
    "When I open fractions, this is the first visual example I work through.",
    "Do not promise mastery, grades, test results, or suitability for every learner.",
  ],
  [
    "Education",
    "The mistake explanation",
    "Instead of hiding the wrong answer, [app] shows me [specific explanation].",
    "Instead of hiding the wrong answer, StudyStep shows which part of the equation changed.",
    "Do not claim explanations are always correct or replace qualified instruction.",
  ],
  [
    "Education",
    "The saved question",
    "I save this question for [teacher, tutor, or study session] instead of guessing past it.",
    "I save this grammar question for tutoring instead of guessing past it.",
    "Avoid presenting the app as a substitute for professional educational support.",
  ],
  [
    "Education",
    "The review selection",
    "I choose what to review from [visible record], not from what feels familiar.",
    "I choose what to review from the missed-question list, not just my favorite chapter.",
    "Do not imply review selection guarantees retention, mastery, or scores.",
  ],
  [
    "Education",
    "The short practice block",
    "I use this [small activity] when I have [realistic amount of time].",
    "I use this five-question vocabulary set while waiting for the bus.",
    "Only state a duration the activity truly fits; avoid learning-speed promises.",
  ],
  [
    "Education",
    "The progress record",
    "This shows what I completed in [topic], not what I have mastered.",
    "This shows which lessons I completed, not whether I can use every concept alone.",
    "Keep activity, completion, proficiency, and achievement clearly separated.",
  ],
  [
    "Education",
    "The parent or teacher view",
    "This is the information [parent or teacher] can see, and this is what stays private.",
    "This is the assignment status a teacher can see, and these are the private study notes.",
    "Verify permissions and protect child/student data; do not make compliance claims casually.",
  ],
  [
    "Education",
    "The learning preference",
    "I switch from [format] to [format] when I need another way to look at the idea.",
    "I switch from the definition to the diagram when I need another way to look at the process.",
    "Describe available formats, not a diagnosis or guaranteed match to a learning style.",
  ],
  [
    "Education",
    "The source check",
    "Before I use [answer or summary], I open the source or explanation behind it.",
    "Before I use the history summary, I open the cited passage behind it.",
    "Do not imply a citation guarantees accuracy; encourage appropriate verification.",
  ],
  [
    "Education",
    "The honest education boundary",
    "[App] helps me practice [specific skill]; it cannot promise [grade, mastery, or credential].",
    "WordPath helps me practice vocabulary; it cannot promise a test score or fluency.",
    "Never guarantee grades, admissions, credentials, mastery, or developmental outcomes.",
  ],
  [
    "Utility",
    "The one-job shortcut",
    "When I need to [specific utility job], I open [app] and tap here.",
    "When I need to rename a batch of screenshots, I open FileTidy and choose the date rule.",
    "Show the complete job and do not claim support for every file, device, or condition.",
  ],
  [
    "Utility",
    "The compatibility check",
    "Before I rely on [feature], I check whether it supports [real format or device].",
    "Before I rely on the export, I check whether it supports the CSV format my client needs.",
    "Do not imply universal compatibility; name tested formats and current limits.",
  ],
  [
    "Utility",
    "The batch preview",
    "I preview these changes before I apply them to [files or items].",
    "I preview the new filenames before I apply them to forty image files.",
    "A preview cannot guarantee there will be no data loss or unexpected result.",
  ],
  [
    "Utility",
    "The undo path",
    "Before I use [batch action], I check how to undo or restore it.",
    "Before I archive a project folder, I check how long restoration stays available.",
    "Show real recovery limits and never promise recoverability you cannot guarantee.",
  ],
  [
    "Utility",
    "The local-versus-uploaded check",
    "This is what stays on my device, and this is what [app] sends elsewhere.",
    "The preview stays in my browser; the shared link uploads the selected file.",
    "Base privacy statements on documented behavior and avoid absolute security claims.",
  ],
  [
    "Utility",
    "The settings reset",
    "I changed too many options, so I use this to return to [known state].",
    "I changed too many export options, so I reset them to the app defaults.",
    "Do not imply resetting settings restores deleted data or previous content.",
  ],
  [
    "Utility",
    "The before-you-run checklist",
    "Before I run [utility action], I check these [number] details.",
    "Before I compress a video, I check its dimensions, duration, and target upload limit.",
    "A checklist cannot guarantee output quality, compatibility, or platform acceptance.",
  ],
  [
    "Utility",
    "The output inspection",
    "I do not stop at 'complete.' I open the output and check [specific property].",
    "I do not stop at 'exported.' I open the file and check that the captions are readable.",
    "Do not imply a single check proves the entire output is correct or safe.",
  ],
  [
    "Utility",
    "The plan-limit check",
    "This feature works on [plan or condition], so I check that before starting.",
    "Bulk rename works on the desktop plan, so I check that before preparing the files.",
    "Keep plan, platform, and availability details current; do not hide paid requirements.",
  ],
  [
    "Utility",
    "The honest utility boundary",
    "[App] helps with [supported technical job]; it cannot guarantee [broader technical outcome].",
    "CompressCheck estimates file size; it cannot guarantee a platform will accept the upload.",
    "Never guarantee compatibility, security, recovery, acceptance, or lossless results.",
  ],
] as const;

export const appCategoryHookPacks: readonly CollectionResourceItem[] =
  appCategoryHookPackEntries.map(
    ([category, title, copyText, example, guardrail], index) => ({
      body: `Example: ${example} Category reminder: ${guardrail}`,
      category,
      copyText,
      eyebrow: `${category} pack · ${(index % 10) + 1}`,
      id: `app-category-hook-${String(index + 1).padStart(2, "0")}`,
      tags: [category, "Fill-in structure"],
      title,
    }),
  );
