import type { CollectionResourceItem } from "@/lib/clipstitchr/tools/resources/CollectionResourceItem";

const appDemoVideoHookEntries = [
  [
    "Pain recognition",
    "The repeat task",
    "Still copying [the same detail] every time you [do the task]?",
    "Show the repeated copy-and-paste, then cut to the app filling the same field.",
    "Only imply automation if the app really performs that step.",
  ],
  [
    "Pain recognition",
    "The tab pile",
    "If [task] needs this many tabs, I need to show you something.",
    "Fan across the open tabs, then land on the app's single working view.",
    "Do not claim one screen replaces tools that users still need.",
  ],
  [
    "Pain recognition",
    "The annoying middle",
    "The most annoying part of [workflow] is not the part you think.",
    "Start on the frustrating middle step and reveal the app action that addresses it.",
    "Name a friction you can demonstrate instead of inventing a universal complaint.",
  ],
  [
    "Pain recognition",
    "The blank start",
    "Your [workflow] should not start with another blank page.",
    "Show the empty state, then tap into a useful starting template or saved setup.",
    "Avoid implying the app completes work the user must still review.",
  ],
  [
    "Pain recognition",
    "The recurring scramble",
    "Every [day or week], I used to scramble for [thing I needed].",
    "Show the messy search, then open the organized place where the item now lives.",
    "Use 'used to' only when it reflects a real personal workflow.",
  ],
  [
    "Pain recognition",
    "The familiar screen",
    "You know that screen you avoid because [unpleasant task] is waiting?",
    "Hold on the avoided screen, then show the first manageable step inside the app.",
    "Do not suggest the app removes consequences or required decisions.",
  ],
  [
    "Pain recognition",
    "The tiny admin job",
    "This tiny admin task kept interrupting the work I actually wanted to do.",
    "Show the interruption, then demonstrate the app's shorter path through it.",
    "Keep the comparison about your own process, not a guaranteed time saving.",
  ],
  [
    "Pain recognition",
    "The buried detail",
    "If [important detail] keeps getting buried, try organizing it like this.",
    "Search unsuccessfully in the old location, then reveal the app's labeled view.",
    "Only call the detail organized if the demo clearly shows where it goes.",
  ],
  [
    "Pain recognition",
    "The rebuild loop",
    "Why are we rebuilding [repeatable thing] from scratch every time?",
    "Show two nearly identical old versions, then start from a reusable app setup.",
    "Do not imply reuse is automatic if the user must duplicate or configure it.",
  ],
  [
    "Pain recognition",
    "The messy handoff",
    "The messy part of [workflow] starts right when one person hands it to another.",
    "Show an unclear handoff message, then the app view containing the needed context.",
    "Avoid promising error-free teamwork; show the specific information being shared.",
  ],
  [
    "Desired outcome",
    "The calm overview",
    "Here is how I keep [important work] visible without checking five places.",
    "Open on the app overview and point to the few details that matter right now.",
    "Do not say everything is included unless the screen truly covers the full workflow.",
  ],
  [
    "Desired outcome",
    "The one-screen answer",
    "One screen tells me what needs attention today.",
    "Reveal the prioritized view, then tap the first item to show the next action.",
    "Make clear that the priority rule comes from real app logic or user settings.",
  ],
  [
    "Desired outcome",
    "The clean start",
    "This is the cleanest way I have found to start [task].",
    "Begin at the app's new-item flow and show the first useful choice.",
    "Frame 'cleanest' as personal preference rather than an objective ranking.",
  ],
  [
    "Desired outcome",
    "The ready next step",
    "I wanted [workflow] to tell me the next step, not give me more homework.",
    "Show the app presenting one next action after a small amount of setup.",
    "Do not hide setup the viewer would need to complete first.",
  ],
  [
    "Desired outcome",
    "The useful routine",
    "My [morning, work, or evening] routine finally has one place to begin.",
    "Show the app icon being opened at the start of the real routine, then the home view.",
    "Avoid claiming the routine works for everyone or produces a guaranteed outcome.",
  ],
  [
    "Desired outcome",
    "The visible progress",
    "I can actually see what moved forward this week.",
    "Show the progress history or completed-state view with real example data.",
    "Do not equate app activity with health, financial, or life results.",
  ],
  [
    "Desired outcome",
    "The shared context",
    "This is what I send when someone asks, 'Where are we on [project]?'.",
    "Copy or share the app summary, then show the recipient-facing result.",
    "Only describe sharing options that exist in the demonstrated plan or version.",
  ],
  [
    "Desired outcome",
    "The prepared moment",
    "I open this before [recurring moment] so I know what I am walking into.",
    "Show the app's relevant summary just before the meeting, workout, lesson, or task.",
    "Keep the outcome about preparation, not guaranteed performance.",
  ],
  [
    "Desired outcome",
    "The clear finish",
    "The best part is knowing when [task] is actually done.",
    "Complete the final app step and hold on the clear finished state.",
    "Do not call a task complete if outside steps still remain.",
  ],
  [
    "Desired outcome",
    "The reusable win",
    "I set this up once, then reuse it whenever [situation] comes back.",
    "Show the saved setup and the exact action used to reuse it.",
    "Do not imply a fully automatic repeat if user input is still required.",
  ],
  [
    "Hidden friction",
    "The decision tax",
    "The hard part of [task] was deciding what to do first.",
    "Show several competing options, then the app's ordered or filtered view.",
    "Do not present app ordering as professional advice unless that is supported and disclosed.",
  ],
  [
    "Hidden friction",
    "The missing context",
    "I was not losing the file. I was losing the reason we made it.",
    "Open an item with its notes, history, or linked context visible beside it.",
    "Only show history or context the app actually retains.",
  ],
  [
    "Hidden friction",
    "The setup trap",
    "A tool is not helpful if setting it up becomes the new project.",
    "Record the shortest honest setup path and stop when the first useful result appears.",
    "Do not skip required onboarding or suggest setup is instant when it is not.",
  ],
  [
    "Hidden friction",
    "The forgotten follow-up",
    "The task was easy. Remembering to come back to it was not.",
    "Show the follow-up date or reminder being attached to the item.",
    "Do not promise a notification if permissions or plan limits can prevent it.",
  ],
  [
    "Hidden friction",
    "The naming problem",
    "We did not need another folder. We needed names that made sense later.",
    "Rename a real item using the app's visible structure, then search for it.",
    "Avoid implying the app can understand or rename files automatically unless it can.",
  ],
  [
    "Hidden friction",
    "The switching cost",
    "I kept breaking focus just to update [small status or detail].",
    "Show the old context switch, then update the detail in the app's current view.",
    "Describe the demonstrated path rather than promising better focus.",
  ],
  [
    "Hidden friction",
    "The invisible backlog",
    "The list looked manageable because half the work was hiding somewhere else.",
    "Reveal the missing work, then show how the app groups related items in one view.",
    "Do not say the view is complete unless all relevant sources are actually connected.",
  ],
  [
    "Hidden friction",
    "The unclear owner",
    "Most of our delays started with one question: who owns this?",
    "Show the owner field and the handoff action on a realistic example item.",
    "Do not claim assigning an owner guarantees completion or timing.",
  ],
  [
    "Hidden friction",
    "The stale answer",
    "The problem was not finding an answer. It was knowing whether it was still current.",
    "Show the updated timestamp, version, or status beside the app content.",
    "Only rely on freshness signals the app genuinely records.",
  ],
  [
    "Hidden friction",
    "The almost-done pile",
    "I had too many things that were technically started and practically stuck.",
    "Show a stuck item, add the missing next action, and move it into a clear state.",
    "Avoid implying the app resolves blockers it only helps document.",
  ],
  [
    "Demo reveal",
    "The three-tap tour",
    "Give me three taps to show you how [app] handles [specific task].",
    "Use three visible taps with no jump cuts and end on the completed app state.",
    "Count honestly; do not hide setup or required typing outside the three taps.",
  ],
  [
    "Demo reveal",
    "From input to result",
    "Watch what happens after I add [one real input].",
    "Enter a safe example, trigger the app action, and hold on the resulting screen.",
    "Do not imply every input produces the same quality or result.",
  ],
  [
    "Demo reveal",
    "The feature people miss",
    "This small button is the reason I keep [app] on my home screen.",
    "Circle the overlooked control, tap it, and show the immediate product response.",
    "Make the personal preference clear and avoid popularity claims.",
  ],
  [
    "Demo reveal",
    "The side-by-side setup",
    "Here is the same [task] before and after I organize it in [app].",
    "Place the two states side by side and keep the changed details readable.",
    "Only attribute differences visibly created by the demonstrated setup.",
  ],
  [
    "Demo reveal",
    "The real use case",
    "Let me show you [app] in the exact moment I need it.",
    "Start in the real-world situation, then screen-record the matching app action.",
    "Use a genuine or clearly staged scenario without pretending it is a customer result.",
  ],
  [
    "Demo reveal",
    "The empty-to-useful path",
    "This blank screen becomes useful as soon as I add these two details.",
    "Start from the empty state, add two safe details, and reveal the populated view.",
    "Do not hide any third required detail or processing step.",
  ],
  [
    "Demo reveal",
    "The hold-to-read demo",
    "Pause here—this is the part of [app] that makes [task] easier to understand.",
    "Freeze long enough for viewers to read the key labels before continuing.",
    "Describe clarity as your experience, not a guaranteed user outcome.",
  ],
  [
    "Demo reveal",
    "The saved setup",
    "I made this once. Here is how I bring it back for the next [project or event].",
    "Open the saved item, duplicate or reuse it, then point out what remains editable.",
    "Show the actual reuse action and avoid implying automatic customization.",
  ],
  [
    "Demo reveal",
    "The handoff moment",
    "This is the exact screen I share before someone else takes over.",
    "Show the summary, its key context, and the real share or export control.",
    "Do not expose private information or promise access the recipient may not have.",
  ],
  [
    "Demo reveal",
    "The undo confidence",
    "I am more willing to try this because I can see how to undo it.",
    "Make a reversible change, then demonstrate the undo, restore, or preview path.",
    "Only promise reversibility for actions the app can actually restore.",
  ],
  [
    "Objection answer",
    "The too-busy objection",
    "I thought I was too busy to set up another app, so I tested the shortest useful path.",
    "Show the honest onboarding steps through the first useful result.",
    "Do not state a setup time unless measured and typical conditions are clear.",
  ],
  [
    "Objection answer",
    "The already-have-a-tool objection",
    "I already had a tool for [category]. This is the job I still needed help with.",
    "Name the narrow gap, then demonstrate only the app flow that addresses it.",
    "Avoid claiming competitors cannot perform the same job.",
  ],
  [
    "Objection answer",
    "The complicated objection",
    "If [app category] usually feels complicated, start with this one screen.",
    "Hide advanced options and walk through the simplest supported starting view.",
    "Do not imply the whole category is simple or risk-free.",
  ],
  [
    "Objection answer",
    "The habit objection",
    "I did not need a perfect new habit. I needed a place to restart after missing a day.",
    "Show the return flow after a realistic gap, without hiding an empty streak.",
    "Avoid health, productivity, or behavior-change guarantees.",
  ],
  [
    "Objection answer",
    "The privacy objection",
    "Before I put [sensitive detail] in an app, I check these settings.",
    "Open the real privacy or sharing controls and explain only what they visibly do.",
    "Do not make security or compliance claims beyond documented product behavior.",
  ],
  [
    "Objection answer",
    "The flexibility objection",
    "I was worried this workflow would lock me into one way of working.",
    "Change a category, order, template, or view to demonstrate the available flexibility.",
    "Do not imply full customization if only specific fields can change.",
  ],
  [
    "Objection answer",
    "The team-size objection",
    "This is how I use [app] without turning it into a giant team process.",
    "Show a single-person or small-team setup with only essential fields visible.",
    "Do not imply plan features are available to every account size.",
  ],
  [
    "Objection answer",
    "The learning-curve objection",
    "The first thing I learned in [app] was not a feature. It was where to begin.",
    "Point to the starting action and follow it through one complete task.",
    "Avoid promising every viewer will find the app intuitive.",
  ],
  [
    "Objection answer",
    "The value objection",
    "The question was not whether [app] had more features. It was whether I would use this one.",
    "Demonstrate one repeated, concrete job instead of scrolling through a feature list.",
    "Do not imply financial value or ROI without the viewer's own numbers.",
  ],
  [
    "Objection answer",
    "The migration objection",
    "I did not want to move everything, so I started with just [small slice].",
    "Show one limited import or manual setup and the useful result it creates.",
    "Do not imply migration is complete, automatic, or lossless unless it is.",
  ],
  [
    "Mistake correction",
    "The feature-first mistake",
    "I was showing every feature before explaining the one problem this app solves.",
    "Start with the problem moment, then reveal only the feature that addresses it.",
    "Keep the problem specific and avoid suggesting one feature solves every case.",
  ],
  [
    "Mistake correction",
    "The cluttered setup",
    "I made [workflow] harder by tracking details I never used.",
    "Remove one unnecessary field and show the simpler working view.",
    "Present this as a personal setup choice, not universal best practice.",
  ],
  [
    "Mistake correction",
    "The wrong starting point",
    "I kept starting [task] at the end and wondering why it felt messy.",
    "Show the old starting screen, then begin from the app's intended first step.",
    "Do not shame alternative workflows or imply they cannot work.",
  ],
  [
    "Mistake correction",
    "The all-at-once mistake",
    "I stopped trying to set up everything and started with one repeatable part.",
    "Choose one narrow app section, configure it, and show how it is reused.",
    "Avoid claiming gradual setup guarantees adoption or consistency.",
  ],
  [
    "Mistake correction",
    "The hidden-payoff mistake",
    "My demo buried the useful part, so here it is first.",
    "Open on the payoff screen, then quickly show the steps that produced it.",
    "Do not present a prepared result as an instant default outcome.",
  ],
  [
    "Mistake correction",
    "The vague-label mistake",
    "This made more sense when I stopped naming things 'final' and 'new final.'",
    "Rename examples with the app's date, status, owner, or version fields visible.",
    "Do not imply the app enforces naming rules unless it does.",
  ],
  [
    "Mistake correction",
    "The no-context mistake",
    "A task without the reason behind it kept coming back with questions.",
    "Add the missing note, source, or acceptance detail and show the complete item.",
    "Avoid promising context eliminates every question or revision.",
  ],
  [
    "Mistake correction",
    "The notification pile",
    "More reminders did not help until I changed what each reminder meant.",
    "Edit a vague reminder into a specific action with a realistic date.",
    "Do not claim notifications improve behavior for every user.",
  ],
  [
    "Mistake correction",
    "The untested template",
    "I stopped calling this a template until I had reused it once.",
    "Duplicate the saved setup, update it for a second case, and note what needed changing.",
    "Do not present a one-off example as universally reusable.",
  ],
  [
    "Mistake correction",
    "The polished-before-clear mistake",
    "I was making the screen prettier before making the next action obvious.",
    "Compare the decorative view with a view that clearly highlights the next step.",
    "Frame the preference as a usability choice, not an objective design verdict.",
  ],
  [
    "Before and after",
    "The scattered-to-visible shift",
    "Before: [work] lived everywhere. After: I can see the pieces in one view.",
    "Use a labeled split screen showing the old locations and the app overview.",
    "Do not imply source systems disappear if the app only links or summarizes them.",
  ],
  [
    "Before and after",
    "The vague-to-specific shift",
    "This went from 'work on [project]' to a next step I could actually take.",
    "Show the vague item, then the edited action, owner, and date fields.",
    "Do not equate clearer wording with guaranteed completion.",
  ],
  [
    "Before and after",
    "The empty-to-prepared shift",
    "Here is the screen before [event], and here it is after two minutes of prep.",
    "Record the exact prep actions and hold on the resulting summary.",
    "Only mention a duration you measured for this real example.",
  ],
  [
    "Before and after",
    "The raw-to-organized shift",
    "Same information, much easier to use once it is organized like this.",
    "Show the raw list followed by the app's groups, labels, or filters.",
    "Avoid saying the organization is objectively better for every workflow.",
  ],
  [
    "Before and after",
    "The forgotten-to-returned shift",
    "This used to disappear after day one. Now it has a clear place to come back to.",
    "Show the saved item, its return cue, and where the next update belongs.",
    "Do not promise reminders or habits work consistently for everyone.",
  ],
  [
    "Before and after",
    "The private-to-shareable shift",
    "I turned my messy notes into a summary someone else could follow.",
    "Show a private draft, then a cleaned share view with sensitive details removed.",
    "Do not expose real private data or imply automatic redaction.",
  ],
  [
    "Before and after",
    "The reactive-to-planned shift",
    "Instead of deciding at the last minute, I can see the next [time period] here.",
    "Move from an empty schedule to a realistic app plan with a few dated items.",
    "Do not claim planning guarantees execution or results.",
  ],
  [
    "Before and after",
    "The one-off-to-repeatable shift",
    "The first version was a one-off. This version is ready for the next [case].",
    "Show what was turned into reusable fields or a saved template.",
    "Avoid implying every part can be reused unchanged.",
  ],
  [
    "Before and after",
    "The unknown-to-explained shift",
    "I could see the number before. Now I can see what changed it.",
    "Open the detail, history, or breakdown view behind a top-level number.",
    "Do not imply causation when the app only shows associated events.",
  ],
  [
    "Before and after",
    "The open-loop-to-closed-loop shift",
    "This started as a question and ended as a documented decision.",
    "Show the original question, the decision field, and the supporting note.",
    "Do not suggest documentation makes the decision correct or final forever.",
  ],
  [
    "Founder perspective",
    "The build reason",
    "I built [app] because I kept running into this exact moment.",
    "Recreate the real moment, then show the narrow product flow made for it.",
    "Keep the origin story truthful and avoid implying every user shares it.",
  ],
  [
    "Founder perspective",
    "The feature I removed",
    "One of the best decisions was removing a step users did not need.",
    "Show the current shorter flow and explain the removed step without fake old footage.",
    "Do not claim users prefer the change without evidence.",
  ],
  [
    "Founder perspective",
    "The customer wording",
    "A user described [problem] in one sentence, and it changed this screen.",
    "Show the anonymized wording, then point to the related product choice.",
    "Use customer language only with permission or anonymize it responsibly.",
  ],
  [
    "Founder perspective",
    "The narrow promise",
    "[App] is not trying to do everything. It is built for this one job.",
    "Demonstrate the single core job from start to finish.",
    "Make sure the narrow job accurately reflects the shipped product.",
  ],
  [
    "Founder perspective",
    "The awkward first version",
    "The first version made this harder. Here is what changed.",
    "Use a sketch or clearly labeled old screenshot, then the current working flow.",
    "Do not fabricate an old design or customer reaction.",
  ],
  [
    "Founder perspective",
    "The small detail",
    "This tiny product detail came from watching people get stuck here.",
    "Zoom into the detail and demonstrate the moment it helps clarify.",
    "Avoid broad usability claims without actual research evidence.",
  ],
  [
    "Founder perspective",
    "The tradeoff",
    "We chose [simple behavior] over [more complex option] for a reason.",
    "Show the simpler flow and explain the real product tradeoff in one sentence.",
    "Acknowledge who might prefer the alternative instead of declaring a universal winner.",
  ],
  [
    "Founder perspective",
    "The not-for-everyone line",
    "[App] is probably not for you if you need [unsupported use case].",
    "Show the supported workflow while naming the honest boundary on screen.",
    "Confirm the limitation is accurate and avoid insulting people outside the fit.",
  ],
  [
    "Founder perspective",
    "The release moment",
    "We just changed how [specific action] works. Here is the difference.",
    "Demonstrate the current release with a before label only when accurate footage exists.",
    "Do not imply every user has the update if rollout is limited.",
  ],
  [
    "Founder perspective",
    "The real constraint",
    "The constraint behind this feature was not code. It was [user reality].",
    "Show the real-world constraint, then the product behavior designed around it.",
    "Do not present an assumption as user research unless you have that evidence.",
  ],
  [
    "Workflow shortcut",
    "The saved starting point",
    "Next time you [repeat task], start from this saved setup instead.",
    "Open the saved setup and show exactly what should be changed for the new case.",
    "Avoid implying the setup fits every future case without review.",
  ],
  [
    "Workflow shortcut",
    "The useful duplicate",
    "Duplicate this, change these two fields, and the next version is ready to review.",
    "Duplicate the item, edit two visible fields, and stop at the review state.",
    "Do not call it finished if review, approval, or production still remains.",
  ],
  [
    "Workflow shortcut",
    "The filter first",
    "Before scrolling, filter [list] by the one thing you need right now.",
    "Apply a real filter and show the smaller result set.",
    "Do not imply the filter finds the right answer automatically.",
  ],
  [
    "Workflow shortcut",
    "The one-field update",
    "You do not need to rebuild the plan. Update this field and keep moving.",
    "Edit the relevant field and show which connected view changes.",
    "Only suggest connected updates the product actually performs.",
  ],
  [
    "Workflow shortcut",
    "The shortcut with context",
    "This shortcut only works because the important context is already attached.",
    "Show the attached note or data, then trigger the shortcut it enables.",
    "Do not hide the preparation that makes the shortcut possible.",
  ],
  [
    "Workflow shortcut",
    "The batch decision",
    "I make this decision once, then apply it to the items that truly match.",
    "Select a few safe example items and show the supported batch action.",
    "Avoid suggesting every item belongs in the batch or that mistakes cannot happen.",
  ],
  [
    "Workflow shortcut",
    "The pinned view",
    "Pin the view you actually use instead of rebuilding the same search.",
    "Create or open a saved view and show the criteria that define it.",
    "Only call it pinned or saved if the product persists it.",
  ],
  [
    "Workflow shortcut",
    "The handoff template",
    "When this leaves my hands, these are the details I never want missing.",
    "Open a handoff template and point to each required piece of context.",
    "Do not imply a template replaces review, consent, or approval.",
  ],
  [
    "Workflow shortcut",
    "The status reset",
    "If [item] is stuck, reset it to the last status everyone understands.",
    "Open the history, choose the accurate status, and add a short explanation.",
    "Do not recommend changing records in ways that hide real history.",
  ],
  [
    "Workflow shortcut",
    "The review queue",
    "I stop hunting for feedback by putting every review in this one queue.",
    "Show several review-ready items and the app view that gathers them.",
    "Avoid claiming all feedback channels are included unless they are connected.",
  ],
  [
    "Proof invitation",
    "The watch-me test",
    "Do not take my word for it—watch me use [feature] on [realistic example].",
    "Run the example in one continuous capture and show the result long enough to inspect.",
    "Use representative input and do not hide failed attempts or required conditions.",
  ],
  [
    "Proof invitation",
    "The checkable claim",
    "Here is the exact screen behind my claim about [specific product behavior].",
    "Put the claim on screen beside the product evidence that supports it.",
    "Limit the claim to what the visible evidence actually demonstrates.",
  ],
  [
    "Proof invitation",
    "The edge-case demo",
    "I wanted to know what happens when [real edge case], so I tried it.",
    "Show the edge-case input and the full product response without cutting away.",
    "Do not generalize one test into a reliability guarantee.",
  ],
  [
    "Proof invitation",
    "The settings reveal",
    "Before you trust this feature, look at the controls it gives you.",
    "Open the relevant settings and explain the practical choice each control changes.",
    "Do not imply controls eliminate risk or guarantee privacy.",
  ],
  [
    "Proof invitation",
    "The real output",
    "This is the actual result [app] produced from that input.",
    "Keep the original input visible, then reveal the unedited app output.",
    "Clearly label any manual edits or prepared example data.",
  ],
  [
    "Proof invitation",
    "The two-route comparison",
    "Same task, two routes. Here is what changes when I use [feature].",
    "Record both paths under comparable conditions and label each step.",
    "Avoid declaring one route faster unless timing is measured fairly.",
  ],
  [
    "Proof invitation",
    "The history check",
    "I can show exactly when this changed and who changed it.",
    "Open the real audit, activity, or version history on safe example data.",
    "Only make traceability claims covered by the demonstrated history.",
  ],
  [
    "Proof invitation",
    "The export check",
    "Before I commit to a tool, I check what I can take back out.",
    "Show the real export controls and open a safe sample of the resulting file.",
    "Name plan, format, or data limits that affect the export.",
  ],
  [
    "Proof invitation",
    "The fresh-account demo",
    "This is what [app] looks like before I have customized anything.",
    "Use a genuine fresh account and show the default experience without seeded shortcuts.",
    "Do not present a prepared workspace as a new-user default.",
  ],
  [
    "Proof invitation",
    "The boundary demo",
    "Here is what [app] handles—and the part it intentionally leaves to you.",
    "Demonstrate the supported action, then clearly label the human decision or outside step.",
    "Keep the limitation visible instead of implying an end-to-end solution.",
  ],
] as const;

export const appDemoVideoHooks: readonly CollectionResourceItem[] =
  appDemoVideoHookEntries.map(
    ([category, title, copyText, visual, guardrail], index) => ({
      body: `Opening visual: ${visual} Claim check: ${guardrail}`,
      category,
      copyText,
      eyebrow: `${category} · ${index + 1}`,
      id: `app-demo-hook-${String(index + 1).padStart(3, "0")}`,
      tags: [category, "App demo"],
      title,
    }),
  );
