import type { PlanKey } from "./types/PlanKey";
import type { PlanPolicy } from "./types/PlanPolicy";

export const planPolicies = {
  starter: {
    activeGenerationLimit: 1,
    aiVideoLimit: 3,
    dailyDraftProductLimit: 0,
    monthlyCreationCredits: 2_000,
    monthlyPriceUsd: 39,
    name: "Starter",
    planKey: "starter",
    productLimit: 1,
    queueLabel: "Standard",
    queueWeight: 1,
    standalonePhotoCreditCost: 25,
    stitchCreditCost: 10,
    swiprCreditCost: 20,
  },
  pro: {
    activeGenerationLimit: 2,
    aiVideoLimit: 10,
    dailyDraftProductLimit: 1,
    monthlyCreationCredits: 8_000,
    monthlyPriceUsd: 99,
    name: "Pro",
    planKey: "pro",
    productLimit: 3,
    queueLabel: "Priority processing",
    queueWeight: 3,
    standalonePhotoCreditCost: 25,
    stitchCreditCost: 10,
    swiprCreditCost: 20,
  },
  agency: {
    activeGenerationLimit: 4,
    aiVideoLimit: 50,
    dailyDraftProductLimit: 10,
    monthlyCreationCredits: 20_000,
    monthlyPriceUsd: 399,
    name: "Agency",
    planKey: "agency",
    productLimit: 10,
    queueLabel: "Highest priority",
    queueWeight: 5,
    standalonePhotoCreditCost: 25,
    stitchCreditCost: 0,
    swiprCreditCost: 20,
  },
} satisfies Record<PlanKey, PlanPolicy>;
