import type { NotionKitTemplate } from "@/lib/clipstitchr/tools/notionKit/NotionKitTemplate";

export const notionKitTemplates: readonly NotionKitTemplate[] = [
  {
    columns: [
      "Idea ID",
      "Working title",
      "Audience",
      "Problem",
      "Angle",
      "Hook",
      "Required assets",
      "Status",
      "Owner",
      "Notes",
    ],
    description:
      "Capture ideas as testable concepts instead of a pile of disconnected captions.",
    fileName: "clipstitchr-idea-bank.csv",
    name: "Idea Bank",
    propertyNotes: [
      "Keep Idea ID unique so other tables can reference it.",
      "Use Status values such as New, Briefed, Capturing, Ready, Tested, or Archived.",
    ],
    rows: [
      [
        "IDEA-001",
        "Monday reset",
        "Busy solo founders",
        "Rebuilding a weekly task list",
        "Problem-first",
        "Still rebuilding Monday from scratch?",
        "Spoken hook; dashboard demo; CTA",
        "New",
        "Alex",
        "Replace the example with a claim the product can show.",
      ],
      [
        "IDEA-002",
        "One-tap payoff",
        "New trial users",
        "The useful moment feels hidden",
        "Demo-first",
        "Watch what happens after one tap.",
        "Clean demo; silent reaction; CTA",
        "Briefed",
        "Sam",
        "Hold the visible result for readability.",
      ],
    ],
  },
  {
    columns: [
      "Shoot ID",
      "Idea ID",
      "Capture",
      "Asset role",
      "Creator",
      "Location",
      "Orientation",
      "Takes requested",
      "Due date",
      "Status",
      "Handoff notes",
    ],
    description:
      "Turn concepts into separate reusable source files with owners and handoff rules.",
    fileName: "clipstitchr-shoot-planner.csv",
    name: "Shoot Planner",
    propertyNotes: [
      "Use one row per requested source file, not one row per finished ad.",
      "Keep UGC and product-demo captures in separate rows.",
    ],
    rows: [
      [
        "SHOOT-001",
        "IDEA-001",
        "Direct-to-camera opening",
        "Spoken hook",
        "Alex",
        "Desk",
        "9:16",
        "2",
        "2026-08-01",
        "Requested",
        "Two seconds of clean handle before and after. No music or captions.",
      ],
      [
        "SHOOT-002",
        "IDEA-001",
        "Complete one dashboard action",
        "Product demo",
        "Internal",
        "Screen recording",
        "9:16",
        "2",
        "2026-08-01",
        "Ready",
        "Start from the before-state and hold the result.",
      ],
    ],
  },
  {
    columns: [
      "Asset ID",
      "Shoot ID",
      "File name",
      "Asset role",
      "Creator",
      "Concept",
      "Duration seconds",
      "Rights status",
      "Technical status",
      "Creative status",
      "Storage link",
      "Notes",
    ],
    description:
      "Know which clips are ready, need work, are missing, or still have unclear usage approval.",
    fileName: "clipstitchr-asset-inventory.csv",
    name: "Asset Inventory",
    propertyNotes: [
      "Rights status records your documentation state; it is not legal verification.",
      "Storage link can point to your existing storage until the asset enters ClipStitchr.",
    ],
    rows: [
      [
        "ASSET-001",
        "SHOOT-001",
        "acme-reset-hook-alex-v01.mp4",
        "Spoken hook",
        "Alex",
        "Monday reset",
        "5",
        "Documented",
        "Ready",
        "Ready",
        "",
        "Clean handles; no baked-in text.",
      ],
      [
        "ASSET-002",
        "SHOOT-002",
        "acme-reset-demo-v01.mp4",
        "Product demo",
        "Internal",
        "Monday reset",
        "7",
        "Owned",
        "Needs crop review",
        "Ready",
        "",
        "Private sample data already removed.",
      ],
    ],
  },
  {
    columns: [
      "Post ID",
      "Idea ID",
      "Channel",
      "Publish date",
      "Publish time",
      "Audience",
      "Asset IDs",
      "CTA role",
      "Owner",
      "Status",
      "Destination",
      "Notes",
    ],
    description:
      "Plan where a ready concept goes without pretending the CSV schedules or publishes it.",
    fileName: "clipstitchr-publishing-calendar.csv",
    name: "Publishing Calendar",
    propertyNotes: [
      "Use one row per planned placement.",
      "Status can be Planned, Ready, Scheduled elsewhere, Published, Paused, or Archived.",
    ],
    rows: [
      [
        "POST-001",
        "IDEA-001",
        "TikTok",
        "2026-08-04",
        "12:00",
        "Busy solo founders",
        "ASSET-001; ASSET-002",
        "Try the workflow",
        "Alex",
        "Planned",
        "App store listing",
        "Confirm destination matches the CTA.",
      ],
      [
        "POST-002",
        "IDEA-002",
        "Instagram Reels",
        "2026-08-06",
        "17:30",
        "New trial users",
        "ASSET-003; ASSET-004",
        "See the product",
        "Sam",
        "Ready",
        "Landing page",
        "Keep the same evidence window as the control.",
      ],
    ],
  },
  {
    columns: [
      "Result ID",
      "Post ID",
      "Review date",
      "Spend",
      "Impressions",
      "Clicks",
      "Installs",
      "Conversions",
      "Primary decision metric",
      "Observation",
      "Inference",
      "Decision",
      "Next hypothesis",
    ],
    description:
      "Keep evidence, interpretation, and the next production decision in separate fields.",
    fileName: "clipstitchr-results-tracker.csv",
    name: "Results Tracker",
    propertyNotes: [
      "Use the same metric definitions and windows for comparable cells.",
      "Leave unknown values blank instead of entering invented zeros.",
    ],
    rows: [
      [
        "RESULT-001",
        "POST-001",
        "2026-08-11",
        "",
        "",
        "",
        "",
        "",
        "Install rate",
        "The opening retained attention longer than the control.",
        "The audience callout may have improved relevance.",
        "Keep as provisional control",
        "Test the same hook with one new opening visual.",
      ],
      [
        "RESULT-002",
        "POST-002",
        "2026-08-13",
        "",
        "",
        "",
        "",
        "",
        "Install rate",
        "Delivery was too small for comparison.",
        "No reliable creative conclusion yet.",
        "Inconclusive",
        "Run the same cell until the entered evidence floor is met.",
      ],
    ],
  },
];
