export type UsageErrorCode =
  | "SUBSCRIPTION_REQUIRED"
  | "SUBSCRIPTION_INACTIVE"
  | "BILLING_REVIEW_REQUIRED"
  | "INSUFFICIENT_CREATION_CREDITS"
  | "AI_VIDEO_ALLOWANCE_REACHED"
  | "GENERATION_CONCURRENCY_REACHED"
  | "USAGE_RESERVATION_EXPIRED"
  | "USAGE_RESERVATION_CONFLICT"
  | "USAGE_RECONCILIATION_REQUIRED";
