import type { InteractiveCommandDefinition } from "./InteractiveCommandDefinition.js";

export const interactiveCommandDefinitions: InteractiveCommandDefinition[] = [
  { value: "/demo", description: "Open the demo menu", completion: "run" },
  { value: "/demo manual", description: "Record a demo yourself", completion: "run" },
  { value: "/demo manual --guide", description: "Record with a saved guide", completion: "continue" },
  { value: "/demo manual --no-guide", description: "Record without a guide", completion: "run" },
  { value: "/demo manual --no-upload", description: "Keep the recording local", completion: "run" },
  { value: "/demo agent", description: "Let AI record a guarded demo", completion: "run", searchTerms: ["automatic demo", "ai demo"] },
  { value: "/demo agent --guide", description: "Run AI with a saved guide", completion: "continue" },
  { value: "/demo agent --no-upload", description: "Review without uploading", completion: "run" },
  { value: "/demo agent --driver", description: "Choose the AI driver", completion: "continue" },
  { value: "/demo agent --target", description: "Choose local or live target", completion: "continue" },
  { value: "/demo guide", description: "Work with walkthrough guides", completion: "continue" },
  { value: "/demo guide create", description: "Create a walkthrough guide", completion: "run" },
  { value: "/demo guide list", description: "Show saved guides", completion: "run" },
  { value: "/demo guide show", description: "Show a guide", completion: "continue" },
  { value: "/demo guide edit", description: "Edit a guide", completion: "continue" },
  { value: "/demo guide delete", description: "Delete a guide", completion: "continue" },
  { value: "/demo guide save-instructions", description: "Save local guide instructions", completion: "continue", searchTerms: ["guide export"] },
  { value: "/demo policy", description: "Manage the safety policy", completion: "continue", searchTerms: ["safety"] },
  { value: "/demo policy init", description: "Set up the safety policy", completion: "run", searchTerms: ["safety setup"] },
  { value: "/demo policy check", description: "Check the safety policy", completion: "run", searchTerms: ["safety validate"] },
  { value: "/demo policy edit", description: "Edit the safety policy", completion: "run", searchTerms: ["safety change"] },
  { value: "/demo upload", description: "Upload an existing demo", completion: "continue" },
  { value: "/demo logs", description: "Show AI run logs", completion: "continue" },
  { value: "/queue", description: "Open the queue menu", completion: "run" },
  { value: "/queue list", description: "Show upcoming queue", completion: "run" },
  { value: "/queue stitch", description: "Queue a Stitch", completion: "run" },
  { value: "/queue stitch --all", description: "Queue all ready Stitches", completion: "run" },
  { value: "/queue stitch --product", description: "Filter Stitches by product", completion: "continue" },
  { value: "/queue swipe", description: "Queue a Swipe", completion: "run" },
  { value: "/queue swipe --all", description: "Queue all ready Swipes", completion: "run" },
  { value: "/queue swipe --product", description: "Filter Swipes by product", completion: "continue" },
  { value: "/queue --all", description: "Queue all ready Stitches and Swipes", completion: "run" },
  { value: "/products", description: "Open the products menu", completion: "run", searchTerms: ["product"] },
  { value: "/products list", description: "Show saved products", completion: "run", searchTerms: ["product show"] },
  { value: "/products create", description: "Create a product", completion: "run", searchTerms: ["product add"] },
  { value: "/products create --use", description: "Create and use a product", completion: "run", searchTerms: ["product add select"] },
  { value: "/products use", description: "Use a product for this repo", completion: "run", searchTerms: ["product select switch"] },
  { value: "/stitchr", description: "Work with Stitchr", completion: "continue" },
  { value: "/stitchr new", description: "Start new Stitchr work", completion: "run" },
  { value: "/stitchr new --product", description: "Use a product ID", completion: "continue" },
  { value: "/stitchr new --template", description: "Use a Stitch template", completion: "continue" },
  { value: "/stitchr new --sound", description: "Use a saved sound", completion: "continue" },
  { value: "/stitchr new --time-zone", description: "Use a time zone", completion: "continue" },
  { value: "/swipr", description: "Work with Swipr", completion: "continue" },
  { value: "/swipr new", description: "Start new Swipr drafts", completion: "run" },
  { value: "/swipr new --product", description: "Use a product ID", completion: "continue" },
  { value: "/native", description: "Open native setup and checks", completion: "run", searchTerms: ["device"] },
  { value: "/native init", description: "Set up native recording", completion: "run", searchTerms: ["device setup"] },
  { value: "/native init --force", description: "Repair native setup", completion: "run", searchTerms: ["device repair"] },
  { value: "/native check", description: "Check native setup", completion: "run", searchTerms: ["device doctor"] },
  { value: "/link", description: "Connect this repo", completion: "run", searchTerms: ["repo setup connect"] },
  { value: "/init", description: "Set up this repo", completion: "run", searchTerms: ["repo setup connect"] },
  { value: "/login", description: "Connect this machine", completion: "run", searchTerms: ["account sign in"] },
  { value: "/logout", description: "Disconnect this machine", completion: "run", searchTerms: ["account sign out"] },
  { value: "/unlink", description: "Disconnect this repo", completion: "run", searchTerms: ["repo disconnect"] },
  { value: "/status", description: "Show account and repo status", completion: "run", searchTerms: ["setup state"] },
  { value: "/doctor", description: "Check settings", completion: "run", searchTerms: ["setup diagnose"] },
  { value: "/update", description: "Update the CLI", completion: "run", searchTerms: ["upgrade"] },
  { value: "/help", description: "Show slash-command examples", completion: "run", searchTerms: ["commands"] },
  { value: "/main", description: "Return to the main menu", completion: "run", searchTerms: ["home"] },
  { value: "/exit", description: "Exit the shell", completion: "run", searchTerms: ["quit close"] },
];
