export type InteractiveShellMainAction =
  | "account"
  | "demo"
  | "doctor"
  | "link"
  | "login"
  | "native"
  | "products"
  | "queue"
  | "status"
  | "stitchr-new"
  | "swipr-new"
  | "update"
  | "nav:exit"
  | "nav:slash";
