import type { SlashCommandSuggestion } from "./SlashCommandSuggestion.js";

export const slashCommandSuggestions: SlashCommandSuggestion[] = [
  { value: "/demo", description: "Open the demo menu" },
  { value: "/demo manual", description: "Record a demo yourself" },
  { value: "/demo manual --guide", description: "Record with a saved guide" },
  { value: "/demo manual --no-guide", description: "Record without a guide" },
  { value: "/demo manual --no-upload", description: "Keep the recording local" },
  { value: "/demo agent", description: "Let AI record a guarded demo" },
  { value: "/demo agent --guide", description: "Run AI with a saved guide" },
  { value: "/demo agent --no-upload", description: "Review without uploading" },
  { value: "/demo agent --driver", description: "Choose the AI driver" },
  { value: "/demo agent --target", description: "Choose local or live target" },
  { value: "/demo guide", description: "Work with walkthrough guides" },
  { value: "/demo guide create", description: "Create a walkthrough guide" },
  { value: "/demo guide list", description: "Show saved guides" },
  { value: "/demo guide show", description: "Show a guide" },
  { value: "/demo guide edit", description: "Edit a guide" },
  { value: "/demo guide delete", description: "Delete a guide" },
  {
    value: "/demo guide save-instructions",
    description: "Save local guide instructions",
  },
  { value: "/demo policy", description: "Manage the safety policy" },
  { value: "/demo policy init", description: "Set up the safety policy" },
  { value: "/demo policy check", description: "Check the safety policy" },
  { value: "/demo policy edit", description: "Edit the safety policy" },
  { value: "/demo upload", description: "Upload an existing demo" },
  { value: "/demo logs", description: "Show AI run logs" },
  { value: "/queue", description: "Open the queue menu" },
  { value: "/queue list", description: "Show upcoming queue" },
  { value: "/queue stitch", description: "Queue a Stitch" },
  { value: "/queue stitch --all", description: "Queue all ready Stitches" },
  { value: "/queue stitch --product", description: "Filter Stitches by product" },
  { value: "/queue swipe", description: "Queue a Swipe" },
  { value: "/queue swipe --all", description: "Queue all ready Swipes" },
  { value: "/queue swipe --product", description: "Filter Swipes by product" },
  { value: "/queue --all", description: "Queue all ready Stitches and Swipes" },
  { value: "/products", description: "Open the products menu" },
  { value: "/products list", description: "Show saved products" },
  { value: "/products create", description: "Create a product" },
  { value: "/products create --use", description: "Create and use a product" },
  { value: "/products use", description: "Use a product for this repo" },
  { value: "/stitchr", description: "Work with Stitchr" },
  { value: "/stitchr new", description: "Start new Stitchr work" },
  { value: "/stitchr new --product", description: "Use a product ID" },
  { value: "/stitchr new --template", description: "Use a Stitch template" },
  { value: "/stitchr new --sound", description: "Use a saved sound" },
  { value: "/stitchr new --time-zone", description: "Use a time zone" },
  { value: "/swipr", description: "Work with Swipr" },
  { value: "/swipr new", description: "Start new Swipr drafts" },
  { value: "/swipr new --product", description: "Use a product ID" },
  { value: "/native", description: "Open native setup and checks" },
  { value: "/native init", description: "Set up native recording" },
  { value: "/native init --force", description: "Repair native setup" },
  { value: "/native check", description: "Check native setup" },
  { value: "/link", description: "Connect this repo" },
  { value: "/init", description: "Connect this repo" },
  { value: "/login", description: "Connect this machine" },
  { value: "/logout", description: "Disconnect this machine" },
  { value: "/unlink", description: "Disconnect this repo" },
  { value: "/status", description: "Show account and repo status" },
  { value: "/doctor", description: "Check settings" },
  { value: "/update", description: "Update the CLI" },
  { value: "/help", description: "Show slash-command examples" },
  { value: "/main", description: "Return to the main menu" },
  { value: "/exit", description: "Exit the shell" },
];
