import type { TextOverlayStyle } from "@/lib/clipr/types/TextOverlayStyle";

export const TEXT_OVERLAY_STYLES: TextOverlayStyle[] = [
  {
    id: "clean",
    label: "Clean",
    fontFamily: "Inter, Arial, Helvetica, sans-serif",
    fontWeight: "800",
    color: "#ffffff",
    shadowColor: "rgba(15, 23, 42, 0.78)",
    shadowBlurRatio: 0.14,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.08,
  },
  {
    id: "hook",
    label: "Hook",
    fontFamily: "Impact, Arial Black, Arial, sans-serif",
    fontWeight: "900",
    color: "#fde047",
    strokeColor: "#020617",
    strokeWidthRatio: 0.075,
    shadowColor: "rgba(2, 6, 23, 0.45)",
    shadowBlurRatio: 0.08,
    shadowOffsetXRatio: 0.03,
    shadowOffsetYRatio: 0.05,
    textTransform: "uppercase",
  },
  {
    id: "caption",
    label: "Caption",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontWeight: "800",
    color: "#ffffff",
    backgroundColor: "rgba(2, 6, 23, 0.72)",
    paddingXRatio: 0.48,
    paddingYRatio: 0.28,
    borderRadiusRatio: 0.22,
  },
  {
    id: "serif",
    label: "Serif",
    fontFamily: "Georgia, Times New Roman, serif",
    fontWeight: "700",
    color: "#fff7ed",
    shadowColor: "rgba(2, 6, 23, 0.72)",
    shadowBlurRatio: 0.12,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.07,
  },
  {
    id: "mono",
    label: "Mono",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontWeight: "800",
    color: "#f8fafc",
    backgroundColor: "rgba(15, 23, 42, 0.82)",
    textTransform: "uppercase",
    paddingXRatio: 0.42,
    paddingYRatio: 0.24,
    borderRadiusRatio: 0.05,
  },
];
