import type { PublicToolDefinition } from "./PublicToolDefinition";
import type { PublicToolKey } from "./PublicToolKey";

export const publicToolCatalog: Record<PublicToolKey, PublicToolDefinition> = {
  "ad-variant-calculator": {
    category: "testing",
    changeFrequency: "monthly",
    description:
      "See how many ad ideas are hiding inside the hooks, UGC clips, demos, and calls to action you already have.",
    eyebrow: "Creative planning",
    format: "calculator",
    iconKey: "calculator",
    key: "ad-variant-calculator",
    keywords: [
      "ad variant calculator",
      "app ad creative calculator",
      "UGC ad variations",
      "mobile app creative testing",
      "TikTok ad variant calculator",
    ],
    name: "Ad Variant Calculator",
    pathname: "/tools/ad-variant-calculator",
    portfolioNumber: 32,
    priority: 0.86,
    relatedToolKeys: [
      "app-ad-test-plan-generator",
      "app-ad-creative-testing-blueprint-builder",
    ],
    tiktokContentId: "ad_variant_calculator",
  },
  "app-hook-generator": {
    category: "hooks",
    changeFrequency: "weekly",
    description:
      "Turn a few plain-English details about your app and audience into short-form hooks built to start better ads.",
    eyebrow: "Hook ideas",
    format: "generator",
    iconKey: "sparkles",
    key: "app-hook-generator",
    keywords: [
      "app hook generator",
      "mobile app ad hooks",
      "TikTok hooks for apps",
      "app marketing hook ideas",
      "short-form app ad hooks",
    ],
    name: "App Hook Generator",
    pathname: "/tools/app-hook-generator",
    portfolioNumber: 11,
    priority: 0.88,
    relatedToolKeys: ["app-ad-hook-grader", "app-ad-hook-rewriter"],
    tiktokContentId: "app_hook_generator",
  },
  "product-demo-readiness-checker": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Check whether an app demo is clear, safe to share, and ready to become a short-form ad before you start editing.",
    eyebrow: "Demo planning",
    format: "checklist",
    iconKey: "clipboard-check",
    key: "product-demo-readiness-checker",
    keywords: [
      "product demo readiness checker",
      "app demo checklist",
      "mobile app demo review",
      "product demo video checklist",
      "app ad demo checker",
    ],
    name: "Product Demo Readiness Checker",
    pathname: "/tools/product-demo-readiness-checker",
    portfolioNumber: 23,
    priority: 0.84,
    relatedToolKeys: [
      "9-16-app-demo-video-checker",
      "app-ugc-clip-readiness-checker",
    ],
    tiktokContentId: "product_demo_readiness_checker",
  },
  "app-ad-hook-grader": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Score an app-ad opening for clarity, specificity, audience fit, curiosity, visual fit, and claim safety.",
    eyebrow: "Hook review",
    format: "tool",
    iconKey: "gauge",
    key: "app-ad-hook-grader",
    keywords: [
      "app ad hook grader",
      "hook strength checker",
      "TikTok hook analyzer",
      "mobile app ad hook score",
      "short-form hook checker",
    ],
    name: "Hook Strength Grader for App Ads",
    pathname: "/tools/app-ad-hook-grader",
    portfolioNumber: 12,
    priority: 0.84,
    relatedToolKeys: ["app-ad-hook-rewriter", "app-hook-generator"],
    tiktokContentId: "app_ad_hook_grader",
  },
  "app-ugc-brief-builder": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Build a clear, copyable UGC filming brief for an app without inventing proof or asking for one giant unusable take.",
    eyebrow: "Creator briefs",
    format: "generator",
    iconKey: "notebook-pen",
    key: "app-ugc-brief-builder",
    keywords: [
      "app UGC brief template",
      "UGC ad brief builder",
      "mobile app creator brief",
      "app ad shot list",
      "UGC brief for apps",
    ],
    name: "UGC Ad Brief Builder for Apps",
    pathname: "/tools/app-ugc-brief-builder",
    portfolioNumber: 47,
    priority: 0.84,
    relatedToolKeys: ["app-ad-shot-list-generator", "app-ugc-cost-calculator"],
    tiktokContentId: "app_ugc_brief_builder",
  },
  "app-ad-hook-rewriter": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Rewrite one app-ad hook six useful ways while keeping your real claims and product context intact.",
    eyebrow: "Hook rewrites",
    format: "generator",
    iconKey: "refresh-cw",
    key: "app-ad-hook-rewriter",
    keywords: [
      "app ad hook rewriter",
      "rewrite TikTok hook",
      "mobile app hook variations",
      "short-form ad hook rewrite",
      "app marketing copy tool",
    ],
    name: "App Ad Hook Rewrite Tool",
    pathname: "/tools/app-ad-hook-rewriter",
    portfolioNumber: 13,
    priority: 0.83,
    relatedToolKeys: ["app-ad-hook-grader", "hook-to-visual-matchmaker"],
    tiktokContentId: "app_ad_hook_rewriter",
  },
  "9-16-app-demo-video-checker": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Inspect an app demo's 9:16 shape, resolution, codecs, frame rate, audio, and browser support without uploading it.",
    eyebrow: "Video checks",
    format: "tool",
    iconKey: "rectangle-vertical",
    key: "9-16-app-demo-video-checker",
    keywords: [
      "9:16 video checker",
      "vertical video spec checker",
      "app demo video checker",
      "TikTok video dimensions checker",
      "Reels video format checker",
    ],
    name: "9:16 App Demo Video Checker",
    pathname: "/tools/9-16-app-demo-video-checker",
    portfolioNumber: 21,
    priority: 0.84,
    relatedToolKeys: [
      "product-demo-readiness-checker",
      "hook-to-visual-matchmaker",
    ],
    tiktokContentId: "nine_by_sixteen_app_demo_video_checker",
  },
  "app-ad-test-plan-generator": {
    category: "testing",
    changeFrequency: "monthly",
    description:
      "Turn the creative assets you already have into a focused, copyable app-ad testing order with one variable at a time.",
    eyebrow: "Creative testing",
    format: "planner",
    iconKey: "flask-conical",
    key: "app-ad-test-plan-generator",
    keywords: [
      "app ad test plan generator",
      "creative testing plan",
      "mobile app ad testing",
      "UGC creative test matrix",
      "TikTok ad testing plan",
    ],
    name: "App Ad Creative Test Plan Generator",
    pathname: "/tools/app-ad-test-plan-generator",
    portfolioNumber: 31,
    priority: 0.85,
    relatedToolKeys: [
      "app-ad-creative-testing-blueprint-builder",
      "ad-variant-calculator",
    ],
    tiktokContentId: "app_ad_test_plan_generator",
  },
  "hook-to-visual-matchmaker": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Match an app-ad hook to a practical opening shot and product-demo handoff using the footage you actually have.",
    eyebrow: "Creative matching",
    format: "planner",
    iconKey: "panels-top-left",
    key: "hook-to-visual-matchmaker",
    keywords: [
      "hook to visual matchmaker",
      "app ad storyboard generator",
      "TikTok hook visual ideas",
      "mobile app ad opening shot",
      "UGC hook visual matcher",
    ],
    name: "Hook-to-Visual Matchmaker for App Ads",
    pathname: "/tools/hook-to-visual-matchmaker",
    portfolioNumber: 15,
    priority: 0.83,
    relatedToolKeys: ["app-ad-hook-rewriter", "product-demo-readiness-checker"],
    tiktokContentId: "hook_to_visual_matchmaker",
  },
  "app-ugc-cost-calculator": {
    category: "business",
    changeFrequency: "monthly",
    description:
      "Estimate what one app UGC production cycle costs and how much paid footage is still sitting unused.",
    eyebrow: "Production costs",
    format: "calculator",
    iconKey: "circle-dollar-sign",
    key: "app-ugc-cost-calculator",
    keywords: [
      "app UGC cost calculator",
      "UGC production cost calculator",
      "creator ad cost calculator",
      "mobile app ad production cost",
      "cost per UGC ad",
    ],
    name: "App UGC Production Cost Calculator",
    pathname: "/tools/app-ugc-cost-calculator",
    portfolioNumber: 34,
    priority: 0.82,
    relatedToolKeys: [
      "app-ad-cost-per-creative-calculator",
      "app-ugc-brief-builder",
    ],
    tiktokContentId: "app_ugc_cost_calculator",
  },
  "app-ad-cost-per-creative-calculator": {
    category: "business",
    changeFrequency: "monthly",
    description:
      "Compare your current app-ad unit cost with a reuse scenario that finishes more publishable creatives from the same paid source footage.",
    eyebrow: "Creative economics",
    format: "calculator",
    iconKey: "badge-dollar-sign",
    key: "app-ad-cost-per-creative-calculator",
    keywords: [
      "app ad cost per creative calculator",
      "cost per ad creative",
      "creative production unit cost",
      "mobile app ad cost calculator",
      "UGC cost per creative",
    ],
    name: "App Ad Cost per Creative Calculator",
    pathname: "/tools/app-ad-cost-per-creative-calculator",
    portfolioNumber: 35,
    priority: 0.83,
    relatedToolKeys: [
      "app-ugc-cost-calculator",
      "app-ad-break-even-calculator",
    ],
    tiktokContentId: "app_ad_cost_per_creative_calculator",
  },
  "app-ad-break-even-calculator": {
    category: "business",
    changeFrequency: "monthly",
    description:
      "Turn your own spend, creative cost, customer value, margin, and conversion assumptions into transparent app-ad break-even targets.",
    eyebrow: "Acquisition economics",
    format: "calculator",
    iconKey: "chart-no-axes-combined",
    key: "app-ad-break-even-calculator",
    keywords: [
      "app ad break even calculator",
      "mobile app CAC calculator",
      "app install break even calculator",
      "paid social break even calculator",
      "app advertising ROAS calculator",
    ],
    name: "App Ad Break-Even Calculator",
    pathname: "/tools/app-ad-break-even-calculator",
    portfolioNumber: 36,
    priority: 0.84,
    relatedToolKeys: [
      "app-ad-cost-per-creative-calculator",
      "app-ad-test-plan-generator",
    ],
    tiktokContentId: "app_ad_break_even_calculator",
  },
  "app-ad-shot-list-generator": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Create an individually numbered app-ad capture list with framing, action, audio, duration, and clean handoff directions for every source file.",
    eyebrow: "Shoot planning",
    format: "generator",
    iconKey: "list-video",
    key: "app-ad-shot-list-generator",
    keywords: [
      "app ad shot list generator",
      "UGC ad shot list",
      "mobile app video shot list",
      "app commercial shot list",
      "product demo shot list",
    ],
    name: "App Ad Shot List Generator",
    pathname: "/tools/app-ad-shot-list-generator",
    portfolioNumber: 5,
    priority: 0.84,
    relatedToolKeys: [
      "app-ugc-brief-builder",
      "app-ugc-clip-readiness-checker",
    ],
    tiktokContentId: "app_ad_shot_list_generator",
  },
  "app-ugc-clip-readiness-checker": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Check one raw app UGC clip's technical facts, then review its framing, clean capture, reuse potential, and documented usage approval.",
    eyebrow: "UGC preparation",
    format: "checklist",
    iconKey: "badge-check",
    key: "app-ugc-clip-readiness-checker",
    keywords: [
      "app UGC clip readiness checker",
      "UGC video quality checklist",
      "raw UGC clip checker",
      "creator footage checklist",
      "UGC handoff checker",
    ],
    name: "App UGC Clip Readiness Checker",
    pathname: "/tools/app-ugc-clip-readiness-checker",
    portfolioNumber: 24,
    priority: 0.84,
    relatedToolKeys: ["app-ad-shot-list-generator", "app-ugc-brief-builder"],
    tiktokContentId: "app_ugc_clip_readiness_checker",
  },
  "app-ad-creative-testing-blueprint-builder": {
    category: "testing",
    changeFrequency: "monthly",
    description:
      "Build a focused app-ad testing blueprint with hypotheses, controlled cells, evidence rules, asset gaps, and a production handoff.",
    eyebrow: "Testing strategy",
    format: "planner",
    iconKey: "map",
    key: "app-ad-creative-testing-blueprint-builder",
    keywords: [
      "app ad creative testing blueprint",
      "creative testing blueprint builder",
      "mobile app ad testing strategy",
      "UGC testing framework",
      "app creative hypothesis template",
    ],
    name: "App Ad Creative Testing Blueprint Builder",
    pathname: "/tools/app-ad-creative-testing-blueprint-builder",
    portfolioNumber: 48,
    priority: 0.85,
    relatedToolKeys: ["app-ad-test-plan-generator", "ad-variant-calculator"],
    tiktokContentId: "app_ad_creative_testing_blueprint_builder",
  },
  "30-day-app-content-plan": {
    category: "planning",
    changeFrequency: "monthly",
    description:
      "Build a realistic 30-day app-content plan around your goal, posting pace, available footage, and comfort on camera.",
    eyebrow: "Content planning",
    format: "planner",
    iconKey: "map",
    key: "30-day-app-content-plan",
    keywords: [
      "30 day app content plan",
      "app marketing content plan",
      "mobile app social media plan",
    ],
    name: "30-Day Short-Form Content Plan for App Founders",
    pathname: "/tools/30-day-app-content-plan",
    portfolioNumber: 1,
    priority: 0.8,
    relatedToolKeys: [
      "app-marketing-content-calendar",
      "what-should-i-post-decision-tree",
    ],
    tiktokContentId: "thirty_day_app_content_plan",
  },
  "100-app-demo-video-hooks": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Browse 100 practical app-demo hooks with a matching opening visual and an honest claim-safety note.",
    eyebrow: "Hook library",
    format: "collection",
    iconKey: "sparkles",
    key: "100-app-demo-video-hooks",
    keywords: [
      "app demo video hooks",
      "100 app ad hooks",
      "mobile app hook examples",
    ],
    name: "100 Hooks for App Demo Videos",
    pathname: "/tools/100-app-demo-video-hooks",
    portfolioNumber: 2,
    priority: 0.81,
    relatedToolKeys: ["app-ad-hook-structures", "app-hook-generator"],
    tiktokContentId: "one_hundred_app_demo_video_hooks",
  },
  "app-ugc-ad-brief-template": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Copy a complete blank UGC brief template, see one filled example, and send creators clearer app-ad directions.",
    eyebrow: "Creator template",
    format: "worksheet",
    iconKey: "notebook-pen",
    key: "app-ugc-ad-brief-template",
    keywords: [
      "app UGC ad brief template",
      "UGC creator brief template",
      "mobile app creator brief",
    ],
    name: "App UGC Ad Brief Template",
    pathname: "/tools/app-ugc-ad-brief-template",
    portfolioNumber: 3,
    priority: 0.78,
    relatedToolKeys: ["app-ugc-brief-builder", "ugc-creator-handoff-kit"],
    tiktokContentId: "app_ugc_ad_brief_template",
  },
  "app-demo-recording-checklist": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Prepare a clean, readable app demo before recording with privacy, setup, gesture, payoff, and file-handoff checks.",
    eyebrow: "Demo capture",
    format: "checklist",
    iconKey: "clipboard-check",
    key: "app-demo-recording-checklist",
    keywords: [
      "app demo recording checklist",
      "screen recording checklist",
      "mobile app demo capture",
    ],
    name: "Product Demo Recording Checklist",
    pathname: "/tools/app-demo-recording-checklist",
    portfolioNumber: 4,
    priority: 0.8,
    relatedToolKeys: [
      "product-demo-readiness-checker",
      "9-16-app-demo-video-checker",
    ],
    tiktokContentId: "app_demo_recording_checklist",
  },
  "tiktok-reels-creative-testing-tracker": {
    category: "testing",
    changeFrequency: "monthly",
    description:
      "Track short-form creative tests locally and calculate CTR, install rate, CPI, and CPA without connecting an ad account.",
    eyebrow: "Test tracking",
    format: "worksheet",
    iconKey: "chart-no-axes-combined",
    key: "tiktok-reels-creative-testing-tracker",
    keywords: [
      "creative testing tracker",
      "TikTok ad test spreadsheet",
      "Reels creative tracker",
    ],
    name: "TikTok and Reels Creative Testing Tracker",
    pathname: "/tools/tiktok-reels-creative-testing-tracker",
    portfolioNumber: 6,
    priority: 0.79,
    relatedToolKeys: [
      "app-hook-testing-matrix",
      "short-form-campaign-retrospective-template",
    ],
    tiktokContentId: "tiktok_reels_creative_testing_tracker",
  },
  "ugc-creator-handoff-kit": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Give creators one practical handoff kit for folders, filenames, delivery notes, usage questions, missing files, and reshoots.",
    eyebrow: "Creator handoff",
    format: "kit",
    iconKey: "notebook-pen",
    key: "ugc-creator-handoff-kit",
    keywords: [
      "UGC creator handoff kit",
      "creator footage delivery checklist",
      "UGC file handoff",
    ],
    name: "UGC Creator Handoff Kit",
    pathname: "/tools/ugc-creator-handoff-kit",
    portfolioNumber: 7,
    priority: 0.77,
    relatedToolKeys: [
      "app-raw-footage-intake-checklist",
      "clip-naming-system-generator",
    ],
    tiktokContentId: "ugc_creator_handoff_kit",
  },
  "what-should-i-post-decision-tree": {
    category: "planning",
    changeFrequency: "monthly",
    description:
      "Answer five simple questions and get one practical app-content format, three post prompts, and the clips to prepare.",
    eyebrow: "Content decision",
    format: "tool",
    iconKey: "map",
    key: "what-should-i-post-decision-tree",
    keywords: [
      "what should my app post",
      "app content decision tree",
      "mobile app content ideas",
    ],
    name: "What Should I Post? Decision Tree",
    pathname: "/tools/what-should-i-post-decision-tree",
    portfolioNumber: 8,
    priority: 0.79,
    relatedToolKeys: [
      "30-day-app-content-plan",
      "app-marketing-content-calendar",
    ],
    tiktokContentId: "what_should_i_post_decision_tree",
  },
  "app-marketing-content-calendar": {
    category: "planning",
    changeFrequency: "monthly",
    description:
      "Turn your month, posting pace, channels, pillars, and campaign dates into an editable app-marketing calendar you can export.",
    eyebrow: "Publishing calendar",
    format: "planner",
    iconKey: "map",
    key: "app-marketing-content-calendar",
    keywords: [
      "app marketing content calendar",
      "mobile app social calendar",
      "TikTok content calendar app",
    ],
    name: "App Marketing Content Calendar",
    pathname: "/tools/app-marketing-content-calendar",
    portfolioNumber: 9,
    priority: 0.79,
    relatedToolKeys: ["30-day-app-content-plan", "five-day-app-content-sprint"],
    tiktokContentId: "app_marketing_content_calendar",
  },
  "short-form-ad-preflight-checklist": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Run one final self-check across the hook, visual, proof, claims, CTA, captions, audio, framing, rights, and destination.",
    eyebrow: "Before publishing",
    format: "checklist",
    iconKey: "clipboard-check",
    key: "short-form-ad-preflight-checklist",
    keywords: [
      "short form ad checklist",
      "TikTok ad preflight checklist",
      "video ad quality checklist",
    ],
    name: "Short-Form Ad Preflight Checklist",
    pathname: "/tools/short-form-ad-preflight-checklist",
    portfolioNumber: 10,
    priority: 0.81,
    relatedToolKeys: ["9-16-app-demo-video-checker", "app-ad-hook-grader"],
    tiktokContentId: "short_form_ad_preflight_checklist",
  },
  "app-ad-hook-structures": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Browse 50 distinct app-ad hook frameworks with a formula, example, opening visual, misuse warning, and claim guardrail.",
    eyebrow: "Hook frameworks",
    format: "collection",
    iconKey: "panels-top-left",
    key: "app-ad-hook-structures",
    keywords: [
      "app ad hook structures",
      "50 hook frameworks",
      "TikTok hook formulas",
    ],
    name: "50 App-Ad Hook Structures",
    pathname: "/tools/app-ad-hook-structures",
    portfolioNumber: 14,
    priority: 0.8,
    relatedToolKeys: ["100-app-demo-video-hooks", "app-category-hook-packs"],
    tiktokContentId: "app_ad_hook_structures",
  },
  "ugc-opening-line-prompt-cards": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Use 24 creator-friendly opening prompts with delivery direction, an alternate take, and an honest proof guardrail.",
    eyebrow: "Creator prompts",
    format: "collection",
    iconKey: "sparkles",
    key: "ugc-opening-line-prompt-cards",
    keywords: [
      "UGC opening line prompts",
      "UGC hook prompt cards",
      "creator opening lines",
    ],
    name: "UGC Opening-Line Prompt Cards",
    pathname: "/tools/ugc-opening-line-prompt-cards",
    portfolioNumber: 16,
    priority: 0.78,
    relatedToolKeys: ["app-ad-shot-list-generator", "app-category-hook-packs"],
    tiktokContentId: "ugc_opening_line_prompt_cards",
  },
  "app-category-hook-packs": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Open focused hook packs for fitness, finance, productivity, dating, education, and utility apps with category claim reminders.",
    eyebrow: "Category hooks",
    format: "collection",
    iconKey: "panels-top-left",
    key: "app-category-hook-packs",
    keywords: [
      "app category hooks",
      "fitness app ad hooks",
      "finance app hook examples",
    ],
    name: "App Category Hook Packs",
    pathname: "/tools/app-category-hook-packs",
    portfolioNumber: 17,
    priority: 0.79,
    relatedToolKeys: ["app-ad-hook-structures", "app-hook-generator"],
    tiktokContentId: "app_category_hook_packs",
  },
  "competitor-hook-research-worksheet": {
    category: "hooks",
    changeFrequency: "monthly",
    description:
      "Record what competing app ads actually show and say, then separate repeated evidence from your own interpretation.",
    eyebrow: "Hook research",
    format: "worksheet",
    iconKey: "notebook-pen",
    key: "competitor-hook-research-worksheet",
    keywords: [
      "competitor hook research",
      "ad hook research worksheet",
      "app ad competitor analysis",
    ],
    name: "Competitor Hook Research Worksheet",
    pathname: "/tools/competitor-hook-research-worksheet",
    portfolioNumber: 18,
    priority: 0.78,
    relatedToolKeys: [
      "why-did-this-ad-work-template",
      "app-ad-teardown-library",
    ],
    tiktokContentId: "competitor_hook_research_worksheet",
  },
  "app-hook-testing-matrix": {
    category: "testing",
    changeFrequency: "monthly",
    description:
      "Build a controlled hook-testing matrix that names the one changed variable in every app-ad test cell.",
    eyebrow: "Hook testing",
    format: "planner",
    iconKey: "flask-conical",
    key: "app-hook-testing-matrix",
    keywords: [
      "hook testing matrix",
      "app ad hook test",
      "creative testing matrix",
    ],
    name: "App Hook Testing Matrix",
    pathname: "/tools/app-hook-testing-matrix",
    portfolioNumber: 19,
    priority: 0.81,
    relatedToolKeys: [
      "app-ad-test-plan-generator",
      "tiktok-reels-creative-testing-tracker",
    ],
    tiktokContentId: "app_hook_testing_matrix",
  },
  "why-did-this-ad-work-template": {
    category: "learning",
    changeFrequency: "monthly",
    description:
      "Break an app ad into observable beats, keep inference separate, and leave with one controlled follow-up hypothesis.",
    eyebrow: "Creative analysis",
    format: "worksheet",
    iconKey: "notebook-pen",
    key: "why-did-this-ad-work-template",
    keywords: [
      "why did this ad work template",
      "creative ad analysis worksheet",
      "app ad breakdown",
    ],
    name: "Why Did This Ad Work? Breakdown Template",
    pathname: "/tools/why-did-this-ad-work-template",
    portfolioNumber: 20,
    priority: 0.78,
    relatedToolKeys: [
      "app-ad-teardown-library",
      "competitor-hook-research-worksheet",
    ],
    tiktokContentId: "why_did_this_ad_work_template",
  },
  "app-ad-dead-space-finder": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Inspect a local app-ad video for quiet, visually still spans worth reviewing before you edit, without uploading the file.",
    eyebrow: "Local video review",
    format: "tool",
    iconKey: "list-video",
    key: "app-ad-dead-space-finder",
    keywords: [
      "video dead space finder",
      "find silence in video",
      "app ad pacing checker",
    ],
    name: "App-Ad Dead-Space Finder",
    pathname: "/tools/app-ad-dead-space-finder",
    portfolioNumber: 22,
    priority: 0.82,
    relatedToolKeys: [
      "product-demo-readiness-checker",
      "app-ugc-clip-readiness-checker",
    ],
    tiktokContentId: "app_ad_dead_space_finder",
  },
  "tiktok-safe-zone-overlay": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Preview a screenshot or frame under conservative TikTok interface obstruction zones before placing important text.",
    eyebrow: "Text placement",
    format: "tool",
    iconKey: "rectangle-vertical",
    key: "tiktok-safe-zone-overlay",
    keywords: [
      "TikTok safe zone overlay",
      "TikTok text safe area",
      "vertical video safe zone",
    ],
    name: "TikTok Safe-Zone Overlay",
    pathname: "/tools/tiktok-safe-zone-overlay",
    portfolioNumber: 25,
    priority: 0.82,
    relatedToolKeys: [
      "short-form-video-specs-cheat-sheet",
      "9-16-app-demo-video-checker",
    ],
    tiktokContentId: "tiktok_safe_zone_overlay",
  },
  "app-video-compression-estimator": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Estimate output size, reduction range, bytes per minute, and upload time from your duration and bitrate choices.",
    eyebrow: "Video size planning",
    format: "calculator",
    iconKey: "calculator",
    key: "app-video-compression-estimator",
    keywords: [
      "video compression estimator",
      "video file size calculator",
      "bitrate file size calculator",
    ],
    name: "App Video Compression Estimator",
    pathname: "/tools/app-video-compression-estimator",
    portfolioNumber: 26,
    priority: 0.8,
    relatedToolKeys: [
      "short-form-video-specs-cheat-sheet",
      "9-16-app-demo-video-checker",
    ],
    tiktokContentId: "app_video_compression_estimator",
  },
  "short-form-video-specs-cheat-sheet": {
    category: "video",
    changeFrequency: "monthly",
    description:
      "Compare dated, source-linked short-form video dimensions, ratios, duration notes, formats, and practical recording guidance.",
    eyebrow: "Video reference",
    format: "collection",
    iconKey: "rectangle-vertical",
    key: "short-form-video-specs-cheat-sheet",
    keywords: [
      "short form video specs",
      "TikTok Reels Shorts dimensions",
      "vertical video specifications",
    ],
    name: "Short-Form Video Specs Cheat Sheet",
    pathname: "/tools/short-form-video-specs-cheat-sheet",
    portfolioNumber: 27,
    priority: 0.82,
    relatedToolKeys: [
      "tiktok-safe-zone-overlay",
      "app-video-compression-estimator",
    ],
    tiktokContentId: "short_form_video_specs_cheat_sheet",
  },
  "clip-naming-system-generator": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Create a clean, repeatable filename pattern for app, campaign, creator, concept, market, date, role, and version.",
    eyebrow: "Asset organization",
    format: "generator",
    iconKey: "list-video",
    key: "clip-naming-system-generator",
    keywords: [
      "video file naming convention",
      "clip naming generator",
      "creative asset naming system",
    ],
    name: "Clip Naming System Generator",
    pathname: "/tools/clip-naming-system-generator",
    portfolioNumber: 28,
    priority: 0.78,
    relatedToolKeys: [
      "ugc-creator-handoff-kit",
      "app-creative-asset-inventory-template",
    ],
    tiktokContentId: "clip_naming_system_generator",
  },
  "app-raw-footage-intake-checklist": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Build a clear raw-footage request covering files, clean handles, demos, audio, naming, usage details, and deadlines.",
    eyebrow: "Footage intake",
    format: "checklist",
    iconKey: "clipboard-check",
    key: "app-raw-footage-intake-checklist",
    keywords: [
      "raw footage intake checklist",
      "UGC footage request",
      "creator asset intake",
    ],
    name: "App Raw Footage Intake Checklist",
    pathname: "/tools/app-raw-footage-intake-checklist",
    portfolioNumber: 29,
    priority: 0.79,
    relatedToolKeys: [
      "ugc-creator-handoff-kit",
      "app-ugc-clip-readiness-checker",
    ],
    tiktokContentId: "app_raw_footage_intake_checklist",
  },
  "app-creative-asset-inventory-template": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Count ready, needs-work, missing, and rights-unknown creative assets, then see the most important gaps to capture next.",
    eyebrow: "Asset inventory",
    format: "worksheet",
    iconKey: "panels-top-left",
    key: "app-creative-asset-inventory-template",
    keywords: [
      "creative asset inventory template",
      "app ad asset checklist",
      "UGC asset inventory",
    ],
    name: "App Creative Asset Inventory Template",
    pathname: "/tools/app-creative-asset-inventory-template",
    portfolioNumber: 30,
    priority: 0.8,
    relatedToolKeys: [
      "raw-clips-to-campaign-planner",
      "app-ad-creative-testing-blueprint-builder",
    ],
    tiktokContentId: "app_creative_asset_inventory_template",
  },
  "app-ad-creative-fatigue-calculator": {
    category: "testing",
    changeFrequency: "monthly",
    description:
      "Model even-delivery impressions per creative and time to your own frequency ceiling without pretending to predict fatigue.",
    eyebrow: "Exposure planning",
    format: "calculator",
    iconKey: "chart-no-axes-combined",
    key: "app-ad-creative-fatigue-calculator",
    keywords: [
      "creative fatigue calculator",
      "ad frequency calculator",
      "creative refresh calculator",
    ],
    name: "App-Ad Creative Fatigue Calculator",
    pathname: "/tools/app-ad-creative-fatigue-calculator",
    portfolioNumber: 33,
    priority: 0.81,
    relatedToolKeys: [
      "app-ad-testing-budget-planner",
      "app-ad-test-plan-generator",
    ],
    tiktokContentId: "app_ad_creative_fatigue_calculator",
  },
  "app-ad-testing-budget-planner": {
    category: "business",
    changeFrequency: "monthly",
    description:
      "Allocate your own app-ad testing budget across production, media, and active cells while keeping backlog visible.",
    eyebrow: "Budget allocation",
    format: "calculator",
    iconKey: "circle-dollar-sign",
    key: "app-ad-testing-budget-planner",
    keywords: [
      "creative testing budget planner",
      "app ad testing budget",
      "UGC test budget calculator",
    ],
    name: "App-Ad Creative Testing Budget Planner",
    pathname: "/tools/app-ad-testing-budget-planner",
    portfolioNumber: 37,
    priority: 0.81,
    relatedToolKeys: [
      "app-ad-creative-testing-blueprint-builder",
      "app-ad-break-even-calculator",
    ],
    tiktokContentId: "app_ad_testing_budget_planner",
  },
  "ugc-creator-rate-comparison-worksheet": {
    category: "business",
    changeFrequency: "monthly",
    description:
      "Compare your own creator quotes by deliverables, usable clips, revisions, raw footage, usage terms, and add-ons.",
    eyebrow: "Quote comparison",
    format: "worksheet",
    iconKey: "badge-dollar-sign",
    key: "ugc-creator-rate-comparison-worksheet",
    keywords: [
      "UGC creator rate comparison",
      "creator quote worksheet",
      "UGC rate calculator",
    ],
    name: "UGC Creator Rate Comparison Worksheet",
    pathname: "/tools/ugc-creator-rate-comparison-worksheet",
    portfolioNumber: 38,
    priority: 0.79,
    relatedToolKeys: ["app-ugc-cost-calculator", "ugc-creator-handoff-kit"],
    tiktokContentId: "ugc_creator_rate_comparison_worksheet",
  },
  "client-content-capacity-calculator": {
    category: "business",
    changeFrequency: "monthly",
    description:
      "Find the limiting stage in your capture, editing, and review workflow and model weekly deliverable and client capacity.",
    eyebrow: "Team capacity",
    format: "calculator",
    iconKey: "calculator",
    key: "client-content-capacity-calculator",
    keywords: [
      "content capacity calculator",
      "agency client capacity",
      "video production capacity calculator",
    ],
    name: "Client Content Capacity Calculator",
    pathname: "/tools/client-content-capacity-calculator",
    portfolioNumber: 39,
    priority: 0.79,
    relatedToolKeys: [
      "app-ad-cost-per-creative-calculator",
      "clipstitchr-savings-report",
    ],
    tiktokContentId: "client_content_capacity_calculator",
  },
  "short-form-campaign-retrospective-template": {
    category: "testing",
    changeFrequency: "monthly",
    description:
      "Turn campaign evidence and observations into keep, stop, start, reusable-footage, and next-hypothesis decisions.",
    eyebrow: "Campaign learning",
    format: "worksheet",
    iconKey: "notebook-pen",
    key: "short-form-campaign-retrospective-template",
    keywords: [
      "campaign retrospective template",
      "creative testing retrospective",
      "ad campaign review worksheet",
    ],
    name: "Short-Form Campaign Retrospective Template",
    pathname: "/tools/short-form-campaign-retrospective-template",
    portfolioNumber: 40,
    priority: 0.8,
    relatedToolKeys: [
      "tiktok-reels-creative-testing-tracker",
      "app-ad-creative-testing-blueprint-builder",
    ],
    tiktokContentId: "short_form_campaign_retrospective_template",
  },
  "personalized-short-form-content-audit": {
    category: "planning",
    changeFrequency: "monthly",
    description:
      "Score your current short-form system across clarity, assets, repeatability, testing, and learning, then get a 14-day priority plan.",
    eyebrow: "Content audit",
    format: "tool",
    iconKey: "gauge",
    key: "personalized-short-form-content-audit",
    keywords: [
      "short form content audit",
      "app marketing content audit",
      "creative system score",
    ],
    name: "Personalized Short-Form Content Audit",
    pathname: "/tools/personalized-short-form-content-audit",
    portfolioNumber: 41,
    priority: 0.82,
    relatedToolKeys: [
      "30-day-app-content-plan",
      "app-creative-asset-inventory-template",
    ],
    tiktokContentId: "personalized_short_form_content_audit",
  },
  "five-day-app-content-sprint": {
    category: "learning",
    changeFrequency: "monthly",
    description:
      "Work through five complete days of inventory, positioning, concepts, capture planning, and publishing preparation at your own pace.",
    eyebrow: "Guided sprint",
    format: "course",
    iconKey: "map",
    key: "five-day-app-content-sprint",
    keywords: [
      "five day content sprint",
      "app content challenge",
      "mobile app content sprint",
    ],
    name: "Five-Day App Content Sprint",
    pathname: "/tools/five-day-app-content-sprint",
    portfolioNumber: 42,
    priority: 0.78,
    relatedToolKeys: ["30-day-app-content-plan", "ugc-to-app-ad-mini-course"],
    tiktokContentId: "five_day_app_content_sprint",
  },
  "ugc-to-app-ad-mini-course": {
    category: "learning",
    changeFrequency: "monthly",
    description:
      "Learn how usable UGC, honest hooks, product demos, controlled variants, and campaign evidence fit together.",
    eyebrow: "Mini-course",
    format: "course",
    iconKey: "notebook-pen",
    key: "ugc-to-app-ad-mini-course",
    keywords: [
      "UGC app ad course",
      "how to make UGC app ads",
      "UGC advertising mini course",
    ],
    name: "UGC-to-App-Ad Mini-Course",
    pathname: "/tools/ugc-to-app-ad-mini-course",
    portfolioNumber: 43,
    priority: 0.79,
    relatedToolKeys: [
      "app-ugc-ad-brief-template",
      "app-ad-shot-list-generator",
    ],
    tiktokContentId: "ugc_to_app_ad_mini_course",
  },
  "app-creative-testing-system-workshop": {
    category: "learning",
    changeFrequency: "monthly",
    description:
      "Build a recurring creative-testing operating charter for variables, roles, naming, evidence, review cadence, and asset flow.",
    eyebrow: "Guided workshop",
    format: "workshop",
    iconKey: "flask-conical",
    key: "app-creative-testing-system-workshop",
    keywords: [
      "creative testing workshop",
      "app ad testing system",
      "creative operations workshop",
    ],
    name: "Build Your First Creative Testing System Workshop",
    pathname: "/tools/app-creative-testing-system-workshop",
    portfolioNumber: 44,
    priority: 0.8,
    relatedToolKeys: [
      "app-ad-creative-testing-blueprint-builder",
      "short-form-campaign-retrospective-template",
    ],
    tiktokContentId: "app_creative_testing_system_workshop",
  },
  "short-form-content-system-notion-kit": {
    category: "planning",
    changeFrequency: "monthly",
    description:
      "Download five Notion-ready CSV templates for ideas, shoots, assets, publishing, and results with a practical setup guide.",
    eyebrow: "Notion-ready kit",
    format: "kit",
    iconKey: "panels-top-left",
    key: "short-form-content-system-notion-kit",
    keywords: [
      "short form content Notion template",
      "content system Notion kit",
      "UGC content planner CSV",
    ],
    name: "Short-Form Content System Notion-Ready Kit",
    pathname: "/tools/short-form-content-system-notion-kit",
    portfolioNumber: 45,
    priority: 0.8,
    relatedToolKeys: [
      "app-marketing-content-calendar",
      "app-creative-asset-inventory-template",
    ],
    tiktokContentId: "short_form_content_system_notion_kit",
  },
  "app-ad-teardown-library": {
    category: "learning",
    changeFrequency: "monthly",
    description:
      "Study original app-ad pattern teardowns across hooks, opening visuals, demo handoffs, proof, pacing, and calls to action.",
    eyebrow: "Creative teardowns",
    format: "collection",
    iconKey: "panels-top-left",
    key: "app-ad-teardown-library",
    keywords: [
      "app ad teardown library",
      "mobile app ad examples",
      "creative ad breakdowns",
    ],
    name: "App Ad Teardown Library",
    pathname: "/tools/app-ad-teardown-library",
    portfolioNumber: 46,
    priority: 0.82,
    relatedToolKeys: [
      "why-did-this-ad-work-template",
      "competitor-hook-research-worksheet",
    ],
    tiktokContentId: "app_ad_teardown_library",
  },
  "raw-clips-to-campaign-planner": {
    category: "production",
    changeFrequency: "monthly",
    description:
      "Describe the hooks, UGC, demos, proof, and calls to action you already have, then build a focused campaign handoff without uploading media.",
    eyebrow: "Campaign planning",
    format: "planner",
    iconKey: "map",
    key: "raw-clips-to-campaign-planner",
    keywords: [
      "raw clips campaign planner",
      "UGC campaign planner",
      "app ad asset planner",
    ],
    name: "Raw Clips to Campaign Planner",
    pathname: "/tools/raw-clips-to-campaign-planner",
    portfolioNumber: 49,
    priority: 0.84,
    relatedToolKeys: [
      "app-creative-asset-inventory-template",
      "ad-variant-calculator",
    ],
    tiktokContentId: "raw_clips_to_campaign_planner",
  },
  "clipstitchr-savings-report": {
    category: "business",
    changeFrequency: "monthly",
    description:
      "Compare your current monthly production workflow with a ClipStitchr scenario using your own time, cost, output, and footage assumptions.",
    eyebrow: "Workflow scenario",
    format: "calculator",
    iconKey: "badge-dollar-sign",
    key: "clipstitchr-savings-report",
    keywords: [
      "video workflow savings calculator",
      "ClipStitchr savings report",
      "content production cost comparison",
    ],
    name: "Interactive ClipStitchr Savings Report",
    pathname: "/tools/clipstitchr-savings-report",
    portfolioNumber: 50,
    priority: 0.84,
    relatedToolKeys: [
      "app-ad-cost-per-creative-calculator",
      "client-content-capacity-calculator",
    ],
    tiktokContentId: "clipstitchr_savings_report",
  },
};
