import type { CliprDurationSeconds } from "@/lib/clipstitchr/types/CliprDurationSeconds";
import type { CliprGenerationMode } from "@/lib/clipstitchr/types/CliprGenerationMode";
import type { CliprMusicMetadata } from "@/lib/clipstitchr/types/CliprMusicMetadata";
import type { CliprResolvedGenerationMode } from "@/lib/clipstitchr/types/CliprResolvedGenerationMode";
import type { CliprVideoModelId } from "@/lib/clipstitchr/types/CliprVideoModelId";

export type CliprMetadata = {
  jobId: string;
  productId: string;
  productName: string;
  avatarId: string;
  avatarPhotoId: string;
  demoClipId?: string;
  demoClipName?: string;
  voiceId: string;
  requestedGenerationMode?: CliprGenerationMode;
  generationMode?: CliprResolvedGenerationMode;
  requestedVideoModelId?: CliprVideoModelId;
  videoModelId?: CliprVideoModelId;
  scriptIdea?: string;
  targetDurationSeconds: CliprDurationSeconds;
  hookStyleKey: string;
  hookTemplateId: string;
  filledHook: string;
  variablesUsed: Record<string, string>;
  script: string;
  sceneCount: number;
  finalDurationSeconds: number;
  music?: CliprMusicMetadata;
  providerModels: string[];
  createdAt: string;
};
