export type R2ObjectKind =
  | "video-clip-video"
  | "video-clip-poster"
  | "photo"
  | "photo-original"
  | "photo-thumbnail"
  | "swapr-segment-video"
  | "library-music-audio"
  | "clipr-music-audio"
  | "clipr-avatar-video"
  | "clipr-scene-image"
  | "stitch-music-audio"
  | "stitch-video"
  | "stitch-poster"
  | "swipe-poster";
