import type { StitchrHookFeedbackStatus } from "@/lib/clipstitchr/types/StitchrHookFeedbackStatus";
import type { StitchrHookPlanSource } from "@/lib/clipstitchr/types/StitchrHookPlanSource";
import type { StitchrHookPlanStatus } from "@/lib/clipstitchr/types/StitchrHookPlanStatus";
import type { StitchrHookVariant } from "@/lib/clipstitchr/types/StitchrHookVariant";

export type StitchrHookPlan = {
  acceptedAt?: string;
  angle?: string;
  automationRunId?: string;
  automationTaskId?: string;
  caption?: string;
  createdAt: string;
  demoClipId?: string;
  demoClipName?: string;
  feedbackStatus?: StitchrHookFeedbackStatus;
  hashtags: string[];
  hookOptions: StitchrHookVariant[];
  id: string;
  productId?: string;
  productName?: string;
  providerModel?: string;
  providerPredictionId?: string;
  reason?: string;
  rejectedAt?: string;
  rejectionReason?: string;
  selectedHook: string;
  socialCaption?: string;
  source: StitchrHookPlanSource;
  status: StitchrHookPlanStatus;
  stitchId?: string;
  ugcClipId?: string;
  ugcClipName?: string;
  updatedAt: string;
};
