import type { R2ObjectReference } from "@/lib/clipstitchr/types/R2ObjectReference";
import type { StitchScore } from "@/lib/clipstitchr/types/StitchScore";
import type { StitchrMode } from "@/lib/clipstitchr/types/StitchrMode";
import type { StitchSequenceSegment } from "@/lib/clipstitchr/types/StitchSequenceSegment";
import type { StitchMusicMetadata } from "@/lib/clipstitchr/types/StitchMusicMetadata";
import type { TextOverlay } from "@/lib/clipstitchr/types/TextOverlay";
import type { VideoPlaybackRate } from "@/lib/clipstitchr/types/VideoPlaybackRate";
import type { VideoTrimRange } from "@/lib/clipstitchr/types/VideoTrimRange";

export type Stitch = {
  id: string;
  mode?: StitchrMode;
  name: string;
  ugcClipId: string;
  demoClipId: string;
  ugcClipName: string;
  demoClipName: string;
  ugcTrimRange?: VideoTrimRange;
  demoTrimRange?: VideoTrimRange;
  sequenceSegments?: StitchSequenceSegment[];
  stitchObject?: R2ObjectReference;
  blob?: Blob;
  posterObject?: R2ObjectReference;
  posterBlob?: Blob;
  posterVersion?: number;
  mimeType?: string;
  size?: number;
  width: number;
  height: number;
  duration: number;
  includeDemoAudio?: boolean;
  includeUgcAudio?: boolean;
  demoPlaybackRate?: VideoPlaybackRate;
  ugcPlaybackRate?: VideoPlaybackRate;
  music?: StitchMusicMetadata;
  textOverlay?: TextOverlay;
  textOverlays?: TextOverlay[];
  socialCaption?: string;
  stitchScore?: StitchScore;
  isPosted?: boolean;
  postedAt?: string;
  createdAt: string;
};
