import type { ClipType } from "@/lib/clipstitchr/types/ClipType";
import type { CliprMetadata } from "@/lib/clipstitchr/types/CliprMetadata";
import type { ClipPerformanceScore } from "@/lib/clipstitchr/types/ClipPerformanceScore";
import type { R2ObjectReference } from "@/lib/clipstitchr/types/R2ObjectReference";
import type { SwaprOutputMetadata } from "@/lib/clipstitchr/types/SwaprOutputMetadata";
import type { VideoTrimRange } from "@/lib/clipstitchr/types/VideoTrimRange";

export type VideoClip = {
  id: string;
  name: string;
  tags?: string[];
  videoDescription?: string;
  mainPersonDescription?: string;
  outfitDescription?: string;
  locationDescription?: string;
  poseDescription?: string;
  performanceScore?: ClipPerformanceScore;
  productDescription?: string;
  productId?: string;
  originalName: string;
  clipType: ClipType;
  libraryKind?: "clipr" | "demo" | "swapr" | "ugc";
  videoObject: R2ObjectReference;
  blob: Blob;
  posterObject?: R2ObjectReference;
  posterBlob?: Blob;
  posterVersion?: number;
  mimeType: string;
  sourceMimeType: string;
  size: number;
  originalSize: number;
  width: number;
  height: number;
  aspectRatio: number;
  duration: number;
  defaultTrimRange?: VideoTrimRange;
  hasAudio: boolean;
  swaprMetadata?: SwaprOutputMetadata;
  cliprMetadata?: CliprMetadata;
  isPosted?: boolean;
  postedAt?: string;
  createdAt: string;
  updatedAt: string;
};
