import type { CollectionResourceItem } from "@/lib/clipstitchr/tools/resources/CollectionResourceItem";

const appAdHookStructureEntries = [
  [
    "Direct clarity",
    "Problem + product action",
    "[Painful moment]? [App] lets you [specific supported action].",
    "Still rebuilding the same client update? Briefly lets you start from the last approved layout.",
    "Show the painful moment, then the exact product action.",
    "Do not stack several benefits into the second sentence.",
    "Confirm the named action works exactly as stated.",
  ],
  [
    "Direct clarity",
    "Audience + job",
    "If you are [specific person] trying to [specific job], watch this.",
    "If you are an indie founder trying to plan three demo posts, watch this.",
    "Show the person in the real situation before opening the app.",
    "Do not use a broad identity that makes the line meaningless.",
    "The demo must address the named job, not a nearby feature.",
  ],
  [
    "Direct clarity",
    "One-screen promise",
    "This one screen helps me [understand or organize one thing].",
    "This one screen helps me see which customer questions still need an answer.",
    "Open directly on the screen and point to the supporting details.",
    "Do not imply one screen completes an entire workflow.",
    "Frame subjective clarity as personal experience.",
  ],
  [
    "Direct clarity",
    "Before-the-moment use",
    "I open [app] right before [recurring moment] to [prepare in a specific way].",
    "I open RouteNote before a client call to see the last decision and next question.",
    "Show the real moment, followed by the preparation view.",
    "Do not turn preparation into a performance guarantee.",
    "Only show information the app truly makes available then.",
  ],
  [
    "Direct clarity",
    "Narrow capability",
    "[App] does not do everything. It does [one job] like this.",
    "DraftBin does not run your campaign. It keeps every approved opening in one place.",
    "Demonstrate the one job from input to useful state.",
    "Do not use false modesty before making an exaggerated claim.",
    "Make the limitation and capability both accurate.",
  ],
  [
    "Direct clarity",
    "Input + output",
    "Give [app] [real input], and it returns [observable output].",
    "Give MealMap your saved recipes, and it returns a weekly view you can edit.",
    "Keep the input visible before revealing the output.",
    "Do not hide manual setup or imply output quality is guaranteed.",
    "Describe an observable product result, not a life outcome.",
  ],
  [
    "Direct clarity",
    "Feature + reason",
    "I use [feature] because [specific workflow reason].",
    "I use the pinned view because open client reviews stop getting buried.",
    "Tap the feature and immediately show the reason it matters.",
    "Do not present preference as universal best practice.",
    "Use a reason your footage can make obvious.",
  ],
  [
    "Direct clarity",
    "Replace one step",
    "Instead of [old step], I now [supported app action].",
    "Instead of searching old messages, I open the decision history beside the task.",
    "Show the two routes with honest labels.",
    "Do not imply the app replaces systems that remain required.",
    "Keep the comparison limited to the demonstrated step.",
  ],
  [
    "Direct clarity",
    "Result first, path second",
    "Here is [useful app state]. Now I will show you how I got there.",
    "Here is the clean handoff summary. Now I will show you the three fields behind it.",
    "Open on the result, then replay the real creation path.",
    "Do not present seeded data as an instant default.",
    "Disclose prepared examples or skipped waiting time.",
  ],
  [
    "Direct clarity",
    "Boundary + fit",
    "Use [app] when you need [supported job], not when you need [unsupported job].",
    "Use QueueUp when you need a review order, not when you need the app to judge the work.",
    "Contrast the supported interface with a simple boundary card.",
    "Do not insult alternatives or users with different needs.",
    "Verify both the fit and the limitation against the shipped product.",
  ],
  [
    "Problem reframe",
    "Not the obvious problem",
    "The real problem with [workflow] is not [obvious issue]. It is [specific hidden friction].",
    "The real problem with content planning is not ideas. It is knowing which idea has footage.",
    "Show the obvious symptom, then reveal the hidden missing detail.",
    "Do not manufacture a contrarian take just to sound surprising.",
    "Use a friction you have observed or personally experienced.",
  ],
  [
    "Problem reframe",
    "Easy task, hard return",
    "[Task] is easy. Remembering where to restart is the hard part.",
    "Writing the note is easy. Remembering which decision it belongs to is the hard part.",
    "Complete the easy action, then show the saved return point.",
    "Do not dismiss genuine difficulty other users may face.",
    "Keep the claim about the demonstrated workflow.",
  ],
  [
    "Problem reframe",
    "Tool versus decision",
    "I did not need another [tool category]. I needed help deciding [specific decision].",
    "I did not need another calendar. I needed help choosing which launch clips came first.",
    "Show several tools, then the app view supporting the decision.",
    "Do not claim the app makes professional or high-stakes decisions for users.",
    "Describe decision support, not guaranteed correctness.",
  ],
  [
    "Problem reframe",
    "Invisible handoff cost",
    "[Workflow] looks finished until someone else has to pick it up.",
    "The creator brief looks finished until the editor has to identify which take is approved.",
    "Show the receiver's missing question, then the completed handoff field.",
    "Do not imply a checklist prevents every misunderstanding.",
    "Make the missing context specific and visible.",
  ],
  [
    "Problem reframe",
    "Setup becomes work",
    "When setting up [solution] becomes its own project, start smaller.",
    "When setting up a content system becomes its own project, start with one reusable shoot list.",
    "Show the smallest useful setup reaching a real result.",
    "Do not hide mandatory onboarding to support the point.",
    "Avoid claiming the small setup fits every team.",
  ],
  [
    "Problem reframe",
    "More is not clearer",
    "Adding more [data, reminders, or fields] did not make [job] clearer.",
    "Adding more campaign tags did not make the next creative decision clearer.",
    "Remove one noisy layer and focus the relevant app view.",
    "Do not imply less information is always safer or better.",
    "Frame the simplification as a use-case choice.",
  ],
  [
    "Problem reframe",
    "Started versus movable",
    "The problem was not starting [work]. It was knowing how to move it forward.",
    "The problem was not saving hook ideas. It was knowing which one was ready to film.",
    "Show a pile of started items, then one item with a clear next state.",
    "Do not imply a status field removes real blockers.",
    "Keep the product claim to visibility or organization.",
  ],
  [
    "Problem reframe",
    "Current versus found",
    "Finding [information] is not useful if you cannot tell whether it is current.",
    "Finding a creator brief is not useful if you cannot tell which revision was approved.",
    "Show two versions, then the app's date, approval, or version cue.",
    "Do not promise freshness without reliable underlying data.",
    "Only cite signals the app actually records.",
  ],
  [
    "Problem reframe",
    "Output versus evidence",
    "I did not need another answer. I needed to see what the answer was based on.",
    "I did not need another score. I needed to see which checklist items lowered it.",
    "Reveal the explanation or source behind the output.",
    "Do not imply explanation proves accuracy.",
    "Separate observable evidence from interpretation.",
  ],
  [
    "Problem reframe",
    "Reminder versus action",
    "A reminder that says '[vague task]' is just tomorrow's confusion.",
    "A reminder that says 'work on launch' is just tomorrow's confusion.",
    "Edit the vague reminder into one concrete app action.",
    "Do not shame users for needing flexible or open-ended notes.",
    "Use an action the product can genuinely support.",
  ],
  [
    "Demonstration",
    "Three-step walkthrough",
    "In three visible steps: [input], [action], [result].",
    "In three visible steps: choose the campaign, select the clips, review the shot list.",
    "Number each uninterrupted step on screen.",
    "Do not hide typing, setup, waiting, or approval outside the count.",
    "End on the exact result named in the hook.",
  ],
  [
    "Demonstration",
    "One input experiment",
    "I added [specific input] to see what [app] would do.",
    "I added one overdue item to see where the planner would place it.",
    "Enter a safe input and show the full product response.",
    "Do not generalize a single test into a reliability claim.",
    "Use a representative input and label special conditions.",
  ],
  [
    "Demonstration",
    "Button with consequence",
    "This button looks small. Here is what changes when I use it.",
    "This button looks small. Here is how it turns a draft into a review-ready handoff.",
    "Zoom into the control, tap it, then widen to show the changed state.",
    "Do not use editing to imply unrelated changes happen automatically.",
    "Show every product change caused by the action.",
  ],
  [
    "Demonstration",
    "Empty-state build",
    "Start empty. Add [two inputs]. Reach [useful state].",
    "Start empty. Add one audience and one goal. Reach a focused brief outline.",
    "Keep the entire empty-to-result path visible.",
    "Do not omit default data or a third required input.",
    "Label any preconfigured account settings.",
  ],
  [
    "Demonstration",
    "Same item, new view",
    "Same [item], different view—here is why I switch.",
    "Same launch plan, different view—here is why I switch from calendar to asset gaps.",
    "Hold the underlying item steady while changing only the view.",
    "Do not imply the view changes the underlying data or outcome.",
    "Explain the visible decision each view supports.",
  ],
  [
    "Demonstration",
    "Real-time correction",
    "Watch me catch and fix [specific mistake] before I finish.",
    "Watch me catch a missing demo clip before I send the creator handoff.",
    "Show the warning, the correction, and the cleared state.",
    "Do not claim the app catches every possible mistake.",
    "Name the exact condition the product checks.",
  ],
  [
    "Demonstration",
    "Reuse walkthrough",
    "I made this once. Here is exactly what changes for the next [case].",
    "I made this shot list once. Here is what changes for the next app feature.",
    "Duplicate the item and highlight every edited field.",
    "Do not present unchanged boilerplate as personalized output.",
    "Clarify what still needs human review.",
  ],
  [
    "Demonstration",
    "Failure-path tour",
    "Here is what [app] shows when [input or step] is not ready.",
    "Here is what the checker shows when a clip has no readable audio track.",
    "Use a safe failed case, then show the recovery guidance.",
    "Do not stage an error state that the product cannot produce.",
    "Avoid implying guidance automatically repairs the problem.",
  ],
  [
    "Demonstration",
    "Share-view reveal",
    "This is what I see, and this is what the recipient sees.",
    "This is my working brief, and this is the clean version the creator receives.",
    "Use a side-by-side capture with private details removed.",
    "Do not expose real customer data or imply access controls you lack.",
    "Demonstrate the actual recipient experience.",
  ],
  [
    "Demonstration",
    "Undo demonstration",
    "Before I try this, I want to know how to reverse it.",
    "Before I archive these ideas, I want to know how to restore one.",
    "Perform the action, then show the real undo or restore path.",
    "Do not imply deleted or overwritten data is recoverable when it is not.",
    "Mention time or plan limits on recovery.",
  ],
  [
    "Objection",
    "I already use something",
    "I already use [existing approach]. I added [app] for this missing job.",
    "I already use a spreadsheet. I added FrameList for checking whether every planned ad has footage.",
    "Show the gap first, then the narrow app workflow.",
    "Do not attack competitors or claim they lack a feature without evidence.",
    "Explain coexistence honestly if both tools remain necessary.",
  ],
  [
    "Objection",
    "I do not have time",
    "I tested the smallest setup that could still be useful.",
    "I tested one campaign, two hooks, and one demo before adding the rest.",
    "Record the true setup through the first useful state.",
    "Do not state a setup time you did not measure.",
    "Show all required steps and plan limitations.",
  ],
  [
    "Objection",
    "It looks complicated",
    "Ignore the advanced options. Start here for [basic job].",
    "Ignore the advanced filters. Start here to label the three clips you already have.",
    "Focus the camera on the basic entry point and one completion path.",
    "Do not hide complexity that appears immediately for the stated job.",
    "Keep the promise limited to the basic workflow.",
  ],
  [
    "Objection",
    "I might lose control",
    "Here is what [app] decides, and what still stays in your hands.",
    "The planner orders the test cells; you still choose which claims and clips are approved.",
    "Use two labeled columns for product action and human decision.",
    "Do not imply automation has judgment or accountability it lacks.",
    "State every consequential human review step.",
  ],
  [
    "Objection",
    "My workflow is different",
    "I changed these parts to make the setup fit [specific workflow].",
    "I changed the status names and owner fields to match our two-person content team.",
    "Show only real settings being changed.",
    "Do not imply full customization from a few configurable fields.",
    "Name fixed parts that cannot be changed.",
  ],
  [
    "Objection",
    "I will forget to use it",
    "I attached [app] to a moment that already happens.",
    "I open the asset check right after our weekly creative review.",
    "Film the existing routine and the app action beside it.",
    "Do not promise habit formation or behavior change.",
    "Frame the routine as a personal experiment.",
  ],
  [
    "Objection",
    "I am worried about privacy",
    "These are the controls I check before adding [sensitive information].",
    "These are the sharing and deletion controls I check before adding customer interview notes.",
    "Navigate the actual controls with safe example data.",
    "Do not make security, privacy, or compliance guarantees from interface controls alone.",
    "Link claims to documented product behavior.",
  ],
  [
    "Objection",
    "The result may be generic",
    "The useful part is not the template. It is the details I can change here.",
    "The useful part is not the brief outline. It is the proof boundary and shots I can edit.",
    "Highlight editable fields and show one meaningful change.",
    "Do not call fixed text personalized.",
    "Make clear which parts are deterministic or user-authored.",
  ],
  [
    "Objection",
    "It may cost more than it helps",
    "Use your own numbers before deciding whether this workflow fits.",
    "Enter your real production costs before deciding whether reusing footage changes the unit cost.",
    "Show transparent inputs and the arithmetic behind the result.",
    "Do not make savings, ROI, or performance predictions.",
    "Label every assumption and avoid outside benchmarks.",
  ],
  [
    "Objection",
    "Migration feels risky",
    "Start with one current [item] instead of moving the whole archive.",
    "Start with one current campaign instead of moving every old creative record.",
    "Show the limited starting slice and how it is used.",
    "Do not imply a partial setup provides full history or coverage.",
    "Disclose import, export, and data-retention boundaries.",
  ],
  [
    "Story and identity",
    "I built this because",
    "I built [app] because [specific recurring moment] kept happening.",
    "I built TakeMap because creator footage kept arriving without a clear demo handoff.",
    "Recreate the moment, then demonstrate the product response.",
    "Do not invent an origin story or imply universal demand.",
    "Keep the founder experience factual and specific.",
  ],
  [
    "Story and identity",
    "I changed my mind",
    "I thought [old belief]. Using [real experience] changed my mind.",
    "I thought every post needed a new concept. Tracking the footage showed which concepts could reuse a demo.",
    "Show the old assumption, then the evidence that challenged it.",
    "Do not manufacture a dramatic reversal without evidence.",
    "Separate your experience from a universal conclusion.",
  ],
  [
    "Story and identity",
    "For people who care about",
    "This is for [specific people] who care more about [value] than [alternative].",
    "This is for small teams that care more about a clear handoff than a giant production dashboard.",
    "Show the value through a concrete product choice.",
    "Do not stereotype or insult people who prefer the alternative.",
    "Confirm the product design genuinely reflects that value.",
  ],
  [
    "Story and identity",
    "The awkward first version",
    "The first version of [feature] got [specific thing] wrong.",
    "The first version of our shot list put every direction in one paragraph.",
    "Use a real old screenshot or a clearly labeled sketch, then the current flow.",
    "Do not fake a product history to create drama.",
    "Avoid claiming users requested the change without evidence.",
  ],
  [
    "Story and identity",
    "The customer phrase",
    "A customer called [problem] '[their phrase],' and that is exactly it.",
    "A founder called their footage folder 'a drawer full of almost-ads,' and that is exactly it.",
    "Put the anonymized phrase on screen, then show the related workflow.",
    "Do not use identifiable customer language without permission.",
    "Make clear whether the wording is quoted, paraphrased, or composite.",
  ],
  [
    "Story and identity",
    "The small-team reality",
    "When [role] is also doing [second role], this detail matters.",
    "When the founder is also the content manager, a clear next shoot matters more than another dashboard.",
    "Show the role switch, then the specific product detail.",
    "Do not claim every small team works the same way.",
    "Ground the insight in a real workflow or stated audience.",
  ],
  [
    "Story and identity",
    "The tradeoff we chose",
    "We chose [product tradeoff] because [user need].",
    "We chose separate raw-clip records because editors need to know which take can be reused.",
    "Demonstrate the tradeoff in the interface.",
    "Do not call the choice superior for every user.",
    "Acknowledge the limitation created by the choice.",
  ],
  [
    "Story and identity",
    "The honest not-for-you",
    "[App] is not for you if [honest unsupported need].",
    "ClipSort is not for you if you need the tool to publish campaigns directly to ad platforms.",
    "Show the supported job beside the clearly stated boundary.",
    "Do not use exclusion as empty posturing or competitor bait.",
    "Ensure the limitation remains true across plans.",
  ],
  [
    "Story and identity",
    "The moment it clicked",
    "[Workflow] clicked when I stopped [old behavior] and started [new behavior].",
    "Creative testing clicked when I stopped changing every element and started labeling one variable.",
    "Contrast the two setups with a concrete example.",
    "Do not imply one change guarantees better performance.",
    "Describe a learning process, not a universal law.",
  ],
  [
    "Story and identity",
    "The principle behind the feature",
    "This feature exists because we believe [plain-language product principle].",
    "The clip-status field exists because source footage should be understandable before an editor opens it.",
    "State the principle, then show the feature expressing it.",
    "Do not use a lofty principle disconnected from shipped behavior.",
    "Keep the principle modest, observable, and current.",
  ],
] as const;

export const appAdHookStructures: readonly CollectionResourceItem[] =
  appAdHookStructureEntries.map(
    (
      [category, title, formula, example, visual, warning, guardrail],
      index,
    ) => ({
      body: `Formula: ${formula} Opening visual: ${visual} Misuse warning: ${warning} Claim guardrail: ${guardrail}`,
      category,
      copyText: example,
      eyebrow: `${category} · ${index + 1}`,
      id: `app-ad-hook-structure-${String(index + 1).padStart(2, "0")}`,
      tags: [category, "Framework"],
      title,
    }),
  );
