import type { AvatarWardrobeStyle } from "@/lib/clipstitchr/types/AvatarWardrobeStyle";

export const avatarGenerationOutfitTops = [
  "a fitted charcoal crewneck sweater",
  "a casual denim jacket over a plain white t-shirt",
  "a light linen shirt with rolled sleeves",
  "a black bomber jacket with a neutral t-shirt",
  "a soft gray hoodie under a lightweight jacket",
  "a navy overshirt with a cream t-shirt",
  "a minimal black turtleneck",
  "a relaxed flannel shirt layered over a solid tee",
  "a simple athletic zip jacket",
  "a clean casual blazer over a plain tee",
  "a cropped canvas chore jacket over a ribbed tank",
  "a lightweight rain shell over a merino base layer",
  "a cream cable-knit cardigan over a fitted tee",
  "a structured olive utility jacket with a striped shirt",
  "a soft varsity jacket over a thermal henley",
  "a loose white button-down shirt",
  "a fitted mock-neck top with a satin bomber jacket",
  "a pastel sweatshirt with a relaxed fit",
  "a short-sleeve knit polo",
  "a warm sherpa jacket over a waffle-knit top",
  "a washed canvas work jacket over a thermal tee",
  "a lightweight coach jacket over a crewneck tee",
  "a ribbed quarter-zip sweater",
  "a relaxed cardigan over a graphic-free tee",
  "a crisp poplin shirt worn open over a tank",
  "a soft fleece pullover",
  "a boxy cropped hoodie over a fitted tee",
  "a breathable mesh training top under a wind vest",
  "a dark denim overshirt over a striped tee",
  "a collarless chore coat over a cotton henley",
  "a brushed flannel overshirt over a ribbed tank",
  "a quilted liner jacket over a plain long-sleeve",
  "a textured knit cardigan over a crewneck top",
  "a satin camp shirt over a fitted base layer",
  "a mock-neck knit top under a suede overshirt",
  "a lightweight anorak over a simple tee",
  "a vintage-style sweatshirt with subtle texture",
  "a linen overshirt over a monochrome tank",
  "a fitted athletic long-sleeve top",
  "an oversized rugby shirt with clean stripes",
  "a cropped utility vest over a cotton tee",
  "a soft boucle jacket over a neutral tank",
  "a structured shirt jacket over a waffle-knit tee",
  "an airy gauze button-up shirt",
  "a technical running vest over a fitted base layer",
  "an oversized hoodie with clean minimal styling",
  "a brushed cotton shacket over a plain tee",
  "a silk-feel blouse with a simple collar",
  "a waxed cotton jacket over a henley",
  "a slouchy knit sweater with ribbed cuffs",
  "a lightweight cardigan over a square-neck top",
  "a breathable polo shirt with a zip collar",
  "a clean crewneck sweatshirt layered over a collared shirt",
  "a herringbone overshirt over a black tee",
  "a cropped track jacket over a neutral top",
  "a relaxed mandarin-collar shirt",
  "a soft thermal top under a sleeveless puffer vest",
  "a merino crewneck sweater",
  "a boxy short-sleeve overshirt over a tank",
  "a quilted bomber jacket over a fine-gauge knit",
  "a faded chambray shirt over a white tee",
  "a fitted ribbed mock-neck shirt",
  "a lightweight utility vest over a linen shirt",
  "a modern zip-front cardigan over a simple tee",
  "a clean windbreaker over an athletic base layer",
  "a loose cotton tunic shirt",
  "a minimal crewneck knit with subtle texture",
  "a belted safari jacket over a plain tee",
  "a bright color-block track jacket",
  "a relaxed hoodie under a denim vest",
  "a twill overshirt over a crewneck sweatshirt",
  "a brushed alpaca-style cardigan over a fitted top",
  "a waterproof shell over a grid-fleece pullover",
  "a terry-cloth camp-collar shirt",
  "a simple V-neck sweater over a white tee",
  "a cropped zip hoodie over a ribbed tank",
  "a tailored waistcoat over a button-down shirt",
  "a loose seersucker shirt with rolled sleeves",
  "a soft henley shirt with an open overshirt",
  "a suede bomber jacket over a cream knit",
  "a minimalist crewneck tee under a long cardigan",
  "an athletic compression top under an open hoodie",
  "a relaxed plaid overshirt over a thermal tee",
  "a polished knit jacket over a crewneck tee",
  "a denim chore coat over a black t-shirt",
  "a lightweight wool overshirt over a mock neck",
  "a cotton popover shirt with a relaxed collar",
  "a quilted field jacket over a simple sweater",
  "a fleece vest over a long-sleeve tee",
  "a clean sleeveless knit top under a boxy jacket",
  "a striped Breton-style shirt under a navy jacket",
  "a relaxed resort shirt with a subtle pattern",
  "a fitted square-neck top under a canvas jacket",
  "a perforated training shirt with a thin wind layer",
  "a soft shawl-collar cardigan over a tee",
  "a structured short trench over a plain sweater",
  "a minimal zip-neck sweater",
  "a cotton cardigan over a ribbed long-sleeve",
  "a relaxed bowling shirt over a white tank",
  "a lightweight parka over a neutral sweatshirt",
  "a cropped moto jacket over a plain top",
  "a simple sleeveless turtleneck under an overshirt",
  "an open knit shirt over a fitted base layer",
  "a brushed crewneck fleece with a clean silhouette",
  "a tailored double-knit blazer over a cotton tee",
  "a boxy linen jacket over a crewneck tank",
  "a lightweight poncho-style rain jacket",
  "a thermal henley under a quilted vest",
  "a classic Harrington jacket over a polo",
  "a loose Oxford shirt under a sweater vest",
  "a ribbed cardigan worn over a simple tank",
  "a breathable cycling jersey under a windbreaker",
  "a soft cowl-neck sweater",
  "a relaxed hoodie under a wool overshirt",
  "a canvas field jacket over a striped long-sleeve",
  "a clean knit tank under an open button-down",
  "a cropped fleece jacket over a fitted tee",
  "a minimalist snap-front overshirt",
  "a quilted shirt jacket over a thin turtleneck",
  "a lightweight travel blazer over a plain tee",
] as const;

export const avatarGenerationOutfitBottoms = [
  "dark straight jeans and clean white sneakers",
  "relaxed tan chinos and low-profile sneakers",
  "black wide-leg trousers and simple loafers",
  "olive cargo pants and trail shoes",
  "tailored joggers and simple trainers",
  "washed black denim and polished ankle boots",
  "pressed navy trousers and white court sneakers",
  "utility shorts, crew socks, and hiking sneakers",
  "cropped trousers and suede slip-on shoes",
  "faded blue jeans and worn-in canvas sneakers",
  "black leggings and bright training shoes",
  "linen drawstring pants and leather sandals",
  "pleated midi skirt and ankle boots",
  "charcoal cargo trousers and black boots",
  "tailored shorts and clean court sneakers",
  "wide-leg denim and platform sneakers",
  "running shorts, crew socks, and lightweight trainers",
  "cream utility pants and brown suede sneakers",
  "dark track pants and retro running shoes",
  "straight khaki pants and simple leather loafers",
  "ribbed lounge pants and slip-on sneakers",
  "stone-colored jeans and gum-sole sneakers",
  "black tailored pants and polished Chelsea boots",
  "relaxed carpenter pants and canvas high-tops",
  "soft joggers and minimal white trainers",
  "relaxed black chinos and white platform sneakers",
  "tapered olive trousers and gum-sole trainers",
  "light denim shorts and classic low-top sneakers",
  "charcoal joggers and trail-running shoes",
  "pleated navy trousers and polished loafers",
  "cream wide-leg pants and simple sandals",
  "dark cargo shorts and hiking sandals",
  "straight gray jeans and black boots",
  "cropped black jeans and canvas slip-ons",
  "tailored beige trousers and suede loafers",
  "olive utility pants and brown hiking boots",
  "navy running shorts and lightweight trainers",
  "white denim jeans and tan sneakers",
  "a ribbed knit skirt and ankle boots",
  "a dark pleated skirt and court sneakers",
  "relaxed linen shorts and leather slides",
  "tapered charcoal pants and minimalist sneakers",
  "washed blue carpenter jeans and canvas high-tops",
  "black bike shorts and chunky trainers",
  "khaki cargo pants and retro sneakers",
  "gray wool trousers and clean white trainers",
  "olive hiking shorts and trail runners",
  "a dark denim skirt and low-profile boots",
  "tan work pants and black canvas sneakers",
  "navy track shorts, crew socks, and sneakers",
  "ecru denim pants and brown loafers",
  "black parachute pants and running shoes",
  "patterned lounge pants and slip-on shoes",
  "cropped cream trousers and ballet flats",
  "a dark utility skirt and sturdy boots",
  "slim black jeans and leather sneakers",
  "relaxed gray sweatpants and court shoes",
  "pressed tan shorts and white sneakers",
  "olive pleated trousers and suede desert boots",
  "blue wide-leg jeans and platform loafers",
  "black tailored shorts and minimalist trainers",
  "stone cargo pants and trail sneakers",
  "dark wash jeans and tan Chelsea boots",
  "a jersey midi skirt and clean sneakers",
  "navy chinos and retro running shoes",
  "a white tennis skirt and court sneakers",
  "brown corduroy pants and leather boots",
  "black nylon pants and technical sneakers",
  "relaxed khaki shorts and canvas slip-ons",
  "cropped navy trousers and polished oxfords",
  "cream joggers and low-profile trainers",
  "faded black jeans and suede boots",
  "olive drawstring shorts and outdoor sandals",
  "gray tapered sweatpants and high-top sneakers",
  "pinstripe wide-leg trousers and loafers",
  "dark linen trousers and woven sandals",
  "tan carpenter shorts and skate shoes",
  "a black cargo skirt and chunky boots",
  "light gray jeans and white court sneakers",
  "navy hiking pants and waterproof trail shoes",
  "relaxed pleated shorts and leather sneakers",
  "cream knit pants and soft slip-on shoes",
  "olive corduroy pants and brown sneakers",
  "black athletic shorts and running shoes",
  "pale blue jeans and beige ankle boots",
  "dark tapered chinos and white leather sneakers",
  "rust-colored work pants and canvas sneakers",
  "a charcoal skirt and polished loafers",
  "white wide-leg trousers and minimal sandals",
  "navy nylon joggers and bright trainers",
  "tan culottes and neutral flats",
  "black cropped trousers and low-cut boots",
  "a light wash denim skirt and platform sneakers",
  "olive trail pants and hiking sandals",
  "gray drawstring trousers and suede mules",
  "dark straight trousers and classic penny loafers",
  "cream cargo shorts and sport sandals",
  "blue relaxed jeans and black high-tops",
  "charcoal technical pants and trail runners",
  "tan linen pants and white espadrilles",
  "black pleated trousers and polished dress shoes",
  "sage utility shorts and low-top sneakers",
  "washed gray jeans and Chelsea boots",
  "a navy wrap skirt and simple flats",
  "oatmeal joggers and retro trainers",
  "black waxed jeans and rugged boots",
  "light khaki trousers and canvas sneakers",
  "dark running tights and lightweight road shoes",
  "cream tailored shorts and woven loafers",
  "olive straight-leg jeans and gum-sole sneakers",
  "gray cargo pants and skate shoes",
  "a black midi skirt and ankle boots",
  "indigo denim culottes and white sneakers",
  "navy wool trousers and brown loafers",
  "tan hiking pants and trail sandals",
  "washed black shorts and high-top sneakers",
  "cream work pants and minimalist trainers",
  "blue slim jeans and clean boots",
  "a dark satin skirt and low-profile sneakers",
  "gray linen shorts and leather sandals",
  "olive joggers and canvas slip-ons",
  "black wide-leg jeans and platform boots",
  "tan pleated trousers and suede sneakers",
  "navy relaxed jeans and white trainers",
  "charcoal drawstring shorts and trail sneakers",
] as const;

const femaleOutfitPattern =
  /\b(ballet flats|blouse|brooch|culottes|midi skirt|skirt|square-neck|satin skirt|tennis skirt|wrap skirt)\b/i;

function getOutfitWardrobeStyle(description: string): AvatarWardrobeStyle {
  if (femaleOutfitPattern.test(description)) {
    return "female";
  }

  return "any";
}

export const avatarGenerationOutfits = avatarGenerationOutfitTops.flatMap(
  (top) =>
    avatarGenerationOutfitBottoms.map((bottoms) => `${top} with ${bottoms}`),
);

export function getAvatarGenerationOutfits(
  wardrobeStyle: AvatarWardrobeStyle,
) {
  if (wardrobeStyle === "any") {
    return avatarGenerationOutfits;
  }

  return avatarGenerationOutfits.filter((outfit) => {
    const outfitWardrobeStyle = getOutfitWardrobeStyle(outfit);

    return (
      outfitWardrobeStyle === "any" || outfitWardrobeStyle === wardrobeStyle
    );
  });
}
