export const avatarUgcReactionPoseActions = [
  "looking directly into the front camera with a surprised reaction",
  "holding one hand over their mouth while reacting to something unexpected",
  "pointing toward the camera in a creator reaction moment",
  "leaning slightly toward the phone camera with raised eyebrows",
  "smiling with a small hand-to-chest reaction gesture",
  "making a confused expression while looking into the camera",
  "widening their eyes as if reacting mid-scroll",
  "covering part of their mouth while smiling in disbelief",
  "tilting their head with a skeptical reaction expression",
  "reacting with an excited open-mouth smile",
  "looking just off camera with a quick surprised glance",
  "resting their chin on one hand with a curious reaction",
  "raising one hand beside their face in a quick wait gesture",
  "nodding slightly toward the front camera mid-reaction",
  "making a quiet wow expression while close to the camera",
  "holding one finger near their cheek while processing a surprise",
  "leaning in with a friendly creator-style reaction smile",
  "reacting with a doubtful half-smile and direct eye contact",
  "placing one hand lightly near their face in a shocked reaction",
  "glancing sideways while keeping their face close to the camera",
];
