import type { AvatarScenarioCategory } from "@/lib/clipstitchr/types/AvatarScenarioCategory";

export const avatarGenerationLocationSettings = [
  "the driver's seat of a parked car on a city street",
  "a tree-lined neighborhood path with bike racks nearby",
  "an airplane window seat during daytime travel",
  "an outdoor cafe patio with small groups in the background",
  "a lush garden with flowers and greenery behind the subject",
  "a busy airport terminal with travel bags nearby",
  "a sunny beach boardwalk with the ocean in the distance",
  "a clean hotel room mirror and neutral hotel decor",
  "a subway platform during a daily commute",
  "a coffee shop table with warm indoor ambience",
  "a scenic hiking overlook with mountains in the distance",
  "a weekend street market with colorful stalls nearby",
  "the back seat of a rideshare with city lights through the window",
  "the entrance of a concert venue with friends in the background",
  "a modern apartment kitchen",
  "a plant-filled bookstore aisle",
  "a food truck on a lively city block",
  "wide stone steps outside a museum entrance",
  "a glass railing on a rooftop terrace",
  "a train station concourse with departure boards behind the subject",
  "a bright coworking lounge with laptops and soft seating nearby",
  "a clean modern elevator mirror",
  "a quiet pedestrian bridge over a river",
  "a rental car at a scenic roadside overlook",
  "a picnic table in a neighborhood park",
  "a colorful mural on a side street",
  "a grocery store produce aisle",
  "a laundromat with rows of clean machines behind the subject",
  "an outdoor stadium seating area before an event starts",
  "a marina walkway with boats in soft focus behind the subject",
  "a farmers market with canvas tents and flower buckets nearby",
  "a bright art gallery with framed prints behind the subject",
  "a gym locker room mirror",
  "a large cafe window with soft light",
  "a downtown crosswalk with storefronts in the background",
  "the front of a neighborhood bakery",
  "a balcony with apartment buildings and trees behind the subject",
  "a park bench with leaves scattered nearby",
  "a pool deck at a sunny boutique hotel",
  "a clean studio apartment with moving boxes nearby",
  "a vending machine area in a train station",
  "a ski lodge window with snowy trees outside",
  "a university courtyard with brick buildings behind the subject",
  "a ferry deck with water and skyline in the distance",
  "a quiet library reading area with shelves behind the subject",
  "a bowling alley with colorful lanes in the background",
  "a hotel hallway with warm sconces and patterned carpet",
  "a scenic desert pullout with red rock formations behind the subject",
  "a bright hair salon waiting area with mirrors in the background",
  "a tennis court fence",
  "a busy convention center hallway with badges and banners nearby",
  "a compact home office with plants and a tidy desk behind the subject",
  "a bus stop shelter with city traffic passing behind the subject",
  "a brick wall outside a small music venue",
  "a lakeside trail with reeds and water behind the subject",
  "a home improvement store aisle with lighting fixtures nearby",
  "a basketball court with painted lines and benches behind the subject",
  "a kitchen island in a sunlit rental house",
  "neon signs on a lively downtown street",
  "a quiet residential sidewalk with blooming trees behind the subject",
  "a glass-walled office meeting room",
  "an airport gate with carry-on luggage nearby",
  "a small record shop with vinyl shelves behind the subject",
  "a coastal pier with railings and water in the background",
  "a campsite picnic area with tents and string lights behind the subject",
  "the back seat of a rideshare during daylight with city buildings outside",
  "a botanical conservatory with large tropical leaves nearby",
  "a modern public fountain in a city plaza",
  "a rustic cabin porch with trees in the background",
  "a bright dance studio with mirrors and wood floors behind the subject",
  "a snowy sidewalk with storefront lights behind the subject",
  "a diner booth with chrome trim and soft window light",
  "a bike-share rack on a sunny city corner",
  "a quiet shopping mall atrium with skylights overhead",
  "a movie theater entrance with posters in soft focus",
  "a brick-lined city alley with string lights overhead",
  "a quiet downtown plaza with stone benches and planters",
  "a city sidewalk outside a glass storefront",
  "a neighborhood corner with a painted crosswalk and small trees",
  "a public art wall beside a busy avenue",
  "a covered arcade with small shops on both sides",
  "a narrow side street with cafe tables along the curb",
  "a modern city square with a fountain and office towers behind it",
  "a pedestrian-only street with storefront awnings",
  "a street-level flower kiosk on a busy block",
  "a shaded sidewalk beside historic row houses",
  "a downtown bus lane with tall buildings in the background",
  "a quiet residential stoop with potted plants nearby",
  "a city overlook terrace with skyline buildings behind the subject",
  "a small public courtyard between apartment buildings",
  "a light rail platform with route signs and glass shelters",
  "a city bus interior with patterned seats and large windows",
  "a train car vestibule with brushed metal doors",
  "a quiet airport baggage claim area with luggage belts behind the subject",
  "a ferry terminal waiting area with water visible through windows",
  "a tram stop beside a tree-lined boulevard",
  "a parking garage elevator lobby with directional signs",
  "a commuter rail station under a high arched roof",
  "a hotel shuttle pickup area outside an airport terminal",
  "a compact rental car counter with travel posters behind it",
  "a covered taxi stand outside a train station",
  "a subway station mezzanine with tiled walls",
  "a long airport moving walkway corridor",
  "a roadside rest stop picnic area near parked cars",
  "a bus terminal waiting area with rows of seats",
  "a sidewalk outside a neighborhood ramen restaurant",
  "a bright juice bar counter with fruit displays behind it",
  "a taco stand with colorful menu boards in soft focus",
  "a cozy bakery case with pastries behind the subject",
  "a small diner counter with chrome stools and pendant lights",
  "a food court seating area with warm overhead lighting",
  "a farmers market bread stall with baskets and linen cloths",
  "a coffee roastery counter with bags of beans in the background",
  "a gelato shop counter with pastel display cases",
  "a restaurant patio with plants and small tables",
  "a tea shop wall with tins and cups arranged behind the subject",
  "a casual pizza shop with tile walls and booth seating",
  "a smoothie shop counter with bright menu panels",
  "a corner bodega aisle with drinks and snacks in the background",
  "a rooftop restaurant terrace with city lights behind the subject",
  "a calm bedroom corner with soft bedding and a bedside lamp",
  "a bright bathroom vanity with clean tile and a large mirror",
  "a walk-in closet area with organized shelves behind the subject",
  "a living room wall with framed prints and a neutral sofa nearby",
  "a sunlit dining nook with a round table and plants",
  "a laundry room with folded towels and bright cabinets",
  "a mudroom entryway with hooks and woven baskets",
  "a small balcony garden with rail planters and city views",
  "a home pantry with labeled jars and shelves behind the subject",
  "a garage storage wall with bins and sports gear nearby",
  "a home workout corner with a mat and weights in the background",
  "a cozy reading corner with an armchair and floor lamp",
  "a hallway gallery wall with family-style frames and soft light",
  "a craft table in a spare room with supplies arranged nearby",
  "a backyard patio with string lights and outdoor chairs",
  "a university classroom with desks and a whiteboard behind the subject",
  "a lecture hall aisle with tiered seats in the background",
  "a quiet study room with glass walls and laptop desks",
  "a coworking phone booth area with acoustic panels",
  "a conference room with a long table and soft daylight",
  "an office lobby with modern seating and reception lights",
  "a creative agency wall with mood boards and samples",
  "a design studio desk area with swatches and monitors",
  "a classroom art sink area with supplies on shelves",
  "a library computer station with privacy dividers",
  "a campus common area with bulletin boards behind the subject",
  "a podcast studio corner with acoustic foam and desk equipment",
  "a small startup office kitchen with stools and plants",
  "a print shop counter with paper samples behind the subject",
  "a quiet coworking lounge with bookcases and table lamps",
  "a boutique clothing rack area with neutral curtains behind it",
  "a sneaker store wall with display shelves behind the subject",
  "a home goods store aisle with lamps and woven baskets",
  "a pharmacy store aisle with skincare shelves nearby",
  "a bookstore checkout counter with stacks of books behind it",
  "a plant shop greenhouse aisle with pots and tags visible",
  "a vintage clothing shop mirror with racks in soft focus",
  "a craft supply store aisle with colorful paper displays",
  "a camera store counter with lenses in glass cases",
  "a furniture showroom corner with sofas and side tables",
  "a toy store aisle with bright shelves in the background",
  "a beauty supply store aisle with product displays nearby",
  "a record shop listening station with headphones nearby",
  "a mall corridor outside a department store entrance",
  "a jewelry counter with velvet trays and soft lighting",
  "a wooded park trailhead with maps and trees behind the subject",
  "a public garden greenhouse exterior with glass panels",
  "a quiet botanical garden path with stone borders",
  "a mountain lodge deck with pine trees in the background",
  "a neighborhood dog park fence with grass beyond it",
  "a city park rose garden with trellises behind the subject",
  "a forest boardwalk with mossy trees on both sides",
  "a desert botanical garden with cacti and gravel paths",
  "a lakeside picnic area with trees and open grass",
  "a hillside overlook with a valley in the distance",
  "a vineyard row with soft hills in the background",
  "a community garden plot with raised beds nearby",
  "a nature center porch with trail signs behind the subject",
  "a wildflower meadow edge with a narrow path nearby",
  "a shaded riverside trail with benches and railings",
  "a quiet canal walkway with brick buildings nearby",
  "a lake dock with small boats tied along the side",
  "a rocky shoreline overlook with waves in the distance",
  "a beach volleyball court with nets and sand behind the subject",
  "a marina fuel dock with ropes and signs in soft focus",
  "a riverside cafe deck with water beyond the railing",
  "a public pool lounge area with umbrellas behind the subject",
  "a ferry upper deck with railings and open water behind it",
  "a kayak rental rack beside a calm lake",
  "a waterfall viewing platform with mist in the background",
  "a canal bridge with moored boats behind the subject",
  "a seaside promenade with benches and ocean railings",
  "a lake cabin dock with pine trees behind it",
  "a harbor fish market exterior with boats in the distance",
  "a beach shower station with tile and palm shadows",
  "a gym weight room with dumbbell racks behind the subject",
  "a boxing gym corner with heavy bags in the background",
  "an indoor climbing gym wall with colored holds",
  "a yoga studio with wood floors and rolled mats",
  "a pilates studio with reformer machines behind the subject",
  "a running track beside empty bleachers",
  "a soccer field sideline with goal posts in the distance",
  "a baseball dugout area with benches behind the subject",
  "a skatepark bowl with concrete ramps nearby",
  "a cycling studio with stationary bikes in rows",
  "a locker room bench area with cubbies behind the subject",
  "an indoor pool viewing area with lane ropes in the background",
  "a golf driving range bay with green turf behind it",
  "a martial arts studio with padded floors and wall mirrors",
  "a neighborhood recreation center gymnasium",
  "a spa reception area with neutral stone and soft lighting",
  "a nail salon station with polish shelves behind the subject",
  "a makeup studio vanity with bulb lights and brushes nearby",
  "a skincare treatment room with clean shelves and towels",
  "a hair salon styling station with mirrors and product shelves",
  "a barber shop chair area with tiled floors",
  "a wellness studio lounge with plants and woven chairs",
  "a perfume counter with glass bottles in soft focus",
  "a brow studio mirror area with small tools nearby",
  "a facial spa hallway with warm sconces and quiet decor",
  "a boutique fitting room mirror with soft curtain panels",
  "a dressing table with jewelry trays and a small mirror",
  "a salon shampoo station with black chairs and tile walls",
  "a cosmetics store display wall with clean lighting",
  "a robe and towel shelf inside a spa changing area",
  "a ceramics studio shelf wall with unfinished clay pieces",
  "a photography studio backdrop corner with light stands nearby",
  "a theater lobby with velvet ropes and framed posters",
  "a black box theater stage edge with simple lights behind it",
  "a museum sculpture gallery with polished floors",
  "a community art classroom with easels and paint jars",
  "a film screening room entrance with dark walls",
  "a local history museum hallway with display cases",
  "a comic book shop aisle with colorful covers behind the subject",
  "a stationery shop wall with cards and paper goods",
  "a small independent cinema ticket counter",
  "a mural courtyard with painted walls on every side",
  "a pottery wheel area with clay tools nearby",
  "a photography darkroom counter with trays and red lights",
  "an illustration studio desk with pens and paper behind the subject",
  "a jazz club entrance with low warm lighting",
  "a karaoke room with padded walls and colored lights",
  "a small music venue stage with amps in the background",
  "a piano lounge corner with a grand piano nearby",
  "a festival entrance gate with banners behind the subject",
  "a banquet hall corner with round tables and linen cloths",
  "a wedding reception lobby with floral arrangements nearby",
  "a party rental showroom with folded chairs and decor",
  "a community center event room with simple decorations",
  "a backstage hallway with road cases and cables nearby",
  "a comedy club lobby with brick walls and small posters",
  "a dance floor edge with soft colored lighting",
  "an outdoor amphitheater seating area before a show",
  "a gallery opening reception room with people blurred behind",
  "a hardware store lumber aisle with stacked boards behind the subject",
  "a paint store color wall with swatches in the background",
  "a garage workbench with tools hung neatly behind it",
  "a garden center potting bench with soil bags nearby",
  "a workshop corner with clamps and shelves behind the subject",
  "a tile showroom wall with sample boards behind it",
  "a lighting showroom aisle with pendant lamps overhead",
  "a home improvement store tool aisle with pegboard displays",
  "a maker space table with safety glasses and tools nearby",
  "a bicycle repair station with wheels and tools behind it",
  "a sewing studio cutting table with fabric bolts nearby",
  "a framing shop counter with mat boards behind the subject",
  "a plant nursery checkout area with potting supplies nearby",
  "a woodworking class bench with sanded boards in the background",
  "a craft workshop shelf with glue, tape, and paper supplies",
  "a snowy town square with warm storefront windows behind the subject",
  "an ice rink boardside area with skates and benches nearby",
  "a ski rental shop wall with helmets and boots behind the subject",
  "a winter cabin entryway with coats and boots nearby",
  "a holiday market stall with lights and ornaments in the background",
  "a fireplace lounge with stacked wood and soft chairs",
  "a snowy overlook with evergreen trees behind the subject",
  "a ski lift waiting area with resort signs nearby",
  "a cozy cafe window with frost outside",
  "a heated patio with blankets folded over chairs",
  "a winter train platform with snow along the tracks",
  "a mountain village sidewalk with snowbanks and shop lights",
  "a holiday tree lot with rows of evergreens behind the subject",
  "a winter park path with bare trees and benches",
  "a lodge gear room with skis and poles arranged behind it",
  "a boutique hotel lobby with velvet chairs and plants",
  "a hotel rooftop pool lounge with skyline views",
  "a resort breakfast room with buffet counters behind the subject",
  "a motel exterior corridor with numbered doors in the background",
  "a bed and breakfast porch with rocking chairs nearby",
  "a vacation rental living room with coastal decor",
  "a hostel common room with travel posters and lockers",
  "a hotel business center with printers and desk chairs",
  "a resort spa hallway with stone tile and soft light",
  "a cruise ship deck with railings and deck chairs",
  "a hotel conference foyer with registration tables nearby",
  "a train sleeper cabin with compact bunks behind the subject",
  "a mountain lodge dining room with wood beams overhead",
  "a beach resort walkway with palms and lanterns nearby",
  "a campground welcome kiosk with maps and signs behind it",
  "a textile studio wall with bolts of fabric behind the subject",
  "a jewelry-making bench with pliers and trays nearby",
  "a printmaking studio table with rollers and ink behind it",
  "a candle-making station with jars and wax supplies",
  "a leatherworking bench with tools and hides nearby",
  "a floral design studio with buckets of stems behind the subject",
  "a calligraphy desk with ink bottles and paper samples",
  "a model-building table with tiny tools and parts nearby",
  "a quilting studio shelf with folded fabric stacks",
  "a stained glass workshop with colored sheets in the background",
  "a soap-making counter with molds and oils nearby",
  "a knitting shop table with yarn baskets behind the subject",
  "a screen printing table with blank shirts nearby",
  "a woodworking hobby room with small hand tools behind it",
  "a classroom craft station with glue sticks and paper scraps nearby",
  "a community center lobby with bulletin boards behind the subject",
  "a public library children's area with colorful shelves nearby",
  "a neighborhood playground bench with climbing structures behind it",
  "a school hallway with lockers and posters in the background",
  "a local volunteer pantry with organized shelves behind the subject",
  "a town hall meeting room with folding chairs nearby",
  "a church basement event space with simple tables behind it",
  "a senior center lounge with board games and armchairs nearby",
  "a recreation center front desk with schedules behind the subject",
  "a community pool entrance with signs and shade structures nearby",
  "a neighborhood clubhouse kitchen with serving counters behind it",
  "a campus club room with couches and flyers in the background",
  "a public notice board area beside a park path",
  "a school gym lobby with trophy cases behind the subject",
  "a local arts center hallway with class posters nearby",
  "a creator studio corner with tripods and softbox lights",
  "a podcast recording desk with microphones and foam panels",
  "a streaming setup wall with shelves and LED accents",
  "a content desk with camera gear and a laptop behind the subject",
  "a product photography table with seamless paper in the background",
  "a home office shelf with creator equipment and storage boxes",
  "a small editing suite with monitors and speakers nearby",
  "a video studio cyclorama wall with light stands behind it",
  "a tech repair counter with small tools and devices nearby",
  "a phone accessory kiosk with cases and cables in the background",
  "a gaming lounge desk row with monitors behind the subject",
  "a maker lab electronics bench with components nearby",
  "a digital classroom media desk with cameras and tablets",
  "a live shopping studio corner with product shelves behind it",
  "a photo booth setup with curtain backdrop and prop shelves",
  "an apple orchard row with wooden crates behind the subject",
  "a pumpkin patch entrance with hay bales and signs nearby",
  "a roadside farm stand with baskets of produce behind it",
  "a sunflower field edge with a dirt path nearby",
  "a lavender farm row with low purple plants in the background",
  "a berry picking field with baskets and rows behind the subject",
  "a barn exterior with weathered wood and open fields beyond it",
  "a greenhouse nursery aisle with seedling trays nearby",
  "a vineyard tasting patio with vines in the distance",
  "a country road pullout with fences and trees behind the subject",
  "a stable tack room with saddles and hooks nearby",
  "a farm market cheese counter with chalkboard signs behind it",
  "a cider mill porch with barrels and crates nearby",
  "a rural flower farm stand with buckets of blooms behind it",
  "a small-town main street with brick storefronts in the background",
  "a pharmacy waiting area with simple chairs and product shelves nearby",
  "a post office lobby with mailboxes and service counters behind it",
  "a bank lobby with teller windows in soft focus",
  "a clinic reception area with neutral chairs and plants nearby",
  "a dental office waiting room with magazines and clean lighting",
  "a veterinary clinic lobby with pet posters behind the subject",
  "a dry cleaner counter with garment bags behind it",
  "a tailor shop fitting area with mirrors and fabric samples",
  "a car wash waiting area with large windows and signs nearby",
  "a library service desk with return bins behind the subject",
  "a copy shop counter with paper reams and printers nearby",
  "a shipping store packing table with boxes and tape behind it",
  "a municipal service office lobby with queue barriers nearby",
  "a phone repair shop counter with device displays behind the subject",
  "a travel agency desk area with destination posters in the background",
  "a community college registration office with brochures and desks nearby",
] as const;

const avatarGenerationLocationMoods = [
  "with natural phone-camera framing and mild background blur",
  "with warm overhead lights and relaxed background activity",
  "with soft side light, natural shadows, and candid framing",
  "with muted colors, realistic reflections, and casual composition",
  "with clean available light and a handheld UGC photo feel",
] as const;

function getCategoriesFromText(text: string): AvatarScenarioCategory[] {
  const categories = new Set<AvatarScenarioCategory>();

  if (
    /\b(apartment|bed|cabin|home|hotel room|kitchen|laundromat|rental house|studio apartment)\b/i.test(
      text,
    )
  ) {
    categories.add("home");
  }

  if (/\b(bakery|cafe|coffee|diner|food truck|grocery|kitchen|market)\b/i.test(text)) {
    categories.add("food");
  }

  if (/\b(market|mall|store|shop|shopping|bakery|record shop)\b/i.test(text)) {
    categories.add("shopping");
  }

  if (/\b(airport|airplane|bus stop|car|ferry|hotel|rideshare|station|subway|train)\b/i.test(text)) {
    categories.add("transit");
    categories.add("travel");
  }

  if (/\b(convention|coworking|meeting|office)\b/i.test(text)) {
    categories.add("work");
  }

  if (/\b(salon|mirror|skincare|makeup)\b/i.test(text)) {
    categories.add("beauty");
  }

  if (/\b(basketball|bike|bowling|court|dance studio|gym|locker room|pool|stadium|tennis)\b/i.test(text)) {
    categories.add("fitness");
    categories.add("sports");
  }

  if (/\b(beach|boardwalk|botanical|camp|coastal|desert|garden|hiking|lake|marina|mountain|park|path|pier|river|trail|water)\b/i.test(text)) {
    categories.add("outdoor");
  }

  if (/\b(coastal|ferry|lake|marina|ocean|pier|pool|river|water)\b/i.test(text)) {
    categories.add("water");
  }

  if (/\b(ski|snow|snowy|winter)\b/i.test(text)) {
    categories.add("winter");
  }

  if (/\b(art gallery|bookstore|library|museum|record shop|theater)\b/i.test(text)) {
    categories.add("arts");
  }

  if (/\b(concert|event|movie theater|music venue|stadium)\b/i.test(text)) {
    categories.add("event");
  }

  if (/\b(music venue|record shop|concert)\b/i.test(text)) {
    categories.add("music");
  }

  if (/\b(home improvement|moving boxes|tool|workshop)\b/i.test(text)) {
    categories.add("diy");
  }

  return [...categories];
}

export function getAvatarGenerationLocationCategories(text: string) {
  return getCategoriesFromText(text);
}

export const avatarGenerationLocationOptions =
  avatarGenerationLocationSettings.flatMap((setting) =>
    avatarGenerationLocationMoods.map((mood) => {
      const description = `${setting} ${mood}`;

      return {
        categories: getCategoriesFromText(description),
        description,
      };
    }),
  );

export const avatarGenerationLocations = avatarGenerationLocationOptions.map(
  (location) => location.description,
);
