import type { AvatarScenarioCategory } from "@/lib/clipstitchr/types/AvatarScenarioCategory";

export const avatarGenerationPoseActions = [
  "standing naturally and looking toward the camera",
  "holding the camera at arm's length for a casual selfie",
  "walking forward with a relaxed candid posture",
  "leaning slightly on a counter",
  "sitting casually with shoulders relaxed",
  "turning slightly toward the camera mid-conversation",
  "gesturing lightly with one hand",
  "looking off camera in a natural candid moment",
  "standing with one hand at their side",
  "holding a phone loosely while facing the camera",
  "adjusting their jacket collar",
  "holding a reusable cup",
  "checking their phone",
  "resting one elbow on a table while leaning slightly forward",
  "walking past the camera with a candid side glance",
  "standing with arms loosely crossed",
  "brushing hair away from their face",
  "sitting sideways on a chair and turning toward the camera",
  "holding sunglasses in one hand",
  "laughing mid-step",
  "leaning against a wall with one foot slightly forward",
  "holding a tote bag strap",
  "turning back over one shoulder while walking away",
  "raising one hand in a small casual wave",
  "standing with hands in jacket pockets",
  "writing in a small notebook",
  "writing on a sticky note",
  "writing a reminder on a whiteboard",
  "writing in a planner at a table",
  "writing a postcard",
  "writing in a travel journal",
  "writing on a clipboard",
  "typing on a laptop at a cafe table",
  "typing on a tablet with a stylus",
  "typing on a phone with both thumbs",
  "reading a paperback book",
  "reading an e-reader",
  "reading a menu",
  "reading a museum wall label",
  "reading a transit map",
  "reading a recipe card",
  "flipping through a magazine",
  "looking over a printed schedule",
  "highlighting a page in a notebook",
  "sketching a quick idea in a sketchbook",
  "drawing a small doodle on paper",
  "painting on a small canvas",
  "holding a paintbrush near a palette",
  "arranging colored pencils on a table",
  "taking a photo of a sketchbook page",
  "holding a camera up for a casual photo",
  "reviewing a photo on a camera screen",
  "framing a shot with both hands",
  "recording a quick voice note on a phone",
  "holding a small microphone for a casual recording",
  "applying makeup in a compact mirror",
  "applying lipstick in a mirror",
  "applying mascara with one hand",
  "blending foundation with a sponge",
  "brushing eyebrows with a small spoolie",
  "checking makeup in a handheld mirror",
  "putting on lip balm",
  "applying sunscreen to one cheek",
  "applying moisturizer to their hands",
  "using a face roller",
  "adjusting an earring",
  "putting on a necklace",
  "fastening a watch strap",
  "adjusting a bracelet",
  "fixing a shirt cuff",
  "tying a scarf loosely",
  "putting on sunglasses",
  "taking sunglasses off",
  "checking their reflection in a mirror",
  "fixing their hair in a mirror",
  "tying their hair back",
  "letting their hair down",
  "clipping hair back with one hand",
  "brushing lint from their sleeve",
  "rolling up their sleeves",
  "zipping up a jacket",
  "buttoning a coat",
  "tying a shoelace",
  "adjusting a backpack strap",
  "packing a tote bag",
  "unpacking a small carry-on bag",
  "placing sunglasses into a bag",
  "searching for keys in a bag",
  "holding keys while reaching toward a door",
  "opening an apartment door",
  "locking a door behind them",
  "checking a mailbox",
  "holding a small stack of mail",
  "carrying a laundry basket",
  "folding a clean towel",
  "hanging a jacket on a hook",
  "watering a houseplant",
  "trimming a houseplant leaf with small shears",
  "dusting a shelf with a cloth",
  "wiping a kitchen counter",
  "loading a dishwasher",
  "putting groceries into a cabinet",
  "arranging flowers in a vase",
  "lighting a candle with a long lighter",
  "straightening pillows on a couch",
  "making a bed",
  "setting a small dining table",
  "pouring coffee into a mug",
  "pouring tea from a kettle",
  "stirring a drink with a straw",
  "holding an iced coffee",
  "holding a smoothie cup",
  "holding a water bottle after a walk",
  "sipping from a reusable bottle",
  "opening a takeout container",
  "holding a small bowl of snacks",
  "breaking apart a pastry",
  "spreading jam on toast",
  "tossing a salad in a bowl",
  "stirring soup in a pot",
  "mixing ingredients in a bowl",
  "rolling out dough on a counter",
  "sprinkling herbs over a plate",
  "checking food in an oven",
  "placing fruit into a canvas bag",
  "holding a basket of produce",
  "selecting apples at a market stand",
  "smelling a bouquet of flowers",
  "holding a shopping basket",
  "checking a grocery list on a phone",
  "scanning a shelf while shopping",
  "comparing two small product boxes",
  "placing an item into a tote bag",
  "carrying paper shopping bags",
  "holding a receipt and phone",
  "tapping a payment terminal",
  "standing in line while looking at a phone",
  "walking with a rolling suitcase",
  "lifting a small suitcase handle",
  "placing a carry-on beside their feet",
  "checking a boarding pass on a phone",
  "looking up at a departure board",
  "putting earbuds in",
  "taking earbuds out",
  "adjusting over-ear headphones",
  "listening to music with one hand on headphones",
  "holding a subway pole",
  "checking a transit card",
  "stepping off a curb",
  "waiting at a crosswalk",
  "waving for a rideshare",
  "opening a car door",
  "buckling a seatbelt in a parked car",
  "checking a map on a phone",
  "pointing toward a street sign",
  "holding a city map",
  "walking while carrying a takeaway coffee",
  "walking while reading a phone notification",
  "walking a bike beside them",
  "unlocking a bike",
  "putting on a bike helmet",
  "leaning on bicycle handlebars",
  "jumping rope",
  "stretching one arm across their chest",
  "touching toes in a warm-up stretch",
  "doing a standing quad stretch",
  "holding a yoga mat under one arm",
  "rolling out a yoga mat",
  "sitting cross-legged on a yoga mat",
  "holding a plank pose",
  "doing a side lunge stretch",
  "tying running shoes before a workout",
  "checking a fitness watch",
  "jogging in place",
  "doing jumping jacks",
  "doing high knees",
  "holding a pair of light dumbbells",
  "doing a bicep curl with light dumbbells",
  "doing a shoulder press with light dumbbells",
  "holding a resistance band",
  "stretching a resistance band",
  "balancing on one foot",
  "dribbling a basketball",
  "holding a basketball at hip height",
  "shooting a basketball",
  "holding a tennis racket",
  "swinging a tennis racket casually",
  "holding a pickleball paddle",
  "tossing a frisbee",
  "catching a frisbee",
  "holding a soccer ball under one arm",
  "kicking a soccer ball lightly",
  "holding a skateboard by their side",
  "standing on a skateboard",
  "carrying roller skates by the laces",
  "adjusting a helmet strap",
  "leaning on a gym railing",
  "taking a post-workout breath",
  "wiping sweat with a towel",
  "standing on a hiking trail with a water bottle",
  "checking a trail map",
  "holding binoculars",
  "looking through binoculars",
  "taking a photo of scenery",
  "holding a small picnic blanket",
  "unfolding a picnic blanket",
  "sitting on a blanket in a park",
  "throwing a small paper plane",
  "blowing bubbles",
  "flying a small kite",
  "holding a beach towel",
  "adjusting a sun hat",
  "brushing sand from a shoe",
  "holding seashells in one hand",
  "leaning on a boardwalk railing",
  "splashing water lightly with one foot",
  "holding an umbrella",
  "closing an umbrella",
  "shaking rain from a jacket sleeve",
  "pulling up a hood",
  "warming hands around a hot drink",
  "rubbing hands together in cold weather",
  "adjusting a beanie",
  "pulling gloves on",
  "holding a scarf in the wind",
  "catching a falling leaf",
  "holding a small pumpkin",
  "decorating a small holiday tree",
  "wrapping a small gift",
  "tying ribbon around a gift box",
  "holding a birthday cupcake",
  "lighting a small birthday candle",
  "holding balloons by their strings",
  "tossing confetti from one hand",
  "clapping lightly",
  "giving a thumbs-up",
  "making a peace sign",
  "pointing at themselves playfully",
  "pointing toward the camera",
  "covering a laugh with one hand",
  "resting chin on one hand",
  "resting both hands on a railing",
  "sitting on steps while holding a drink",
  "perching on a stool",
  "turning in a swivel chair",
  "leaning back in an office chair",
  "standing at a standing desk",
  "placing a laptop into a bag",
  "opening a laptop",
  "closing a laptop",
  "presenting something on a tablet",
  "holding a stack of folders",
  "placing a folder on a desk",
  "organizing sticky notes on a wall",
  "pinning a note to a corkboard",
  "checking a wall calendar",
  "holding a pen near their chin",
  "twirling a pen in one hand",
  "using a calculator",
  "sorting receipts on a table",
  "placing a book back on a shelf",
  "pulling a book from a shelf",
  "carrying a small stack of books",
  "using a library checkout kiosk",
  "listening during a conversation",
  "speaking mid-sentence with one hand raised",
  "nodding as if agreeing",
  "shrugging playfully",
  "looking surprised in a candid moment",
  "reacting to something on a phone",
  "showing a phone screen to the camera",
  "taking a mirror selfie with a phone partly visible",
  "holding a phone on speaker mode",
  "recording a selfie video",
  "setting a phone on a mini tripod",
  "adjusting a small tripod",
  "holding a ring light remote",
  "clipping on a tiny microphone",
  "checking lighting near a window",
  "pulling a curtain open",
  "closing blinds halfway",
  "opening a window",
  "leaning out slightly from a balcony doorway",
  "sitting on a windowsill",
  "looking through a shop window",
  "pressing an elevator button",
  "holding an elevator door open",
  "scanning a keycard",
  "opening a locker",
  "placing a bag into a locker",
  "lacing up hiking boots",
  "putting on a baseball cap",
  "adjusting a baseball cap brim",
  "holding a helmet at their side",
  "putting a reusable straw into a drink",
  "opening a sparkling water can",
  "peeling an orange",
  "holding chopsticks over a bowl",
  "using a fork to take a bite",
  "holding a slice of pizza",
  "holding an ice cream cone",
  "catching melting ice cream with a napkin",
  "cutting into a pancake with a fork",
  "pouring cereal into a bowl",
  "shaking a salad container",
  "holding a small tray at a cafe",
  "carrying two coffee cups",
  "offering a coffee cup toward the camera",
  "opening a bakery box",
  "placing cookies on a plate",
  "decorating a cupcake",
  "kneading dough on a counter",
  "washing produce in a sink",
  "drying a plate with a towel",
  "putting on an apron",
  "taking an apron off",
  "arranging place settings",
  "pulling a chair out from a table",
  "sitting down at a table",
  "standing up from a chair",
  "leaning across a table to reach something",
  "passing a small dish across a table",
  "opening a notebook at a cafe",
  "turning a page in a planner",
  "checking off an item on a list",
  "holding a pen over a crossword puzzle",
  "playing a board game piece",
  "holding playing cards",
  "moving a chess piece",
  "stacking small game tiles",
  "holding a puzzle piece",
  "assembling a small puzzle",
  "threading a needle",
  "knitting with yarn",
  "crocheting with yarn",
  "sewing a button",
  "folding origami paper",
  "cutting paper with craft scissors",
  "gluing a photo into a scrapbook",
  "placing a sticker on a notebook",
  "arranging photos on a table",
  "holding a record sleeve",
  "placing a vinyl record on a turntable",
  "adjusting a turntable needle",
  "holding a guitar pick",
  "strumming an acoustic guitar",
  "holding drumsticks",
  "tapping a rhythm on a table",
  "playing a small keyboard",
  "holding a ukulele",
  "singing along softly",
  "dancing with a small shoulder movement",
  "doing a quick spin",
  "stepping side to side to music",
  "clapping along to a beat",
  "standing at a microphone stand",
  "holding sheet music",
  "turning a page of sheet music",
  "placing flowers into a tote",
  "tying a bouquet with twine",
  "holding a potted plant",
  "repotting a small plant",
  "scooping soil into a planter",
  "spraying plant leaves with a mister",
  "standing with gardening gloves",
  "pulling weeds from a planter",
  "holding seed packets",
  "placing herbs on a windowsill",
  "taking a photo of flowers",
  "smelling fresh herbs",
  "carrying a folded camping chair",
  "setting up a small folding chair",
  "holding a flashlight",
  "checking a lantern",
  "rolling up a sleeping bag",
  "zipping a tent doorway",
  "holding a trail snack",
  "tightening a backpack strap",
  "standing with trekking poles",
  "checking a compass",
  "looking at a paper trail guide",
  "crossing a small footbridge",
  "stepping over a puddle",
  "balancing on stepping stones",
  "walking through tall grass",
  "holding a small towel after swimming",
  "putting goggles on their forehead",
  "carrying a swim bag",
  "standing near a pool ladder",
  "leaning on a fence",
  "sitting on a bench while tying shoes",
  "stretching calves against a wall",
  "doing a light squat",
  "holding a medicine ball",
  "balancing a foam roller under one arm",
  "rolling shoulders back after stretching",
  "checking posture in a mirror",
  "posing with one hand on a hip",
  "standing in a three-quarter stance",
  "turning their body slightly away from camera",
  "looking down and smiling at something in hand",
  "looking up from a book",
  "shielding eyes from bright light",
  "walking under an awning",
  "peeking around a doorway",
  "stepping through an open doorway",
  "holding a door handle",
  "waiting with hands clasped loosely",
  "standing with one shoulder against a wall",
  "sitting with ankles crossed",
  "sitting with hands folded loosely",
  "sitting with one arm over the back of a chair",
  "standing with one knee slightly bent",
  "walking while turning toward the camera",
  "walking away while glancing back",
  "pausing mid-step on a sidewalk",
  "standing beside luggage while checking a phone",
  "holding a paper ticket",
  "placing a ticket into a pocket",
  "scanning a QR code on a poster",
  "looking at a museum exhibit",
  "standing beside a sculpture",
  "holding an audio guide device",
  "looking through a clothing rack",
  "holding up a jacket on a hanger",
  "trying on a hat",
  "checking a shoe fit",
  "holding a fitting room tag",
  "carrying a garment bag",
  "placing folded clothes into a drawer",
  "folding a sweater",
  "pulling a hoodie over their head",
  "taking off a jacket",
  "tucking hair behind one ear",
  "checking an earring in a mirror",
  "holding a compact powder case",
  "brushing blush onto one cheek",
  "applying eyeliner carefully",
  "holding a makeup brush set",
  "opening a skincare jar",
  "massaging hand cream into one hand",
  "placing a hair clip into a bag",
  "holding a comb",
  "brushing hair with a paddle brush",
  "spraying fragrance onto one wrist",
  "adjusting a collar before leaving",
  "holding a lint roller",
  "steaming a shirt with a handheld steamer",
  "placing shoes beside a door",
  "holding a small bouquet behind their back",
  "offering flowers toward the camera",
  "opening a greeting card",
  "holding a handwritten sign with no visible text",
  "setting a timer on a phone",
  "swiping through photos on a phone",
  "scanning a document with a phone camera",
  "balancing a phone against a mug for a quick recording",
  "plugging a charger into a phone",
  "untangling charging cables",
  "placing a laptop charger into an outlet",
  "cleaning a laptop screen with a cloth",
  "arranging a keyboard and mouse on a desk",
  "adjusting a monitor height",
  "putting a tablet into a sleeve",
  "opening a video call on a laptop",
  "waving at a laptop screen during a call",
  "taking notes during a video call",
  "pointing at a laptop screen",
  "placing earbuds into a charging case",
  "checking a notification on a smartwatch",
  "changing a smartwatch band",
  "tapping through a playlist on a phone",
  "holding a portable battery pack",
  "plugging in a small desk lamp",
  "adjusting a desk lamp angle",
  "organizing cables with a small tie",
  "placing a memory card into a camera",
  "attaching a camera lens cap",
  "wiping a camera lens",
  "setting a camera on a tabletop tripod",
  "checking an external hard drive",
  "labeling a storage box",
  "placing a tablet on a stand",
  "carrying a reusable grocery bag over one shoulder",
  "placing folded towels into a cabinet",
  "measuring a window with a tape measure",
  "hanging a small picture frame",
  "aligning a picture frame on a wall",
  "tightening a loose drawer handle",
  "replacing batteries in a remote",
  "sorting recycling into a bin",
  "flattening a cardboard box",
  "carrying a small toolbox",
  "opening a toolbox on a table",
  "holding a measuring tape at waist height",
  "wiping a mirror with a cloth",
  "polishing a faucet with a towel",
  "organizing spices on a shelf",
  "filling a soap dispenser",
  "replacing a light bulb in a table lamp",
  "placing shoes on a rack",
  "arranging books by color on a shelf",
  "sliding a storage bin under a bed",
  "shaking out a small rug",
  "fluffing a blanket on a couch",
  "carrying a folded blanket",
  "placing a vase on a shelf",
  "opening a window shade",
  "hanging clothes on a drying rack",
  "clipping a shirt onto a hanger",
  "sorting socks on a bed",
  "placing coins into a jar",
  "checking a household checklist on paper",
  "slicing a lemon on a cutting board",
  "squeezing lemon into a glass",
  "grating cheese over a plate",
  "cracking an egg into a bowl",
  "whisking eggs in a bowl",
  "flipping a pancake in a pan",
  "pouring batter into a pan",
  "measuring flour with a scoop",
  "sprinkling powdered sugar over pastries",
  "placing berries on top of yogurt",
  "scooping yogurt into a bowl",
  "pouring granola into a bowl",
  "blending a smoothie at a counter",
  "carrying a blender cup",
  "shaking a protein shaker",
  "peeling a banana",
  "cutting an avocado",
  "spreading avocado on toast",
  "tossing pasta in a bowl",
  "twirling pasta on a fork",
  "pouring sauce into a pan",
  "chopping herbs on a cutting board",
  "washing a cutting board",
  "drying lettuce in a salad spinner",
  "packing lunch into a container",
  "opening a lunch container",
  "wrapping a sandwich in paper",
  "pouring sparkling water over ice",
  "placing ice cubes into a glass",
  "stirring matcha in a bowl",
  "doing a wall sit",
  "stepping onto a low exercise box",
  "stepping off a low exercise box",
  "holding a foam yoga block",
  "reaching overhead in a stretch",
  "doing arm circles",
  "doing a gentle side bend",
  "doing a calf raise",
  "doing a glute bridge on a mat",
  "doing a seated twist stretch",
  "holding a jump rope handle before starting",
  "coiling a jump rope",
  "wiping down gym equipment with a towel",
  "clipping a water bottle to a backpack",
  "adjusting a treadmill speed button",
  "standing beside an exercise bike",
  "adjusting an exercise bike seat",
  "holding a kettlebell by the handle",
  "doing a kettlebell deadlift setup",
  "holding a medicine ball at chest height",
  "tossing a medicine ball lightly upward",
  "stretching a hamstring with a strap",
  "doing quick footwork drills",
  "balancing on a wobble board",
  "stepping through an agility ladder",
  "stretching wrists before a workout",
  "shaking out arms after exercise",
  "checking shoelaces after a run",
  "leaning forward with hands on knees after jogging",
  "placing a passport into a travel wallet",
  "opening a travel wallet",
  "weighing a suitcase with a luggage scale",
  "attaching a luggage tag",
  "compressing clothes into a packing cube",
  "placing a hat into a suitcase",
  "rolling a shirt for packing",
  "checking a hotel keycard",
  "opening hotel room curtains",
  "looking over a hotel room map",
  "carrying a folded city guide",
  "standing beside a rental scooter",
  "scanning a scooter rental code",
  "putting a helmet onto a scooter handlebar",
  "checking tire pressure on a bike",
  "filling a bike tire with a pump",
  "adjusting a bike seat height",
  "fastening a bike lock around a rack",
  "placing a picnic basket on a table",
  "opening a sunscreen bottle",
  "shaking sand from a towel",
  "folding a beach chair",
  "holding a sun visor",
  "adjusting a backpack chest strap",
  "pouring water into a reusable bottle",
  "setting a bottle on a trail marker",
  "unfolding a paper map",
  "tracing a route on a paper map",
  "holding a travel pillow",
  "placing a passport back into a bag",
  "applying nail polish",
  "checking nail polish on one hand",
  "filing nails with an emery board",
  "buffing nails with a small buffer",
  "applying cuticle oil",
  "placing hair rollers in a pouch",
  "using a hair dryer at a mirror",
  "smoothing hair with a flat iron",
  "curling hair with a curling wand",
  "applying dry shampoo",
  "braiding a small section of hair",
  "fastening a hair tie around a ponytail",
  "trying on a necklace in a mirror",
  "holding two earrings to compare them",
  "arranging rings on a small tray",
  "pinning a brooch to a jacket",
  "adjusting a tie knot",
  "tightening a belt",
  "choosing between two scarves",
  "folding a scarf into a bag",
  "checking sleeve length in a mirror",
  "turning to check the back of an outfit",
  "holding a garment steamer near a jacket",
  "brushing suede shoes",
  "polishing leather shoes with a cloth",
  "placing a hat on a shelf",
  "trying on a watch at a counter",
  "adjusting a handbag strap",
  "matching socks from a drawer",
  "lint-brushing trousers",
  "pressing a rubber stamp onto paper",
  "arranging scrapbook paper",
  "taping a photo into a frame",
  "measuring fabric with a ruler",
  "pinning fabric pieces together",
  "threading beads onto a string",
  "tying a knot in a friendship bracelet",
  "arranging beads by color",
  "painting a small ceramic cup",
  "wiping glaze from a ceramic piece",
  "shaping clay on a small mat",
  "pressing leaves into a journal",
  "arranging dried flowers on paper",
  "winding yarn into a ball",
  "untangling yarn",
  "holding an embroidery hoop",
  "stitching fabric in an embroidery hoop",
  "sorting buttons in a small dish",
  "cutting fabric with scissors",
  "sharpening a pencil",
  "mixing watercolor paint in a palette",
  "rinsing a paintbrush in a cup",
  "setting up an easel",
  "placing a canvas on an easel",
  "folding a zine",
  "stapling pages into a booklet",
  "arranging postcards on a wall",
  "holding a film negative strip",
  "placing a photo into an album",
  "holding a name badge near their chest",
  "clipping a badge onto a lanyard",
  "checking a conference agenda",
  "placing business cards on a table",
  "holding a presentation clicker",
  "standing beside a flip chart",
  "pointing to a blank chart pad",
  "rearranging chairs in a meeting room",
  "carrying a stack of event programs",
  "setting a small sign on a table with no visible text",
  "arranging cups at a refreshment table",
  "placing napkins beside a tray",
  "pinning a small flower to a jacket",
  "opening a party invitation",
  "holding a party favor bag",
  "placing candles on a table",
  "hanging paper decorations",
  "tying a balloon string to a chair",
  "carrying a wrapped gift under one arm",
  "placing a gift on a table",
  "arranging greeting cards on a shelf",
  "holding a blank place card",
  "setting a place card onto a table",
  "raising a glass of sparkling water",
  "toasting with a cup held up",
  "holding a small dessert plate",
  "passing a napkin across a table",
  "standing beside a guestbook",
  "placing a pen beside a guestbook",
  "placing painter's tape along a wall",
  "smoothing painter's tape with fingertips",
  "holding a paint roller tray",
  "rolling paint onto a small wall sample",
  "stirring paint with a wooden stick",
  "opening a can of paint with a paint key",
  "holding a paint swatch card",
  "comparing paint swatches",
  "placing a wallpaper sample on a wall",
  "smoothing wallpaper with a flat tool",
  "tightening a screw with a small screwdriver",
  "assembling a small shelf",
  "holding a shelf bracket",
  "placing a level against a shelf",
  "marking a wall with a pencil",
  "installing a small hook",
  "hanging a plant basket from a hook",
  "replacing a cabinet knob",
  "organizing tools in a drawer",
  "winding an extension cord",
  "plugging in a vacuum cleaner",
  "vacuuming a small rug",
  "emptying a vacuum canister",
  "sweeping a balcony",
  "mopping a kitchen floor",
  "filling a watering can at a sink",
  "carrying a watering can",
  "arranging patio cushions",
  "folding a step stool",
  "standing on a low step stool reaching for a shelf",
  "blowing on a hot drink",
  "opening a window seat tray table",
  "tracing condensation on a window with one finger",
  "opening a puzzle book",
  "filling in a sudoku square",
  "tossing keys onto a table",
  "catching keys in one hand",
  "spinning a keyring around one finger",
  "checking a weather app",
  "holding a folded raincoat",
  "placing a reusable cup into a cupholder",
  "adjusting a car mirror in a parked car",
  "reaching for a dashboard control in a parked car",
  "placing coins into a parking meter",
  "tapping a crosswalk button",
  "holding a folded umbrella by their side",
  "standing under a covered awning",
  "shaking out a picnic blanket",
  "closing a picnic basket",
  "setting up a portable speaker",
  "turning a portable speaker volume knob",
  "opening a sunglasses case",
  "placing a train ticket into a wallet",
  "unfolding a stadium seat cushion",
  "applying a temporary wristband",
  "scanning a wristband at an entrance",
  "holding a small souvenir",
  "wrapping a souvenir in tissue paper",
  "placing a magnet on a refrigerator",
  "taking a photo of a plated meal",
  "placing a bookmark into a book",
  "checking a luggage carousel screen",
  "holding a folded theater program",
] as const;

export const avatarGenerationPoseExpressions = [
  "with a relaxed natural smile",
  "with a calm neutral expression and soft eye contact",
  "with a candid half-smile as if between takes",
  "while glancing slightly past the camera",
  "with bright friendly energy and loose shoulders",
] as const;

function getActionCategories(action: string): AvatarScenarioCategory[] {
  const categories = new Set<AvatarScenarioCategory>();

  if (
    /\b(apartment|bed|blanket|blinds|cabinet|candle|chair|counter|curtain|dishwasher|door|drawer|home|household|laundry|mailbox|mirror|plant|pillow|rug|shelf|sofa|towel|window)\b/i.test(
      action,
    )
  ) {
    categories.add("home");
  }

  if (
    /\b(avocado|bakery|batter|bowl|breakfast|cafe|cereal|coffee|cookie|cup|diner|drink|egg|food|fork|grocery|herbs|ice cream|kettle|kitchen|lemon|lunch|market|mug|pancake|pastry|pizza|produce|recipe|salad|sandwich|snack|soup|tea|toast|yogurt)\b/i.test(
      action,
    )
  ) {
    categories.add("food");
  }

  if (
    /\b(bag|basket|checkout|clothing rack|comparing|fitting room|garment|grocery|hanger|product boxes|receipt|shelf|shopping|store)\b/i.test(
      action,
    )
  ) {
    categories.add("shopping");
  }

  if (
    /\b(airport|boarding pass|bus|car|curb|dashboard|departure|elevator|hotel|keycard|luggage|map|parking|passport|rideshare|seatbelt|scooter|suitcase|ticket|train|transit|travel|wallet)\b/i.test(
      action,
    )
  ) {
    categories.add("transit");
    categories.add("travel");
  }

  if (
    /\b(agenda|badge|business cards|calculator|calendar|clipboard|conference|desk|folder|laptop|meeting|monitor|presentation|receipts|standing desk|sticky note|tablet|video call|whiteboard|work)\b/i.test(
      action,
    )
  ) {
    categories.add("work");
  }

  if (
    /\b(apron|beauty|blush|comb|compact|cuticle|earring|eyebrow|eyeliner|face roller|foundation|fragrance|hair|lip|makeup|mascara|mirror|moisturizer|nail|necklace|perfume|powder|skincare|sunscreen)\b/i.test(
      action,
    )
  ) {
    categories.add("beauty");
  }

  if (
    /\b(agility|basketball|bike|dumbbell|exercise|fitness|foam roller|frisbee|gym|jumping|jump rope|kettlebell|medicine ball|pickleball|plank|post-workout|resistance band|run|skateboard|soccer|sport|stretch|tennis|treadmill|workout|yoga|yoga mat|exercise mat)\b/i.test(
      action,
    )
  ) {
    categories.add("fitness");
    categories.add("sports");
  }

  if (
    /\b(beach|binoculars|boardwalk|camp|compass|flowers|garden|hiking|kite|lantern|leaf|outdoor|picnic|plant|puddle|sand|seashell|sleeping bag|sun|trail|trees|umbrella|water)\b/i.test(
      action,
    )
  ) {
    categories.add("outdoor");
  }

  if (
    /\b(beach|goggles|pool|sand|seashell|swim|towel|water)\b/i.test(action)
  ) {
    categories.add("water");
  }

  if (
    /\b(beanie|cold|gloves|hot drink|scarf|snow|winter)\b/i.test(action)
  ) {
    categories.add("winter");
  }

  if (
    /\b(album|art|bead|book|bookstore|camera|canvas|ceramic|craft|drawing|easel|embroidery|gallery|journal|museum|paint|photo|puzzle|record|scrapbook|sketch|vinyl|watercolor|zine)\b/i.test(
      action,
    )
  ) {
    categories.add("arts");
  }

  if (
    /\b(balloon|birthday|candle|confetti|event|gift|guestbook|invitation|party|program|toast|wristband)\b/i.test(
      action,
    )
  ) {
    categories.add("event");
  }

  if (
    /\b(guitar|keyboard|microphone|music|record|sheet music|singing|speaker|turntable|ukulele)\b/i.test(
      action,
    )
  ) {
    categories.add("music");
  }

  if (
    /\b(bracket|cabinet knob|cord|drill|extension cord|hook|level|paint roller|painter|screw|screwdriver|shelf|step stool|tool|wallpaper)\b/i.test(
      action,
    )
  ) {
    categories.add("diy");
  }

  return [...categories];
}

function isUniversalPoseAction(action: string) {
  return /\b(adjusting their jacket|arms loosely crossed|brushing hair|candid side glance|checking their phone|gesturing|hands in jacket pockets|holding a phone|laughing|leaning|looking|raising one hand|sitting|standing|turning|walking)\b/i.test(
    action,
  );
}

export function getAvatarGenerationPoseActionCategories(action: string) {
  return getActionCategories(action);
}

export function getAvatarGenerationPosesForLocationCategories(
  locationCategories: readonly AvatarScenarioCategory[],
) {
  const locationCategorySet = new Set(locationCategories);
  const compatibleActions = avatarGenerationPoseActions.filter((action) => {
    const actionCategories = getActionCategories(action);

    if (!actionCategories.length) {
      return !locationCategories.length || isUniversalPoseAction(action);
    }

    return actionCategories.some((category) => locationCategorySet.has(category));
  });
  const actions = compatibleActions.length
    ? compatibleActions
    : avatarGenerationPoseActions;

  return actions.flatMap((action) =>
    avatarGenerationPoseExpressions.map(
      (expression) => `${action} ${expression}`,
    ),
  );
}

export const avatarGenerationPoses = avatarGenerationPoseActions.flatMap(
  (action) =>
    avatarGenerationPoseExpressions.map((expression) => `${action} ${expression}`),
);
