import type { CliprVoice } from "@/lib/clipstitchr/types/CliprVoice";

const englishUs = "English (US)";
const conversationalCreator =
  "Natural UGC creator delivery, conversational, clear, calm, no sales hype.";

export const cliprVoices: CliprVoice[] = [
  {
    id: "Zephyr (Female)",
    name: "Zephyr",
    description: "Female, clear creator",
    language: englishUs,
    prompt: conversationalCreator,
  },
  {
    id: "Puck (Male)",
    name: "Puck",
    description: "Male, upbeat coach",
    language: englishUs,
    prompt: "Upbeat creator delivery, friendly, crisp, no shouting or hard sell.",
  },
  {
    id: "Charon (Male)",
    name: "Charon",
    description: "Male, steady guide",
    language: englishUs,
    prompt: "Steady explainer delivery, reassuring, plainspoken, no jargon.",
  },
  {
    id: "Kore (Female)",
    name: "Kore",
    description: "Female, polished calm",
    language: englishUs,
    prompt: "Polished creator delivery, calm confidence, measured pacing.",
  },
  {
    id: "Fenrir (Male)",
    name: "Fenrir",
    description: "Male, punchy",
    language: englishUs,
    prompt: "Punchy creator delivery, energetic but controlled, no theatrical hype.",
  },
  {
    id: "Leda (Female)",
    name: "Leda",
    description: "Female, warm",
    language: englishUs,
    prompt: "Warm conversational delivery, easy pacing, clear sentence endings.",
  },
  {
    id: "Orus (Male)",
    name: "Orus",
    description: "Male, direct",
    language: englishUs,
    prompt: "Direct creator delivery, grounded, concise, confident without pressure.",
  },
  {
    id: "Aoede (Female)",
    name: "Aoede",
    description: "Female, instructional",
    language: englishUs,
    prompt: "Helpful instructor delivery, clear steps, friendly expert tone.",
  },
  {
    id: "Callirrhoe (Female)",
    name: "Callirrhoe",
    description: "Female, decisive",
    language: englishUs,
    prompt: "Decisive creator delivery, plain language, no filler.",
  },
  {
    id: "Autonoe (Female)",
    name: "Autonoe",
    description: "Female, casual",
    language: englishUs,
    prompt: conversationalCreator,
  },
  {
    id: "Enceladus (Male)",
    name: "Enceladus",
    description: "Male, grounded",
    language: englishUs,
    prompt: "Grounded creator delivery, relaxed, clear, natural pauses.",
  },
  {
    id: "Iapetus (Male)",
    name: "Iapetus",
    description: "Male, facilitator",
    language: englishUs,
    prompt: "Encouraging facilitator delivery, crisp endings, measured pacing.",
  },
  {
    id: "Umbriel (Male)",
    name: "Umbriel",
    description: "Male, calm",
    language: englishUs,
    prompt: "Calm creator delivery, steady pace, low-pressure clarity.",
  },
  {
    id: "Algenib (Male)",
    name: "Algenib",
    description: "Male, premium",
    language: englishUs,
    prompt: "Premium creator delivery, composed, confident, no hype.",
  },
  {
    id: "Despina (Female)",
    name: "Despina",
    description: "Female, bright",
    language: englishUs,
    prompt: "Bright creator delivery, expressive, friendly, still natural.",
  },
  {
    id: "Erinome (Female)",
    name: "Erinome",
    description: "Female, soft",
    language: englishUs,
    prompt: "Soft conversational delivery, thoughtful, clear, no whispering.",
  },
  {
    id: "Laomedeia (Female)",
    name: "Laomedeia",
    description: "Female, refined",
    language: englishUs,
    prompt: "Refined creator delivery, articulate, measured, relaxed.",
  },
  {
    id: "Achernar (Female)",
    name: "Achernar",
    description: "Female, composed",
    language: englishUs,
    prompt: "Composed creator delivery, direct, natural, concise.",
  },
  {
    id: "Algieba (Male)",
    name: "Algieba",
    description: "Male, confident",
    language: englishUs,
    prompt: "Confident creator delivery, warm, natural, not announcer-like.",
  },
  {
    id: "Schedar (Male)",
    name: "Schedar",
    description: "Male, precise",
    language: englishUs,
    prompt: "Precise explainer delivery, steady cadence, useful and calm.",
  },
  {
    id: "Gacrux (Female)",
    name: "Gacrux",
    description: "Female, practical",
    language: englishUs,
    prompt: "Practical creator delivery, matter-of-fact, clear, conversational.",
  },
  {
    id: "Pulcherrima (Female)",
    name: "Pulcherrima",
    description: "Female, expressive",
    language: englishUs,
    prompt: "Expressive creator delivery, friendly energy, no exaggerated emotion.",
  },
  {
    id: "Achird (Male)",
    name: "Achird",
    description: "Male, casual",
    language: englishUs,
    prompt: "Casual creator delivery, natural pace, clear and relaxed.",
  },
  {
    id: "Zubenelgenubi (Male)",
    name: "Zubenelgenubi",
    description: "Male, measured",
    language: englishUs,
    prompt: "Measured creator delivery, calm confidence, clear consonants.",
  },
  {
    id: "Vindemiatrix (Female)",
    name: "Vindemiatrix",
    description: "Female, grounded",
    language: englishUs,
    prompt: "Grounded creator delivery, thoughtful, concise, no sales pressure.",
  },
  {
    id: "Sadachbia (Male)",
    name: "Sadachbia",
    description: "Male, helpful",
    language: englishUs,
    prompt: "Helpful creator delivery, steady and direct, no filler.",
  },
  {
    id: "Sadaltager (Male)",
    name: "Sadaltager",
    description: "Male, energetic",
    language: englishUs,
    prompt: "Energetic creator delivery, punchy but believable, no shouting.",
  },
  {
    id: "Sulafat (Female)",
    name: "Sulafat",
    description: "Female, neutral",
    language: englishUs,
    prompt: "Neutral creator delivery, clear, natural, evenly paced.",
  },
  {
    id: "Alnilam (Male)",
    name: "Alnilam",
    description: "Male, crisp",
    language: englishUs,
    prompt: "Crisp creator delivery, clear sentence rhythm, friendly confidence.",
  },
  {
    id: "Rasalgethi (Male)",
    name: "Rasalgethi",
    description: "Male, warm",
    language: englishUs,
    prompt: "Warm creator delivery, relaxed and conversational, no hard sell.",
  },
];
