export const CLIPR_SEEDANCE_ASPECT_RATIO = "9:16";

export const CLIPR_SEEDANCE_RESOLUTION = "720p";

export const CLIPR_SEEDANCE_MIN_DURATION_SECONDS = 8;

export const CLIPR_SEEDANCE_MAX_DURATION_SECONDS = 15;

export const CLIPR_SEEDANCE_AUDIO_PADDING_SECONDS = 2;
