import type { CliprVoice } from "@/lib/clipstitchr/types/CliprVoice";

const englishUs = "English (US)";
const conversationalCreator =
  "Natural UGC creator delivery, conversational, clear, calm, no sales hype.";

export const cliprVoices: CliprVoice[] = [
  {
    id: "Rachel",
    name: "Rachel",
    description: "Balanced creator",
    language: englishUs,
    prompt: conversationalCreator,
  },
  {
    id: "Drew",
    name: "Drew",
    description: "Warm narrator",
    language: englishUs,
    prompt: "Warm creator delivery, clear sentence endings, no hard sell.",
  },
  {
    id: "Clyde",
    name: "Clyde",
    description: "Grounded guide",
    language: englishUs,
    prompt: "Grounded explainer delivery, confident, steady, plainspoken.",
  },
  {
    id: "Paul",
    name: "Paul",
    description: "Calm expert",
    language: englishUs,
    prompt: "Calm expert delivery, measured, useful, never announcer-like.",
  },
  {
    id: "Aria",
    name: "Aria",
    description: "Polished creator",
    language: englishUs,
    prompt: "Polished creator delivery, articulate, friendly, concise.",
  },
  {
    id: "Domi",
    name: "Domi",
    description: "Expressive creator",
    language: englishUs,
    prompt: "Expressive creator delivery, friendly energy, still believable.",
  },
  {
    id: "Dave",
    name: "Dave",
    description: "Casual coach",
    language: englishUs,
    prompt: "Casual coach delivery, relaxed, clear, conversational.",
  },
  {
    id: "Roger",
    name: "Roger",
    description: "Direct narrator",
    language: englishUs,
    prompt: "Direct narrator delivery, concise, crisp, confident.",
  },
  {
    id: "Fin",
    name: "Fin",
    description: "Friendly explainer",
    language: englishUs,
    prompt: "Friendly explainer delivery, easy pace, helpful and natural.",
  },
  {
    id: "Sarah",
    name: "Sarah",
    description: "Clear creator",
    language: englishUs,
    prompt: "Clear creator delivery, bright, practical, no exaggerated emotion.",
  },
  {
    id: "James",
    name: "James",
    description: "Confident guide",
    language: englishUs,
    prompt: "Confident guide delivery, warm, concise, not salesy.",
  },
  {
    id: "Jane",
    name: "Jane",
    description: "Helpful narrator",
    language: englishUs,
    prompt: "Helpful narrator delivery, steady, natural, plain language.",
  },
  {
    id: "Juniper",
    name: "Juniper",
    description: "Bright creator",
    language: englishUs,
    prompt: "Bright creator delivery, upbeat but controlled, clear.",
  },
  {
    id: "Arabella",
    name: "Arabella",
    description: "Refined creator",
    language: englishUs,
    prompt: "Refined creator delivery, composed, articulate, relaxed.",
  },
  {
    id: "Hope",
    name: "Hope",
    description: "Warm creator",
    language: englishUs,
    prompt: "Warm conversational delivery, sincere, easy pacing.",
  },
  {
    id: "Bradford",
    name: "Bradford",
    description: "Steady presenter",
    language: englishUs,
    prompt: "Steady presenter delivery, practical, clear, no filler.",
  },
  {
    id: "Reginald",
    name: "Reginald",
    description: "Premium narrator",
    language: englishUs,
    prompt: "Premium narrator delivery, composed, confident, restrained.",
  },
  {
    id: "Gaming",
    name: "Gaming",
    description: "High energy",
    language: englishUs,
    prompt: "High-energy creator delivery, punchy but believable, no shouting.",
  },
  {
    id: "Austin",
    name: "Austin",
    description: "Casual creator",
    language: englishUs,
    prompt: "Casual creator delivery, natural pace, relaxed confidence.",
  },
  {
    id: "Kuon",
    name: "Kuon",
    description: "Measured guide",
    language: englishUs,
    prompt: "Measured guide delivery, calm, precise, useful.",
  },
  {
    id: "Blondie",
    name: "Blondie",
    description: "Social creator",
    language: englishUs,
    prompt: "Social creator delivery, friendly, expressive, direct.",
  },
  {
    id: "Priyanka",
    name: "Priyanka",
    description: "Practical creator",
    language: englishUs,
    prompt: "Practical creator delivery, grounded, clear, conversational.",
  },
  {
    id: "Alexandra",
    name: "Alexandra",
    description: "Confident creator",
    language: englishUs,
    prompt: "Confident creator delivery, warm, articulate, no pressure.",
  },
  {
    id: "Monika",
    name: "Monika",
    description: "Instructional voice",
    language: englishUs,
    prompt: "Instructional creator delivery, helpful, clear steps, friendly.",
  },
  {
    id: "Mark",
    name: "Mark",
    description: "Crisp narrator",
    language: englishUs,
    prompt: "Crisp narrator delivery, steady rhythm, concise and clear.",
  },
  {
    id: "Grimblewood",
    name: "Grimblewood",
    description: "Distinctive narrator",
    language: englishUs,
    prompt: "Distinctive narrator delivery, controlled, clear, not theatrical.",
  },
];
