import type { SwiprBackgroundSeedNiche } from "@/lib/clipstitchr/types/SwiprBackgroundSeedNiche";

export const swiprBackgroundSeedNiches = [
  {
    id: "fitness-training",
    label: "Fitness Training",
    category: "fitness",
    tags: ["gym", "workout", "strength", "training", "athlete"],
    productFit: "fitness programs, gym offers, coaching, activewear, and equipment",
    settings: [
      "rubber gym floor with a squat rack edge, plate storage, and a clean open wall",
      "outdoor calisthenics bars on smooth concrete with open sky and simple park detail",
      "recovery corner with foam roller, folded towel, matte bottle, and negative space",
      "boutique studio mirror wall with stacked mats low in frame and soft reflections",
      "running track lane curve with blurred infield detail and clear space above",
    ],
  },
  {
    id: "yoga-pilates",
    label: "Yoga and Pilates",
    category: "fitness",
    tags: ["yoga", "pilates", "mobility", "mindfulness", "studio"],
    productFit: "yoga studios, pilates classes, wellness programs, mats, and mobility tools",
    settings: [
      "quiet yoga studio floor with rolled mats along one side and a calm blank wall",
      "sunlit pilates reformer room with neutral wall space and soft equipment shapes",
      "outdoor deck beside a woven privacy screen with mat texture and airy daylight",
      "meditation nook with floor cushions, linen curtain, and open wall space",
      "barre studio rail with pale wood floor and gentle window light",
    ],
  },
  {
    id: "beauty-skincare",
    label: "Beauty and Skincare",
    category: "beauty",
    tags: ["beauty", "skincare", "cosmetics", "spa", "self-care"],
    productFit: "skincare, cosmetics, fragrance, beauty tools, and spa offers",
    settings: [
      "bathroom vanity with stone counter, folded towel, soft reflection, and clean wall",
      "spa treatment room with warm linens, side table, and open plaster backdrop",
      "makeup station with mirror bulbs blurred at the edges and empty counter space",
      "clean shelf with glass jars, ceramic tray, and soft tonal background",
      "salon chair corner with neutral wall, subtle mirror edge, and polished floor",
    ],
  },
  {
    id: "hair-salon",
    label: "Hair Salon",
    category: "beauty",
    tags: ["hair", "salon", "styling", "barber", "color"],
    productFit: "salons, stylists, hair products, color services, and booking offers",
    settings: [
      "modern salon station with a chair edge, blurred mirror, and clear wall area",
      "shampoo room with basin detail low in frame and warm neutral wall space",
      "barber counter with combs and tools arranged near the edge without branding",
      "color bar with tidy bowls, folded foils, and softly lit shelving",
      "salon reception corner with textured wall, plant detail, and polished floor",
    ],
  },
  {
    id: "fashion-apparel",
    label: "Fashion Apparel",
    category: "fashion",
    tags: ["fashion", "apparel", "clothing", "style", "wardrobe"],
    productFit: "clothing drops, boutiques, styling services, shoes, and accessories",
    settings: [
      "boutique fitting area with curtain texture, rack edge, and open floor space",
      "studio wardrobe rail with neutral garments blurred along the side",
      "urban sidewalk wall with clean concrete, subtle shadow, and fashion retail feel",
      "minimal dressing room bench with mirror edge and warm overhead lighting",
      "flat studio surface with fabric swatches, hanger detail, and empty center",
    ],
  },
  {
    id: "jewelry-accessories",
    label: "Jewelry and Accessories",
    category: "fashion",
    tags: ["jewelry", "accessories", "luxury", "gift", "boutique"],
    productFit: "jewelry, watches, bags, eyewear, gifting, and boutique accessories",
    settings: [
      "velvet display surface with soft jewelry-case lighting and open top area",
      "marble counter with small tray, silk fabric fold, and elegant negative space",
      "boutique shelf with mirrored edge, warm sparkle, and clean background",
      "gift wrapping desk with ribbon texture, tissue paper, and uncluttered center",
      "dark matte surface with precise side light and premium showroom mood",
    ],
  },
  {
    id: "food-restaurant",
    label: "Food and Restaurant",
    category: "food",
    tags: ["food", "restaurant", "dining", "kitchen", "menu"],
    productFit: "restaurants, meal offers, delivery, catering, and food products",
    settings: [
      "restaurant counter with warm tile, simple utensils, and clean open wall",
      "chef prep surface with cutting board texture and soft kitchen blur",
      "cozy dining table corner with napkin, glassware, and atmospheric bokeh",
      "takeout pickup ledge with unmarked bags low in frame and neutral backdrop",
      "market stall surface with produce color at the edges and open center",
    ],
  },
  {
    id: "coffee-beverage",
    label: "Coffee and Beverage",
    category: "food",
    tags: ["coffee", "beverage", "cafe", "drink", "bar"],
    productFit: "cafes, drink brands, juice bars, coffee subscriptions, and beverage promos",
    settings: [
      "cafe counter with espresso machine blur, ceramic cup, and clean tile wall",
      "bright juice bar surface with citrus color at edges and empty center",
      "home coffee nook with grinder silhouette, wood shelf, and warm morning light",
      "minimal bar top with condensation texture, glassware blur, and moody light",
      "outdoor cafe table with soft street blur and open sky-toned upper area",
    ],
  },
  {
    id: "meal-prep-nutrition",
    label: "Meal Prep and Nutrition",
    category: "food",
    tags: ["meal-prep", "nutrition", "healthy", "grocery", "kitchen"],
    productFit: "meal plans, nutrition coaching, grocery products, and healthy food offers",
    settings: [
      "organized kitchen counter with containers, fresh ingredients, and open wall",
      "fridge shelf scene with clean containers low in frame and bright interior light",
      "grocery prep table with produce arranged at the edges and clear center",
      "simple pantry shelf with jars, neutral packaging, and copy-ready blank space",
      "sunlit breakfast counter with oats, fruit texture, and quiet domestic mood",
    ],
  },
  {
    id: "home-decor",
    label: "Home Decor",
    category: "home",
    tags: ["home", "decor", "interior", "furniture", "room"],
    productFit: "home goods, decor, furniture, candles, bedding, and interior services",
    settings: [
      "living room wall with sofa edge, textured pillows, and balanced open space",
      "styled shelf with vases, books without readable text, and warm daylight",
      "bedroom corner with layered bedding, bedside lamp, and calm negative space",
      "entryway console with basket texture, plant detail, and clean wall",
      "minimal dining nook with wood table edge and soft pendant light",
    ],
  },
  {
    id: "cleaning-organization",
    label: "Cleaning and Organization",
    category: "home",
    tags: ["cleaning", "organization", "home", "storage", "declutter"],
    productFit: "cleaning products, organizers, home services, and decluttering offers",
    settings: [
      "fresh laundry room counter with folded towels, baskets, and bright wall",
      "organized closet shelves with neutral bins and open center space",
      "kitchen sink area with clean tile, sponge tray, and polished counter",
      "garage storage wall with tidy hooks and matte floor space",
      "minimal cleaning caddy on floor tile with soft daylight and blank wall",
    ],
  },
  {
    id: "parenting-baby",
    label: "Parenting and Baby",
    category: "family",
    tags: ["parenting", "baby", "kids", "family", "nursery"],
    productFit: "baby products, family services, toys, classes, and parenting offers",
    settings: [
      "calm nursery corner with crib edge, soft rug, and blank pastel wall",
      "playroom shelf with simple toys low in frame and clear upper space",
      "stroller-friendly entryway with diaper bag detail and warm home light",
      "kids craft table with paper texture, crayons without text, and open center",
      "bedtime reading nook with pillows, lamp glow, and gentle negative space",
    ],
  },
  {
    id: "pet-care",
    label: "Pet Care",
    category: "pets",
    tags: ["pet", "dog", "cat", "grooming", "veterinary"],
    productFit: "pet products, grooming, training, veterinary clinics, and pet services",
    settings: [
      "pet grooming table with towel texture, comb edge, and clean wall",
      "cozy home pet corner with bed, toy shapes, and open floor space",
      "veterinary exam room with unbranded counter, tile wall, and soft light",
      "outdoor dog park path with grass detail and clear sky area",
      "cat cafe shelf scene with neutral cushions and warm window light",
    ],
  },
  {
    id: "travel-hospitality",
    label: "Travel and Hospitality",
    category: "travel",
    tags: ["travel", "hotel", "vacation", "hospitality", "destination"],
    productFit: "hotels, travel planning, luggage, tours, and destination offers",
    settings: [
      "hotel room desk with curtain light, suitcase edge, and calm blank wall",
      "resort poolside lounger with water color and open sky-toned space",
      "airport lounge table with window blur and polished surface",
      "boutique lobby corner with plant, textured wall, and warm hospitality mood",
      "scenic overlook railing with landscape depth and clean upper area",
    ],
  },
  {
    id: "real-estate",
    label: "Real Estate",
    category: "real-estate",
    tags: ["real-estate", "property", "home", "listing", "interior"],
    productFit: "real estate agents, listings, mortgage offers, staging, and home tours",
    settings: [
      "bright empty living room with window light, wood floor, and clean walls",
      "modern kitchen island with stone surface and open cabinetry blur",
      "front porch entry with door texture, potted plant, and neutral siding",
      "home office nook with built-in shelving and calm negative space",
      "apartment balcony with city blur, railing, and warm evening light",
    ],
  },
  {
    id: "automotive",
    label: "Automotive",
    category: "automotive",
    tags: ["automotive", "car", "garage", "service", "detail"],
    productFit: "auto detailing, dealerships, repair shops, accessories, and car services",
    settings: [
      "clean garage bay with polished concrete, tool chest edge, and blank wall",
      "auto detail studio with soft reflections, microfiber towel, and moody light",
      "dealership lot at golden hour with vehicle shapes blurred at the sides",
      "mechanic workbench with organized tools and open center space",
      "car wash bay with tile texture, water sheen, and uncluttered backdrop",
    ],
  },
  {
    id: "finance-insurance",
    label: "Finance and Insurance",
    category: "finance",
    tags: ["finance", "insurance", "banking", "planning", "money"],
    productFit: "financial advisors, insurance, tax services, budgeting, and fintech",
    settings: [
      "quiet advisor desk with calculator, folder shapes, and clear wall space",
      "modern bank lobby table with glass reflection and neutral architectural lines",
      "home budgeting workspace with notebook, laptop closed, and warm lamp light",
      "tax preparation desk with organized papers without readable text and clean center",
      "premium office conference table with subtle city window blur",
    ],
  },
  {
    id: "saas-software",
    label: "SaaS and Software",
    category: "software",
    tags: ["saas", "software", "startup", "workflow", "technology"],
    productFit: "software tools, apps, agencies, automation, analytics, and B2B offers",
    settings: [
      "minimal desk setup with closed laptop, cable-free surface, and blank wall",
      "startup meeting room with glass wall blur and clean table edge",
      "dark workspace with monitor glow abstracted, no visible UI, and open center",
      "remote work shelf with headphones, plant, and neutral background",
      "modern coworking booth with soft acoustic panels and focused negative space",
    ],
  },
  {
    id: "productivity-office",
    label: "Productivity and Office",
    category: "business",
    tags: ["productivity", "office", "planning", "workspace", "business"],
    productFit: "planners, business tools, consulting, coworking, and work routines",
    settings: [
      "organized desktop with planner shape, pen, mug, and open wall beyond",
      "conference room whiteboard area with no writing and clean meeting table",
      "executive desk corner with leather texture, lamp, and soft city blur",
      "coworking lounge table with notebook shapes and bright natural light",
      "standing desk setup with tidy accessories and a neutral vertical backdrop",
    ],
  },
  {
    id: "education-courses",
    label: "Education and Courses",
    category: "education",
    tags: ["education", "course", "learning", "student", "school"],
    productFit: "online courses, tutoring, schools, workshops, and learning tools",
    settings: [
      "classroom desk row with soft focus chairs and blank board area",
      "study desk with notebook, pencil, warm lamp, and clear wall space",
      "library table with book stacks at edges and quiet open center",
      "workshop room with folding chairs, simple table, and neutral backdrop",
      "online course creator desk with camera tripod silhouette and uncluttered wall",
    ],
  },
  {
    id: "coaching-consulting",
    label: "Coaching and Consulting",
    category: "business",
    tags: ["coaching", "consulting", "strategy", "mentor", "service"],
    productFit: "coaches, consultants, agencies, expert services, and personal brands",
    settings: [
      "calm consultation office with two chairs, side table, and clean wall",
      "strategy workshop table with sticky notes turned away and open board space",
      "premium lounge corner with armchair, plant, and soft professional lighting",
      "small podcast-style studio corner with acoustic panels and empty center",
      "business retreat room with window light, wood table edge, and neutral wall",
    ],
  },
  {
    id: "medical-dental",
    label: "Medical and Dental",
    category: "health",
    tags: ["medical", "dental", "clinic", "health", "appointment"],
    productFit: "clinics, dental practices, med spas, health services, and appointments",
    settings: [
      "clean clinic room with exam table edge, cabinet blur, and calm wall space",
      "dental operatory corner with chair silhouette, tray edge, and bright lighting",
      "reception area with modern chairs, plant detail, and blank wall",
      "med spa treatment room with linen texture, soft lamp, and open backdrop",
      "pharmacy-style counter with neutral shelves and no readable labels",
    ],
  },
  {
    id: "wellness-supplements",
    label: "Wellness and Supplements",
    category: "wellness",
    tags: ["wellness", "supplements", "health", "routine", "self-care"],
    productFit: "supplements, health routines, recovery products, and wellness programs",
    settings: [
      "morning wellness counter with glass of water, towel, and soft kitchen light",
      "minimal bedside routine surface with lamp glow and clean wall",
      "spa-like shelf with stone texture, plant detail, and airy negative space",
      "home recovery corner with blanket, mat, and calming neutral backdrop",
      "bright bathroom shelf with ceramic tray and gentle daylight",
    ],
  },
  {
    id: "events-entertainment",
    label: "Events and Entertainment",
    category: "events",
    tags: ["events", "party", "venue", "music", "tickets"],
    productFit: "venues, event planners, ticketed events, parties, and entertainment offers",
    settings: [
      "empty event venue wall with uplighting, polished floor, and open center",
      "party table edge with balloons blurred at the sides and clean backdrop",
      "small stage with curtain texture, soft lights, and no performers",
      "wedding detail table with linen, floral edge, and elegant negative space",
      "nightlife lounge corner with neon color glow and uncluttered composition",
    ],
  },
  {
    id: "outdoor-recreation",
    label: "Outdoor Recreation",
    category: "outdoor",
    tags: ["outdoor", "camping", "hiking", "adventure", "sports"],
    productFit: "outdoor gear, tours, recreation programs, apparel, and local adventures",
    settings: [
      "trailhead bench with backpack shape, woodland detail, and open sky space",
      "campground table with enamel cup, canvas texture, and warm morning light",
      "lakeside dock with water reflection, railing edge, and clean horizon",
      "mountain overlook path with rocks at the lower edge and wide negative space",
      "sports field sideline with turf texture, fence blur, and bright daylight",
    ],
  },
] satisfies readonly SwiprBackgroundSeedNiche[];
