import type { TextOverlayStyle } from "@/lib/clipstitchr/types/TextOverlayStyle";

export const TEXT_OVERLAY_STYLES: TextOverlayStyle[] = [
  {
    id: "clean",
    label: "Clean",
    fontFamily: "Inter, Arial, Helvetica, sans-serif",
    fontWeight: "800",
    color: "#ffffff",
    shadowColor: "rgba(15, 23, 42, 0.78)",
    shadowBlurRatio: 0.14,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.08,
  },
  {
    id: "hook",
    label: "Hook",
    fontFamily: "Impact, Arial Black, Arial, sans-serif",
    fontWeight: "900",
    color: "#fde047",
    strokeColor: "#020617",
    strokeWidthRatio: 0.075,
    shadowColor: "rgba(2, 6, 23, 0.45)",
    shadowBlurRatio: 0.08,
    shadowOffsetXRatio: 0.03,
    shadowOffsetYRatio: 0.05,
    textTransform: "uppercase",
  },
  {
    id: "caption",
    label: "Caption",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontWeight: "800",
    color: "#ffffff",
    backgroundColor: "rgba(2, 6, 23, 0.72)",
    paddingXRatio: 0.48,
    paddingYRatio: 0.28,
    borderRadiusRatio: 0.22,
  },
  {
    id: "serif",
    label: "Serif",
    fontFamily: "Georgia, Times New Roman, serif",
    fontWeight: "700",
    color: "#fff7ed",
    shadowColor: "rgba(2, 6, 23, 0.72)",
    shadowBlurRatio: 0.12,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.07,
  },
  {
    id: "mono",
    label: "Mono",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontWeight: "800",
    color: "#f8fafc",
    backgroundColor: "rgba(15, 23, 42, 0.82)",
    textTransform: "uppercase",
    paddingXRatio: 0.42,
    paddingYRatio: 0.24,
    borderRadiusRatio: 0.05,
  },
  {
    id: "badge",
    label: "Badge",
    fontFamily: "Arial Black, Arial, Helvetica, sans-serif",
    fontWeight: "900",
    color: "#ffffff",
    backgroundColor: "rgba(79, 70, 229, 0.86)",
    shadowColor: "rgba(2, 6, 23, 0.35)",
    shadowBlurRatio: 0.08,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.05,
    textTransform: "uppercase",
    paddingXRatio: 0.46,
    paddingYRatio: 0.22,
    borderRadiusRatio: 0.42,
  },
  {
    id: "outline",
    label: "Outline",
    fontFamily: "Arial Black, Arial, Helvetica, sans-serif",
    fontWeight: "900",
    color: "#ffffff",
    strokeColor: "#ffffff",
    strokeWidthRatio: 0.04,
    shadowColor: "rgba(2, 6, 23, 0.86)",
    shadowBlurRatio: 0.16,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.05,
  },
  {
    id: "luxe",
    label: "Luxe",
    fontFamily: "Georgia, Times New Roman, serif",
    fontWeight: "700",
    color: "#fef3c7",
    backgroundColor: "rgba(17, 24, 39, 0.62)",
    shadowColor: "rgba(2, 6, 23, 0.55)",
    shadowBlurRatio: 0.1,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.05,
    paddingXRatio: 0.36,
    paddingYRatio: 0.18,
    borderRadiusRatio: 0.08,
  },
  {
    id: "neon",
    label: "Neon",
    fontFamily: "Arial Black, Arial, Helvetica, sans-serif",
    fontWeight: "900",
    color: "#67e8f9",
    shadowColor: "rgba(103, 232, 249, 0.9)",
    shadowBlurRatio: 0.24,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0,
    textTransform: "uppercase",
  },
  {
    id: "soft",
    label: "Soft",
    fontFamily: "Inter, Arial, Helvetica, sans-serif",
    fontWeight: "700",
    color: "#ffffff",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    shadowColor: "rgba(15, 23, 42, 0.55)",
    shadowBlurRatio: 0.12,
    shadowOffsetXRatio: 0,
    shadowOffsetYRatio: 0.06,
    paddingXRatio: 0.32,
    paddingYRatio: 0.2,
    borderRadiusRatio: 0.18,
  },
  {
    id: "snapchat",
    label: "Snapchat",
    fontFamily:
      "Avenir Next, Avenir, Public Sans, Helvetica Neue, Helvetica, Arial, sans-serif",
    fontWeight: "400",
    fontScale: 0.78,
    color: "#ffffff",
    backgroundColor: "rgba(108, 108, 108, 0.84)",
    paddingXRatio: 0.22,
    paddingYRatio: 0.14,
    borderRadiusRatio: 0,
    fullWidthBand: true,
  },
];
