import type { StudioClipsCaptionTemplate } from "./StudioClipsCaptionTemplate";

const templates = {
  default: {
    backColorHex: "#00000000",
    borderStyle: 1,
    fontColorHex: "#FFFFFF",
    fontFamily: "THEBOLDFONT",
    fontSizePx: 32,
    outlineColorHex: "#000000",
    outlineWidth: 3,
    positionY: 0.8,
    shadowDepth: 2,
  },
  hormozi: {
    backColorHex: "#00000000",
    borderStyle: 1,
    fontColorHex: "#FFFFFF",
    fontFamily: "THEBOLDFONT",
    fontSizePx: 38,
    outlineColorHex: "#000000",
    outlineWidth: 4,
    positionY: 0.74,
    shadowDepth: 2,
  },
  minimal: {
    backColorHex: "#00000080",
    borderStyle: 3,
    fontColorHex: "#FFFFFF",
    fontFamily: "TikTokSans-Regular",
    fontSizePx: 26,
    outlineColorHex: "#00000000",
    outlineWidth: 8,
    positionY: 0.82,
    shadowDepth: 0,
  },
  mrbeast: {
    backColorHex: "#00000000",
    borderStyle: 1,
    fontColorHex: "#FFFF00",
    fontFamily: "THEBOLDFONT",
    fontSizePx: 42,
    outlineColorHex: "#000000",
    outlineWidth: 5,
    positionY: 0.7,
    shadowDepth: 2,
  },
  neon: {
    backColorHex: "#00000000",
    borderStyle: 1,
    fontColorHex: "#00FFFF",
    fontFamily: "THEBOLDFONT",
    fontSizePx: 36,
    outlineColorHex: "#002A6B",
    outlineWidth: 2,
    positionY: 0.76,
    shadowDepth: 0,
  },
  podcast: {
    backColorHex: "#1A1A1ACC",
    borderStyle: 3,
    fontColorHex: "#FFFFFF",
    fontFamily: "TikTokSans-Regular",
    fontSizePx: 28,
    outlineColorHex: "#1A1A1A",
    outlineWidth: 6,
    positionY: 0.8,
    shadowDepth: 0,
  },
  tiktok: {
    backColorHex: "#00000000",
    borderStyle: 1,
    fontColorHex: "#FFFFFF",
    fontFamily: "TikTokSans-Regular",
    fontSizePx: 34,
    outlineColorHex: "#000000",
    outlineWidth: 3,
    positionY: 0.78,
    shadowDepth: 2,
  },
} as const satisfies Record<string, StudioClipsCaptionTemplate>;

export function getStudioClipsCaptionTemplate(
  templateId: string,
): StudioClipsCaptionTemplate | undefined {
  return templates[templateId as keyof typeof templates];
}
