import type { Doc } from "./_generated/dataModel";

export function createStitchCardFields(stitch: Doc<"stitches">) {
  return {
    ownerId: stitch.ownerId,
    id: stitch.id,
    productId: stitch.productId,
    mode: stitch.mode,
    name: stitch.name,
    ugcClipId: stitch.ugcClipId,
    demoClipId: stitch.demoClipId,
    ugcClipName: stitch.ugcClipName,
    demoClipName: stitch.demoClipName,
    ugcTrimRange: stitch.ugcTrimRange,
    demoTrimRange: stitch.demoTrimRange,
    demoQuickEdit: stitch.demoQuickEdit,
    quickEdit: stitch.quickEdit,
    ugcQuickEdit: stitch.ugcQuickEdit,
    sequenceSegments: stitch.sequenceSegments,
    stitchObject: stitch.stitchObject,
    posterObject: stitch.posterObject,
    posterVersion: stitch.posterVersion,
    mimeType: stitch.mimeType,
    size: stitch.size,
    width: stitch.width,
    height: stitch.height,
    duration: stitch.duration,
    includeDemoAudio: stitch.includeDemoAudio,
    includeUgcAudio: stitch.includeUgcAudio,
    demoPlaybackRate: stitch.demoPlaybackRate,
    ugcPlaybackRate: stitch.ugcPlaybackRate,
    music: stitch.music,
    textOverlay: stitch.textOverlay,
    textOverlays: stitch.textOverlays,
    socialCaption: stitch.socialCaption,
    stitchScore: stitch.stitchScore,
    firstStitchScore: stitch.firstStitchScore,
    socialPublishingPosts: stitch.socialPublishingPosts,
    isPosted: stitch.isPosted,
    postedAt: stitch.postedAt,
    automation: stitch.automation,
    createdAt: stitch.createdAt,
  };
}
