type CliprGeneratedScenePlanInput = {
  sceneType: "avatar" | "demo";
  scriptText?: string;
  visualPrompt?: string;
};

type CliprGeneratedClipStorageJob = {
  avatarName?: string;
  demoClipName?: string;
  generationMode?: "script" | "reaction" | "broll" | "demo";
  productDetails: string;
  productId: string;
  productName: string;
  scenePlan: CliprGeneratedScenePlanInput[];
  script?: string;
};

function cleanText(value: string | undefined, maxLength: number) {
  const text = value?.replace(/\s+/g, " ").trim() ?? "";

  return text ? text.slice(0, maxLength) : undefined;
}

function getSceneSummary(scenePlan: CliprGeneratedScenePlanInput[]) {
  return cleanText(
    scenePlan
      .map((scene) =>
        [scene.scriptText, scene.visualPrompt].filter(Boolean).join(" "),
      )
      .filter(Boolean)
      .join(" "),
    5000,
  );
}

function getPrimaryScene(scenePlan: CliprGeneratedScenePlanInput[]) {
  return scenePlan[0] ?? null;
}

export function getCliprGeneratedClipStorageFields(
  job: CliprGeneratedClipStorageJob,
) {
  const isDemo = job.generationMode === "demo";
  const primaryScene = getPrimaryScene(job.scenePlan);
  const sceneSummary = getSceneSummary(job.scenePlan);
  const productDescription = cleanText(
    `${job.productName}: ${job.productDetails}`,
    1200,
  );
  const visualPrompt = cleanText(primaryScene?.visualPrompt, 800);
  const actionDescription = cleanText(
    primaryScene?.scriptText || primaryScene?.visualPrompt || sceneSummary,
    3000,
  );
  const videoDescription = cleanText(
    isDemo
      ? [
          `Clipr demo remix for ${job.productName}.`,
          job.demoClipName ? `Source demo: ${job.demoClipName}.` : undefined,
          sceneSummary,
        ]
          .filter(Boolean)
          .join(" ")
      : [
          `Clipr ${job.generationMode ?? "script"} clip for ${job.productName}.`,
          cleanText(job.script, 1800),
          sceneSummary,
        ]
          .filter(Boolean)
          .join(" "),
    5000,
  );

  return {
    clipType: isDemo ? ("demo" as const) : ("ugc" as const),
    libraryKind: isDemo ? ("demo" as const) : ("clipr" as const),
    tags: isDemo ? ["demo", "clipr"] : ["ugc", "clipr"],
    ...(isDemo ? { productId: job.productId } : {}),
    ...(videoDescription ? { videoDescription } : {}),
    ...(productDescription ? { productDescription } : {}),
    ...(visualPrompt ? { locationDescription: visualPrompt } : {}),
    ...(actionDescription ? { poseDescription: actionDescription } : {}),
    mainPersonDescription: isDemo
      ? "UGC-style person presenting the product demo in a short vertical scene."
      : `Avatar clone${job.avatarName ? ` ${job.avatarName}` : ""} in a generated Clipr video.`,
    outfitDescription: isDemo
      ? "Context-appropriate everyday outfit generated by Clipr."
      : "Prompt-guided outfit generated by Clipr for the selected avatar scene.",
  };
}
