import { DAY, HOUR, MINUTE, SECOND, RateLimiter } from "@convex-dev/rate-limiter";
import { components } from "./_generated/api";
import {
  AUTOMATION_STITCHR_DAILY_LIMIT,
  AUTOMATION_STITCHR_GLOBAL_DAILY_LIMIT,
} from "../lib/clipstitchr/constants/automationStitchrGenerationLimits";
import {
  STITCHR_BATCH_DAILY_LIMIT,
  STITCHR_BATCH_GLOBAL_DAILY_LIMIT,
} from "../lib/clipstitchr/constants/stitchrBatchGenerationLimits";

const GIGABYTE = 1024 * 1024 * 1024;
const MONTH = 30 * DAY;

export const rateLimiter = new RateLimiter(components.rateLimiter, {
  stripeSubscriptionCheckout: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 3,
  },
  stripeSubscriptionCheckoutGlobal: {
    kind: "token bucket",
    rate: 1_000,
    period: HOUR,
    capacity: 100,
    shards: 5,
  },
  stripeRefillCheckout: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 3,
  },
  stripeRefillCheckoutGlobal: {
    kind: "token bucket",
    rate: 1_000,
    period: HOUR,
    capacity: 100,
    shards: 5,
  },
  stripePortalSession: {
    kind: "token bucket",
    rate: 30,
    period: HOUR,
    capacity: 6,
  },
  stripePortalSessionGlobal: {
    kind: "token bucket",
    rate: 2_000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  r2UploadUrl: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 500,
  },
  r2UploadBytes: {
    kind: "token bucket",
    rate: 10 * GIGABYTE,
    period: DAY,
    capacity: 10 * GIGABYTE,
  },
  r2UploadBytesMonthly: {
    kind: "token bucket",
    rate: 500 * GIGABYTE,
    period: MONTH,
    capacity: 500 * GIGABYTE,
  },
  r2DownloadUrl: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 1000,
  },
  r2DeleteObjects: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 500,
  },
  pexelsSearch: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 30,
  },
  pexelsSearchGlobal: {
    kind: "token bucket",
    rate: 800,
    period: HOUR,
    capacity: 200,
    shards: 4,
  },
  pexelsImportImages: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 120,
  },
  pexelsImportImagesGlobal: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 500,
    shards: 4,
  },
  replicateUploadAnalysis: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 100,
  },
  replicateUploadAnalysisMonthly: {
    kind: "token bucket",
    rate: 10000,
    period: MONTH,
    capacity: 10000,
  },
  replicateUploadAnalysisGlobal: {
    kind: "token bucket",
    rate: 6000,
    period: HOUR,
    capacity: 1000,
    shards: 10,
  },
  replicateUploadVideoAnalysis: {
    kind: "token bucket",
    rate: 60,
    period: HOUR,
    capacity: 20,
  },
  replicateUploadVideoAnalysisMonthly: {
    kind: "token bucket",
    rate: 1500,
    period: MONTH,
    capacity: 1500,
  },
  replicateUploadVideoAnalysisGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  stitchScoreAnalyze: {
    kind: "token bucket",
    rate: 60,
    period: HOUR,
    capacity: 20,
  },
  stitchScoreAnalyzeMonthly: {
    kind: "token bucket",
    rate: 1500,
    period: MONTH,
    capacity: 1500,
  },
  stitchScoreAnalyzeGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  replicateSwaprPhotoExpand: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 5,
  },
  replicateSwaprPhotoExpandDaily: {
    kind: "token bucket",
    rate: 20,
    period: DAY,
    capacity: 20,
  },
  replicateSwaprPhotoExpandMonthly: {
    kind: "token bucket",
    rate: 375,
    period: MONTH,
    capacity: 375,
  },
  replicateSwaprPhotoExpandGlobal: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 50,
    shards: 5,
  },
  replicateSwaprJobCreate: {
    kind: "token bucket",
    rate: 2,
    period: HOUR,
    capacity: 2,
  },
  replicateSwaprJobCreateDaily: {
    kind: "token bucket",
    rate: 5,
    period: DAY,
    capacity: 5,
  },
  replicateSwaprGeneratedSecondsMonthly: {
    kind: "token bucket",
    rate: 500,
    period: MONTH,
    capacity: 500,
  },
  replicateSwaprProviderSegment: {
    kind: "token bucket",
    rate: 60,
    period: HOUR,
    capacity: 60,
  },
  replicateSwaprProviderSegmentDaily: {
    kind: "token bucket",
    rate: 180,
    period: DAY,
    capacity: 180,
  },
  replicateSwaprJobCreateGlobal: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 50,
    shards: 5,
  },
  replicateSwaprJobPoll: {
    kind: "token bucket",
    rate: 600,
    period: MINUTE,
    capacity: 150,
  },
  replicateSwaprJobCancel: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  replicateSwaprOutputDownload: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
  },
  replicateAvatarPhotoGenerate: {
    kind: "token bucket",
    rate: 15,
    period: HOUR,
    capacity: 10,
  },
  replicateAvatarPhotoGenerateDaily: {
    kind: "token bucket",
    rate: 25,
    period: DAY,
    capacity: 25,
  },
  replicateAvatarPhotoGenerateMonthly: {
    kind: "token bucket",
    rate: 500,
    period: MONTH,
    capacity: 500,
  },
  replicateAvatarPhotoGenerateGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 150,
    shards: 10,
  },
  replicateSwiprBackgroundGenerate: {
    kind: "token bucket",
    rate: 20,
    period: HOUR,
    capacity: 8,
  },
  replicateSwiprBackgroundGenerateDaily: {
    kind: "token bucket",
    rate: 50,
    period: DAY,
    capacity: 50,
  },
  replicateSwiprBackgroundGenerateMonthly: {
    kind: "token bucket",
    rate: 500,
    period: MONTH,
    capacity: 500,
  },
  replicateSwiprBackgroundGenerateGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 100,
    shards: 10,
  },
  replicateSwiprSeedBackgroundGenerateDev: {
    kind: "token bucket",
    rate: 1000,
    period: DAY,
    capacity: 1000,
  },
  replicateSwiprSeedBackgroundGenerateDevGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 100,
    shards: 10,
  },
  waitlistSubmitByEmail: {
    kind: "token bucket",
    rate: 3,
    period: HOUR,
    capacity: 3,
  },
  waitlistSubmitGlobal: {
    kind: "token bucket",
    rate: 500,
    period: HOUR,
    capacity: 100,
    shards: 5,
  },
  toolLeadSubmitByClient: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 5,
  },
  toolLeadSubmitByEmail: {
    kind: "token bucket",
    rate: 3,
    period: HOUR,
    capacity: 3,
  },
  toolLeadSubmitGlobal: {
    kind: "token bucket",
    rate: 500,
    period: HOUR,
    capacity: 100,
    shards: 5,
  },
  toolLeadInteractionByToken: {
    kind: "token bucket",
    rate: 60,
    period: HOUR,
    capacity: 20,
  },
  toolLeadInteractionByClient: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 30,
  },
  toolLeadInteractionGlobal: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 1000,
    shards: 5,
  },
  emailConfirmationSendByEmail: {
    kind: "token bucket",
    rate: 3,
    period: DAY,
    capacity: 1,
  },
  emailConfirmationSendByClient: {
    kind: "token bucket",
    rate: 5,
    period: HOUR,
    capacity: 2,
  },
  emailConfirmationSendGlobal: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 50,
    shards: 5,
  },
  emailConfirmationRedeemByToken: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 5,
  },
  emailConfirmationRedeemByClient: {
    kind: "token bucket",
    rate: 20,
    period: HOUR,
    capacity: 5,
  },
  emailConfirmationRedeemGlobal: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  emailNativeEnrollmentByContact: {
    kind: "token bucket",
    rate: 3,
    period: DAY,
    capacity: 1,
  },
  emailNativeEnrollmentByClient: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 3,
  },
  emailNativeEnrollmentGlobal: {
    kind: "token bucket",
    rate: 500,
    period: HOUR,
    capacity: 100,
    shards: 5,
  },
  courseWorkspaceReadBySession: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 30,
  },
  courseWorkspaceReadGlobal: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 1000,
    shards: 5,
  },
  courseProgressWriteBySession: {
    kind: "token bucket",
    rate: 240,
    period: HOUR,
    capacity: 60,
  },
  courseProgressWriteByClient: {
    kind: "token bucket",
    rate: 360,
    period: HOUR,
    capacity: 90,
  },
  courseProgressWriteGlobal: {
    kind: "token bucket",
    rate: 10000,
    period: HOUR,
    capacity: 2000,
    shards: 5,
  },
  courseProgressResetBySession: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 3,
  },
  courseProgressResetGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 100,
    shards: 5,
  },
  emailWorkflowEventByContact: {
    kind: "token bucket",
    rate: 10,
    period: DAY,
    capacity: 4,
  },
  emailWorkflowEventGlobal: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 400,
    shards: 5,
  },
  emailTransactionalByContact: {
    kind: "token bucket",
    rate: 10,
    period: DAY,
    capacity: 3,
  },
  emailTransactionalGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  accountTransactionalEmailByOwner: {
    kind: "token bucket",
    rate: 30,
    period: DAY,
    capacity: 10,
  },
  accountTransactionalEmailGlobal: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 300,
    shards: 5,
  },
  accountContactSyncByOwner: {
    kind: "token bucket",
    rate: 30,
    period: HOUR,
    capacity: 6,
  },
  accountContactSyncGlobal: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 300,
    shards: 5,
  },
  loopsProviderRequest: {
    kind: "token bucket",
    rate: 8,
    period: SECOND,
    capacity: 2,
  },
  marketingPrivacyDeletionOperator: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  appHookGeneratorByClient: {
    kind: "token bucket",
    rate: 30,
    period: HOUR,
    capacity: 10,
  },
  appHookGeneratorGlobal: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 300,
    shards: 5,
  },
  tiktokEventsApiByClient: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 30,
  },
  tiktokEventsApiGlobal: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 1000,
    shards: 10,
  },
  cliDeviceAuthorizationByClient: {
    kind: "token bucket",
    rate: 20,
    period: HOUR,
    capacity: 5,
  },
  cliDeviceAuthorizationGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  cliDeviceTokenExchangeByClient: {
    kind: "token bucket",
    rate: 120,
    period: MINUTE,
    capacity: 30,
  },
  cliDeviceTokenExchangeGlobal: {
    kind: "token bucket",
    rate: 10000,
    period: MINUTE,
    capacity: 1000,
    shards: 10,
  },
  cliDemoGuideGenerate: {
    kind: "token bucket",
    rate: 20,
    period: HOUR,
    capacity: 5,
  },
  cliDemoGuideGenerateGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  cliDemoAgentPlan: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 20,
  },
  cliDemoAgentPlanGlobal: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 500,
    shards: 5,
  },
  cliOpenAiComputerRelay: {
    kind: "token bucket",
    rate: 160,
    period: HOUR,
    capacity: 40,
  },
  cliOpenAiComputerRelayDaily: {
    kind: "token bucket",
    rate: 300,
    period: DAY,
    capacity: 300,
  },
  cliOpenAiComputerRelayRun: {
    kind: "token bucket",
    rate: 80,
    period: 30 * MINUTE,
    capacity: 80,
  },
  cliOpenAiComputerRelayGlobal: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 500,
    shards: 5,
  },
  tiktokSoundLookup: {
    kind: "token bucket",
    rate: 60,
    period: HOUR,
    capacity: 20,
  },
  tiktokSoundLookupGlobal: {
    kind: "token bucket",
    rate: 600,
    period: HOUR,
    capacity: 100,
    shards: 5,
  },
  tiktokSoundImport: {
    kind: "token bucket",
    rate: 30,
    period: HOUR,
    capacity: 10,
  },
  tiktokSoundImportGlobal: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 60,
    shards: 5,
  },
  hookLabSocialImport: {
    kind: "token bucket",
    rate: 15,
    period: DAY,
    capacity: 3,
  },
  hookLabSocialImportGlobal: {
    kind: "token bucket",
    rate: 300,
    period: DAY,
    capacity: 60,
    shards: 5,
  },
  hookLabIdeaAnalysis: {
    kind: "token bucket",
    rate: 30,
    period: DAY,
    capacity: 5,
  },
  hookLabIdeaAnalysisGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: DAY,
    capacity: 200,
    shards: 5,
  },
  hookLabIdeaUse: {
    kind: "token bucket",
    rate: 10,
    period: DAY,
    capacity: 5,
  },
  hookLabIdeaAssetSave: {
    kind: "token bucket",
    rate: 20,
    period: DAY,
    capacity: 10,
  },
  hookLabIdeaAssetSaveGlobal: {
    kind: "token bucket",
    rate: 2000,
    period: DAY,
    capacity: 400,
    shards: 5,
  },
  postBridgeRead: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 30,
  },
  postBridgeReadGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  postBridgeProviderRequest: {
    kind: "token bucket",
    rate: 8,
    period: SECOND,
    capacity: 2,
    maxReserved: 40,
  },
  postBridgeSchedule: {
    kind: "token bucket",
    rate: 600,
    period: MINUTE,
    capacity: 60,
  },
  postBridgeScheduleHourly: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 100,
  },
  postBridgeScheduleDaily: {
    kind: "token bucket",
    rate: 1000,
    period: DAY,
    capacity: 1000,
  },
  postBridgeUploadBytesDaily: {
    kind: "token bucket",
    rate: 2 * GIGABYTE,
    period: DAY,
    capacity: 2 * GIGABYTE,
  },
  postBridgeScheduleGlobalDaily: {
    kind: "token bucket",
    rate: 10000,
    period: DAY,
    capacity: 1000,
    shards: 10,
  },
  postBridgeUploadBytesGlobalDaily: {
    kind: "token bucket",
    rate: 50 * GIGABYTE,
    period: DAY,
    capacity: 50 * GIGABYTE,
    shards: 10,
  },
  postBridgeAnalyticsSync: {
    kind: "token bucket",
    rate: 12,
    period: HOUR,
    capacity: 3,
  },
  postBridgeAnalyticsSyncGlobal: {
    kind: "token bucket",
    rate: 200,
    period: HOUR,
    capacity: 40,
    shards: 5,
  },
  indexNowSubmitUrlsByClient: {
    kind: "token bucket",
    rate: 500,
    period: HOUR,
    capacity: 500,
  },
  indexNowSubmitUrlsGlobal: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 500,
  },
  blogPublishWebhookByClient: {
    kind: "token bucket",
    rate: 120,
    period: HOUR,
    capacity: 30,
  },
  blogPublishWebhookGlobal: {
    kind: "token bucket",
    rate: 600,
    period: HOUR,
    capacity: 120,
    shards: 5,
  },
  cliprJobCreate: {
    kind: "token bucket",
    rate: 3,
    period: HOUR,
    capacity: 2,
  },
  cliprJobCreateDaily: {
    kind: "token bucket",
    rate: 8,
    period: DAY,
    capacity: 8,
  },
  cliprGeneratedSecondsMonthly: {
    kind: "token bucket",
    rate: 900,
    period: MONTH,
    capacity: 900,
  },
  cliprHookScriptGenerate: {
    kind: "token bucket",
    rate: 30,
    period: HOUR,
    capacity: 10,
  },
  cliprVoiceGenerate: {
    kind: "token bucket",
    rate: 600,
    period: HOUR,
    capacity: 180,
  },
  cliprVideoGenerate: {
    kind: "token bucket",
    rate: 600,
    period: HOUR,
    capacity: 180,
  },
  cliprAvatarStillGenerate: {
    kind: "token bucket",
    rate: 20,
    period: HOUR,
    capacity: 6,
  },
  cliprMusicGenerate: {
    kind: "token bucket",
    rate: 600,
    period: HOUR,
    capacity: 180,
  },
  cliprMusicGenerateDaily: {
    kind: "token bucket",
    rate: 1200,
    period: DAY,
    capacity: 1200,
  },
  stitchMusicGenerate: {
    kind: "token bucket",
    rate: 600,
    period: HOUR,
    capacity: 180,
  },
  stitchMusicGenerateDaily: {
    kind: "token bucket",
    rate: 1200,
    period: DAY,
    capacity: 1200,
  },
  sharedMusicGenerate: {
    kind: "token bucket",
    rate: 600,
    period: HOUR,
    capacity: 180,
  },
  sharedMusicGenerateDaily: {
    kind: "token bucket",
    rate: 1200,
    period: DAY,
    capacity: 1200,
  },
  cliprProviderSpendGlobal: {
    kind: "token bucket",
    rate: 10000,
    period: HOUR,
    capacity: 2000,
    shards: 10,
  },
  automationStitchrDaily: {
    kind: "token bucket",
    rate: AUTOMATION_STITCHR_DAILY_LIMIT,
    period: DAY,
    capacity: AUTOMATION_STITCHR_DAILY_LIMIT,
  },
  automationStitchrGlobalDaily: {
    kind: "token bucket",
    rate: AUTOMATION_STITCHR_GLOBAL_DAILY_LIMIT,
    period: DAY,
    capacity: AUTOMATION_STITCHR_GLOBAL_DAILY_LIMIT,
    shards: 5,
  },
  stitchrBatchDaily: {
    kind: "token bucket",
    rate: STITCHR_BATCH_DAILY_LIMIT,
    period: DAY,
    capacity: STITCHR_BATCH_DAILY_LIMIT,
  },
  stitchrBatchGlobalDaily: {
    kind: "token bucket",
    rate: STITCHR_BATCH_GLOBAL_DAILY_LIMIT,
    period: DAY,
    capacity: STITCHR_BATCH_GLOBAL_DAILY_LIMIT,
    shards: 5,
  },
  stitchrBatchHookPlanDaily: {
    kind: "token bucket",
    rate: 20,
    period: DAY,
    capacity: 10,
  },
  stitchrBatchHookPlanGlobalDaily: {
    kind: "token bucket",
    rate: 2000,
    period: DAY,
    capacity: 500,
    shards: 5,
  },
  stitchrBatchAssetSaveDaily: {
    kind: "token bucket",
    rate: STITCHR_BATCH_DAILY_LIMIT,
    period: DAY,
    capacity: STITCHR_BATCH_DAILY_LIMIT,
  },
  stitchrBatchAssetSaveGlobalDaily: {
    kind: "token bucket",
    rate: STITCHR_BATCH_GLOBAL_DAILY_LIMIT,
    period: DAY,
    capacity: STITCHR_BATCH_GLOBAL_DAILY_LIMIT,
    shards: 5,
  },
  automationSwaprDaily: {
    kind: "token bucket",
    rate: 1,
    period: DAY,
    capacity: 1,
  },
  automationSwaprGlobalDaily: {
    kind: "token bucket",
    rate: 100,
    period: DAY,
    capacity: 100,
    shards: 5,
  },
  automationCliprDaily: {
    kind: "token bucket",
    rate: 1,
    period: DAY,
    capacity: 1,
  },
  automationCliprGlobalDaily: {
    kind: "token bucket",
    rate: 100,
    period: DAY,
    capacity: 100,
    shards: 5,
  },
  automationAvatarPhotoDaily: {
    kind: "token bucket",
    rate: 1,
    period: DAY,
    capacity: 1,
  },
  automationAvatarPhotoGlobalDaily: {
    kind: "token bucket",
    rate: 500,
    period: DAY,
    capacity: 500,
    shards: 5,
  },
  automationSwiprDaily: {
    kind: "token bucket",
    rate: 10,
    period: DAY,
    capacity: 10,
  },
  automationSwiprGlobalDaily: {
    kind: "token bucket",
    rate: 100,
    period: DAY,
    capacity: 100,
    shards: 5,
  },
  automationProviderCostDailyGlobal: {
    kind: "token bucket",
    rate: 10000,
    period: DAY,
    capacity: 10000,
    shards: 10,
  },
  automationAssetSaveDaily: {
    kind: "token bucket",
    rate: 20,
    period: DAY,
    capacity: 20,
  },
  automationAssetSaveGlobalDaily: {
    kind: "token bucket",
    rate: 2000,
    period: DAY,
    capacity: 2000,
    shards: 10,
  },
  cliprJobPoll: {
    kind: "token bucket",
    rate: 600,
    period: MINUTE,
    capacity: 150,
  },
  cliprJobCancel: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  replicateProductEnrichment: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  replicateProductEnrichmentMonthly: {
    kind: "token bucket",
    rate: 2000,
    period: MONTH,
    capacity: 2000,
  },
  replicateProductEnrichmentGlobal: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 500,
    shards: 10,
  },
  avatarCascadeDelete: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  convexRecordSave: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 500,
  },
  convexMetadataUpdate: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 1000,
  },
  convexPosterUpdate: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 300,
  },
  convexCliprJobWrite: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 500,
  },
  convexRecordDelete: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 500,
  },
});
