import { DAY, HOUR, MINUTE, RateLimiter } from "@convex-dev/rate-limiter";
import { components } from "./_generated/api";

const GIGABYTE = 1024 * 1024 * 1024;
const MONTH = 30 * DAY;

export const rateLimiter = new RateLimiter(components.rateLimiter, {
  r2UploadUrl: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 500,
  },
  r2UploadBytes: {
    kind: "token bucket",
    rate: 10 * GIGABYTE,
    period: DAY,
    capacity: 10 * GIGABYTE,
  },
  r2UploadBytesMonthly: {
    kind: "token bucket",
    rate: 500 * GIGABYTE,
    period: MONTH,
    capacity: 500 * GIGABYTE,
  },
  r2DownloadUrl: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 1000,
  },
  r2DeleteObjects: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 500,
  },
  replicateUploadAnalysis: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 100,
  },
  replicateUploadAnalysisMonthly: {
    kind: "token bucket",
    rate: 10000,
    period: MONTH,
    capacity: 10000,
  },
  replicateUploadAnalysisGlobal: {
    kind: "token bucket",
    rate: 6000,
    period: HOUR,
    capacity: 1000,
    shards: 10,
  },
  replicateUploadVideoAnalysis: {
    kind: "token bucket",
    rate: 60,
    period: HOUR,
    capacity: 20,
  },
  replicateUploadVideoAnalysisMonthly: {
    kind: "token bucket",
    rate: 1500,
    period: MONTH,
    capacity: 1500,
  },
  replicateUploadVideoAnalysisGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
    shards: 5,
  },
  replicateSwaprPhotoExpand: {
    kind: "token bucket",
    rate: 10,
    period: HOUR,
    capacity: 5,
  },
  replicateSwaprPhotoExpandDaily: {
    kind: "token bucket",
    rate: 20,
    period: DAY,
    capacity: 20,
  },
  replicateSwaprPhotoExpandMonthly: {
    kind: "token bucket",
    rate: 375,
    period: MONTH,
    capacity: 375,
  },
  replicateSwaprPhotoExpandGlobal: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 50,
    shards: 5,
  },
  replicateSwaprJobCreate: {
    kind: "token bucket",
    rate: 2,
    period: HOUR,
    capacity: 2,
  },
  replicateSwaprJobCreateDaily: {
    kind: "token bucket",
    rate: 5,
    period: DAY,
    capacity: 5,
  },
  replicateSwaprGeneratedSecondsMonthly: {
    kind: "token bucket",
    rate: 500,
    period: MONTH,
    capacity: 500,
  },
  replicateSwaprJobCreateGlobal: {
    kind: "token bucket",
    rate: 300,
    period: HOUR,
    capacity: 50,
    shards: 5,
  },
  replicateSwaprJobPoll: {
    kind: "token bucket",
    rate: 600,
    period: MINUTE,
    capacity: 150,
  },
  replicateSwaprJobCancel: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  replicateSwaprOutputDownload: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 200,
  },
  replicateAvatarPhotoGenerate: {
    kind: "token bucket",
    rate: 15,
    period: HOUR,
    capacity: 10,
  },
  replicateAvatarPhotoGenerateDaily: {
    kind: "token bucket",
    rate: 25,
    period: DAY,
    capacity: 25,
  },
  replicateAvatarPhotoGenerateMonthly: {
    kind: "token bucket",
    rate: 500,
    period: MONTH,
    capacity: 500,
  },
  replicateAvatarPhotoGenerateGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 150,
    shards: 10,
  },
  replicateSwiprBackgroundGenerate: {
    kind: "token bucket",
    rate: 20,
    period: HOUR,
    capacity: 5,
  },
  replicateSwiprBackgroundGenerateDaily: {
    kind: "token bucket",
    rate: 50,
    period: DAY,
    capacity: 50,
  },
  replicateSwiprBackgroundGenerateMonthly: {
    kind: "token bucket",
    rate: 500,
    period: MONTH,
    capacity: 500,
  },
  replicateSwiprBackgroundGenerateGlobal: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 100,
    shards: 10,
  },
  cliprJobCreate: {
    kind: "token bucket",
    rate: 3,
    period: HOUR,
    capacity: 2,
  },
  cliprJobCreateDaily: {
    kind: "token bucket",
    rate: 8,
    period: DAY,
    capacity: 8,
  },
  cliprGeneratedSecondsMonthly: {
    kind: "token bucket",
    rate: 900,
    period: MONTH,
    capacity: 900,
  },
  cliprHookScriptGenerate: {
    kind: "token bucket",
    rate: 30,
    period: HOUR,
    capacity: 10,
  },
  cliprVoiceGenerate: {
    kind: "token bucket",
    rate: 60,
    period: HOUR,
    capacity: 20,
  },
  cliprAvatarStillGenerate: {
    kind: "token bucket",
    rate: 20,
    period: HOUR,
    capacity: 6,
  },
  cliprSceneGenerate: {
    kind: "token bucket",
    rate: 40,
    period: HOUR,
    capacity: 12,
  },
  cliprProviderSpendGlobal: {
    kind: "token bucket",
    rate: 500,
    period: HOUR,
    capacity: 80,
    shards: 10,
  },
  cliprJobPoll: {
    kind: "token bucket",
    rate: 600,
    period: MINUTE,
    capacity: 150,
  },
  cliprJobCancel: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  replicateProductEnrichment: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  replicateProductEnrichmentMonthly: {
    kind: "token bucket",
    rate: 2000,
    period: MONTH,
    capacity: 2000,
  },
  replicateProductEnrichmentGlobal: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 500,
    shards: 10,
  },
  avatarCascadeDelete: {
    kind: "token bucket",
    rate: 100,
    period: HOUR,
    capacity: 20,
  },
  convexRecordSave: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 500,
  },
  convexMetadataUpdate: {
    kind: "token bucket",
    rate: 5000,
    period: HOUR,
    capacity: 1000,
  },
  convexPosterUpdate: {
    kind: "token bucket",
    rate: 1000,
    period: HOUR,
    capacity: 300,
  },
  convexCliprJobWrite: {
    kind: "token bucket",
    rate: 3000,
    period: HOUR,
    capacity: 500,
  },
  convexRecordDelete: {
    kind: "token bucket",
    rate: 2000,
    period: HOUR,
    capacity: 500,
  },
});
