import type { CliprHookStyle } from "@/lib/clipstitchr/types/CliprHookStyle";

export const cliprHookStyles: CliprHookStyle[] = [
  {
    styleKey: "mystery_gap",
    styleName: "Mystery Gap",
    sourceCategory: "Curiosity",
    coreIntent: "Create an unanswered question the viewer wants resolved",
    emotionalTrigger: "curiosity",
    bestFor: ["education", "problem awareness", "workflow insights"],
    riskLevel: "safe",
  },
  {
    styleKey: "authority_signal",
    styleName: "Authority Signal",
    sourceCategory: "Expertise",
    coreIntent: "Borrow credibility from expertise research data or experience",
    emotionalTrigger: "trust",
    bestFor: ["expert guidance", "research", "professional tips"],
    riskLevel: "safe",
  },
  {
    styleKey: "anti_advice",
    styleName: "Anti-Advice",
    sourceCategory: "Contrarian",
    coreIntent: "Challenge the obvious popular or default advice",
    emotionalTrigger: "contrarian interest",
    bestFor: ["myth correction", "opinion content", "category education"],
    riskLevel: "medium",
  },
  {
    styleKey: "inside_room",
    styleName: "Inside Room",
    sourceCategory: "Insider",
    coreIntent: "Reveal hidden rules incentives or behind-the-scenes knowledge",
    emotionalTrigger: "insider access",
    bestFor: ["behind the scenes", "process education", "operator lessons"],
    riskLevel: "safe",
  },
  {
    styleKey: "direct_diagnosis",
    styleName: "Direct Diagnosis",
    sourceCategory: "Callout",
    coreIntent: "Name the viewer's behavior problem or blind spot directly",
    emotionalTrigger: "recognition",
    bestFor: ["mistake awareness", "behavior change", "workflow fixes"],
    riskLevel: "medium",
  },
  {
    styleKey: "before_after_arc",
    styleName: "Before/After Arc",
    sourceCategory: "Transformation",
    coreIntent: "Show a clear movement from bad state to better state",
    emotionalTrigger: "progress",
    bestFor: ["process improvement", "case studies", "how-to content"],
    riskLevel: "safe",
  },
  {
    styleKey: "cost_alert",
    styleName: "Cost Alert",
    sourceCategory: "Warning",
    coreIntent: "Make the viewer feel the cost of continuing a mistake",
    emotionalTrigger: "loss aversion",
    bestFor: ["risk education", "mistake prevention", "workflow cleanup"],
    riskLevel: "medium",
  },
  {
    styleKey: "deadline_pull",
    styleName: "Deadline Pull",
    sourceCategory: "FOMO",
    coreIntent: "Create urgency around timing opportunity or missed advantage",
    emotionalTrigger: "urgency",
    bestFor: ["timely advice", "planning", "trend readiness"],
    riskLevel: "medium",
  },
  {
    styleKey: "receipt_stack",
    styleName: "Receipt Stack",
    sourceCategory: "Proof",
    coreIntent: "Use evidence results examples or tests to support the claim",
    emotionalTrigger: "proof",
    bestFor: ["experiments", "examples", "comparison content"],
    riskLevel: "safe",
  },
  {
    styleKey: "future_cast",
    styleName: "Future Cast",
    sourceCategory: "Prediction",
    coreIntent: "Show what is likely to happen next and why it matters",
    emotionalTrigger: "anticipation",
    bestFor: ["trend commentary", "category shifts", "strategic advice"],
    riskLevel: "medium",
  },
  {
    styleKey: "test_drive",
    styleName: "Test Drive",
    sourceCategory: "Experiment",
    coreIntent: "Show what happened after trying comparing or stress-testing something",
    emotionalTrigger: "practical proof",
    bestFor: ["tests", "comparisons", "process experiments"],
    riskLevel: "safe",
  },
  {
    styleKey: "pattern_break",
    styleName: "Pattern Break",
    sourceCategory: "Shock",
    coreIntent: "Open with a surprising result stat contrast or unexpected outcome",
    emotionalTrigger: "surprise",
    bestFor: ["unexpected lessons", "creative tests", "attention resets"],
    riskLevel: "medium",
  },
  {
    styleKey: "vulnerable_reveal",
    styleName: "Vulnerable Reveal",
    sourceCategory: "Confession",
    coreIntent: "Admit something honest uncomfortable or personal",
    emotionalTrigger: "empathy",
    bestFor: ["founder stories", "lessons learned", "honest reflections"],
    riskLevel: "safe",
  },
  {
    styleKey: "viewer_dare",
    styleName: "Viewer Dare",
    sourceCategory: "Challenge",
    coreIntent: "Dare the viewer to prove skill knowledge or self-awareness",
    emotionalTrigger: "participation",
    bestFor: ["interactive education", "diagnostics", "quick tests"],
    riskLevel: "aggressive",
  },
  {
    styleKey: "identity_challenge",
    styleName: "Identity Challenge",
    sourceCategory: "Provocation",
    coreIntent: "Make a bold claim the viewer's identity or core belief won't let them scroll past",
    emotionalTrigger: "defiance",
    bestFor: ["scroll-stop hooks", "belief disruption", "audience-targeted ads", "reaction content"],
    riskLevel: "aggressive",
  },
  {
    styleKey: "cold_open_story",
    styleName: "Cold Open Story",
    sourceCategory: "Storytime",
    coreIntent: "Start inside a specific moment that needs resolution",
    emotionalTrigger: "narrative tension",
    bestFor: ["storytelling", "founder moments", "case studies"],
    riskLevel: "safe",
  },
];
