export const rawCliprHookTemplates: {
  styleKey: string;
  template: string;
  templateId: string;
}[] = [
  { styleKey: "mystery_gap", templateId: "MG-001", template: "The thing nobody tells you about {{topic}}" },
  { styleKey: "mystery_gap", templateId: "MG-002", template: "I finally figured out why {{audience}} struggle with {{problem}}" },
  { styleKey: "mystery_gap", templateId: "MG-003", template: "This one small part of {{task}} matters more than you think" },
  { styleKey: "mystery_gap", templateId: "MG-004", template: "Most people skip this before they try {{goal}}" },
  { styleKey: "mystery_gap", templateId: "MG-005", template: "This looks like {{problem}}, but it is really {{real_problem}}" },
  { styleKey: "mystery_gap", templateId: "MG-006", template: "I changed one thing in {{routine}}, and it got weird" },
  { styleKey: "mystery_gap", templateId: "MG-007", template: "The first sign that {{problem}} is getting worse" },
  { styleKey: "mystery_gap", templateId: "MG-008", template: "I wish I knew this before paying for {{thing}}" },
  { styleKey: "mystery_gap", templateId: "MG-009", template: "The real reason {{problem}} keeps happening" },
  { styleKey: "mystery_gap", templateId: "MG-010", template: "What happens when you stop doing {{old_step}}" },
  { styleKey: "authority_signal", templateId: "AS-001", template: "I looked at {{number}} examples of {{topic}}, and one thing stood out" },
  { styleKey: "authority_signal", templateId: "AS-002", template: "A good {{role}} checks this before starting {{task}}" },
  { styleKey: "authority_signal", templateId: "AS-003", template: "The best {{audience}} do this before making {{decision}}" },
  { styleKey: "authority_signal", templateId: "AS-004", template: "Here is how smart {{audience}} avoid {{mistake}}" },
  { styleKey: "authority_signal", templateId: "AS-005", template: "Once you understand {{idea}}, {{topic}} gets simpler" },
  { styleKey: "authority_signal", templateId: "AS-006", template: "This is what separates new {{audience}} from better ones" },
  { styleKey: "authority_signal", templateId: "AS-007", template: "I kept seeing the same mistake in {{examples}}" },
  { styleKey: "authority_signal", templateId: "AS-008", template: "The smart move before {{action}} is this" },
  { styleKey: "authority_signal", templateId: "AS-009", template: "Here is a better way to think about {{problem}}" },
  { styleKey: "authority_signal", templateId: "AS-010", template: "Most advice about {{topic}} skips the simple part" },
  { styleKey: "anti_advice", templateId: "AA-001", template: "The common advice about {{topic}} is not helping {{audience}}" },
  { styleKey: "anti_advice", templateId: "AA-002", template: "You do not need more {{thing}}. You need {{better_thing}}" },
  { styleKey: "anti_advice", templateId: "AA-003", template: "Everyone says {{common_advice}}, but that is not the whole story" },
  { styleKey: "anti_advice", templateId: "AA-004", template: "Stop chasing {{wrong_goal}} if you want {{result}}" },
  { styleKey: "anti_advice", templateId: "AA-005", template: "{{audience}} are trying to fix the wrong problem" },
  { styleKey: "anti_advice", templateId: "AA-006", template: "The thing helping your {{goal}} might be slowing you down" },
  { styleKey: "anti_advice", templateId: "AA-007", template: "Fix {{big_problem}} before worrying about {{small_detail}}" },
  { styleKey: "anti_advice", templateId: "AA-008", template: "The easier way to do {{task}} might be better" },
  { styleKey: "anti_advice", templateId: "AA-009", template: "Most {{audience}} do not need this trendy {{thing}}" },
  { styleKey: "anti_advice", templateId: "AA-010", template: "Doing less of {{bad_habit}} might fix more than doing more" },
  { styleKey: "inside_room", templateId: "IR-001", template: "The quiet rule good {{audience}} follow with {{topic}}" },
  { styleKey: "inside_room", templateId: "IR-002", template: "What really happens before {{result}}" },
  { styleKey: "inside_room", templateId: "IR-003", template: "The part of {{topic}} beginners never hear about" },
  { styleKey: "inside_room", templateId: "IR-004", template: "Why {{thing}} feels harder than it should" },
  { styleKey: "inside_room", templateId: "IR-005", template: "What actually happens after you {{action}}" },
  { styleKey: "inside_room", templateId: "IR-006", template: "Why {{situation}} feels so confusing" },
  { styleKey: "inside_room", templateId: "IR-007", template: "People who know {{topic}} rarely say this part out loud" },
  { styleKey: "inside_room", templateId: "IR-008", template: "The checklist I use before {{task}}" },
  { styleKey: "inside_room", templateId: "IR-009", template: "The rule that saves you from {{bad_outcome}}" },
  { styleKey: "inside_room", templateId: "IR-010", template: "The secret is not {{obvious_thing}}. It is {{real_thing}}" },
  { styleKey: "direct_diagnosis", templateId: "DD-001", template: "{{audience}}: stop doing {{bad_habit}} before it becomes {{bad_outcome}}" },
  { styleKey: "direct_diagnosis", templateId: "DD-002", template: "If {{goal}} feels impossible, this might be why" },
  { styleKey: "direct_diagnosis", templateId: "DD-003", template: "You are not bad at {{topic}}. Your setup is messy" },
  { styleKey: "direct_diagnosis", templateId: "DD-004", template: "If you keep doing {{bad_habit}}, {{bad_result}} will keep happening" },
  { styleKey: "direct_diagnosis", templateId: "DD-005", template: "This is why your {{thing}} looks like everyone else's" },
  { styleKey: "direct_diagnosis", templateId: "DD-006", template: "You are fixing {{symptom}} instead of {{real_problem}}" },
  { styleKey: "direct_diagnosis", templateId: "DD-007", template: "If you are {{audience}}, this habit is costing you {{cost}}" },
  { styleKey: "direct_diagnosis", templateId: "DD-008", template: "Your {{routine}} has one thing slowing it down" },
  { styleKey: "direct_diagnosis", templateId: "DD-009", template: "You are making {{task}} harder than it needs to be" },
  { styleKey: "direct_diagnosis", templateId: "DD-010", template: "Your effort is fine. It is going to the wrong part of {{task}}" },
  { styleKey: "before_after_arc", templateId: "BA-001", template: "From {{before_state}} to {{after_state}} in {{timeframe}}" },
  { styleKey: "before_after_arc", templateId: "BA-002", template: "The small change that took me from {{bad_result}} to {{better_result}}" },
  { styleKey: "before_after_arc", templateId: "BA-003", template: "How {{audience}} can go from {{pain_point}} to {{desired_outcome}}" },
  { styleKey: "before_after_arc", templateId: "BA-004", template: "I swapped {{old_way}} for {{new_way}}, and {{result}} changed" },
  { styleKey: "before_after_arc", templateId: "BA-005", template: "How to turn messy {{thing}} into clean {{thing}}" },
  { styleKey: "before_after_arc", templateId: "BA-006", template: "How {{one_change}} turned {{problem}} into {{advantage}}" },
  { styleKey: "before_after_arc", templateId: "BA-007", template: "Before I fixed {{problem}}, {{bad_result}} kept happening" },
  { styleKey: "before_after_arc", templateId: "BA-008", template: "The {{timeframe}} reset that changed my {{thing}}" },
  { styleKey: "before_after_arc", templateId: "BA-009", template: "I stopped {{old_habit}} and finally got {{result}}" },
  { styleKey: "before_after_arc", templateId: "BA-010", template: "How to turn {{input}} into {{output}} without overthinking it" },
  { styleKey: "cost_alert", templateId: "CA-001", template: "This common {{habit}} is quietly hurting your {{result}}" },
  { styleKey: "cost_alert", templateId: "CA-002", template: "Do not start {{task}} until you check {{thing}}" },
  { styleKey: "cost_alert", templateId: "CA-003", template: "The {{task}} mistake that wastes {{time}}" },
  { styleKey: "cost_alert", templateId: "CA-004", template: "If you ignore {{problem}}, it gets harder to fix" },
  { styleKey: "cost_alert", templateId: "CA-005", template: "Your {{tool}} might be causing the problem" },
  { styleKey: "cost_alert", templateId: "CA-006", template: "This is the red flag that {{problem}} is getting expensive" },
  { styleKey: "cost_alert", templateId: "CA-007", template: "One bad guess about {{topic}} can ruin {{result}}" },
  { styleKey: "cost_alert", templateId: "CA-008", template: "Check this before spending money on {{thing}}" },
  { styleKey: "cost_alert", templateId: "CA-009", template: "The risky part of {{trend}} people skip" },
  { styleKey: "cost_alert", templateId: "CA-010", template: "This tiny mistake turns into a bigger {{problem}}" },
  { styleKey: "deadline_pull", templateId: "DP-001", template: "Do this before {{milestone}} makes it harder" },
  { styleKey: "deadline_pull", templateId: "DP-002", template: "You are early to {{opportunity}}, but that will not last" },
  { styleKey: "deadline_pull", templateId: "DP-003", template: "The window for {{advantage}} is closing" },
  { styleKey: "deadline_pull", templateId: "DP-004", template: "Check this before you choose {{decision}}" },
  { styleKey: "deadline_pull", templateId: "DP-005", template: "If you are planning {{task}}, save this now" },
  { styleKey: "deadline_pull", templateId: "DP-006", template: "Fix {{problem}} before {{moment}}" },
  { styleKey: "deadline_pull", templateId: "DP-007", template: "Most {{audience}} learn this too late" },
  { styleKey: "deadline_pull", templateId: "DP-008", template: "You will want this before {{moment}}" },
  { styleKey: "deadline_pull", templateId: "DP-009", template: "Your reminder to handle {{task}} before {{deadline}}" },
  { styleKey: "deadline_pull", templateId: "DP-010", template: "Learn {{skill}} now and {{task}} gets easier later" },
  { styleKey: "receipt_stack", templateId: "RS-001", template: "I tried {{method}} on {{examples}}, and the answer was clear" },
  { styleKey: "receipt_stack", templateId: "RS-002", template: "Here is what changed when I only fixed {{one_thing}}" },
  { styleKey: "receipt_stack", templateId: "RS-003", template: "Things changed when I stopped doing {{old_habit}}" },
  { styleKey: "receipt_stack", templateId: "RS-004", template: "I compared {{option_a}} and {{option_b}} so you do not have to" },
  { styleKey: "receipt_stack", templateId: "RS-005", template: "This is what {{result}} looked like after {{timeframe}}" },
  { styleKey: "receipt_stack", templateId: "RS-006", template: "I tracked {{thing}} every day, and saw the same pattern" },
  { styleKey: "receipt_stack", templateId: "RS-007", template: "Here is what happened when I used {{method}} instead of {{old_way}}" },
  { styleKey: "receipt_stack", templateId: "RS-008", template: "I used {{tool}} for {{timeframe}} and checked {{result}}" },
  { styleKey: "receipt_stack", templateId: "RS-009", template: "The proof showed up after I tried {{action}}" },
  { styleKey: "receipt_stack", templateId: "RS-010", template: "This tiny test made {{outcome}} easier" },
  { styleKey: "future_cast", templateId: "FC-001", template: "{{thing}} is about to change how {{audience}} do {{task}}" },
  { styleKey: "future_cast", templateId: "FC-002", template: "Soon, {{old_way}} will feel old" },
  { styleKey: "future_cast", templateId: "FC-003", template: "The next wave of {{topic}} will reward {{skill}}" },
  { styleKey: "future_cast", templateId: "FC-004", template: "{{audience}} who ignore {{trend}} will feel behind" },
  { styleKey: "future_cast", templateId: "FC-005", template: "{{topic}} is moving from {{old_way}} to {{new_way}}" },
  { styleKey: "future_cast", templateId: "FC-006", template: "Here is where {{topic}} is probably going next" },
  { styleKey: "future_cast", templateId: "FC-007", template: "People using {{new_way}} now will move faster later" },
  { styleKey: "future_cast", templateId: "FC-008", template: "{{tool}} will not replace {{audience}}. It will replace {{old_way}}" },
  { styleKey: "future_cast", templateId: "FC-009", template: "The next big edge in {{topic}} is not {{obvious_thing}}" },
  { styleKey: "future_cast", templateId: "FC-010", template: "What happens when {{trend}} becomes normal" },
  { styleKey: "test_drive", templateId: "TD-001", template: "I tested {{thing}} and found the part people leave out" },
  { styleKey: "test_drive", templateId: "TD-002", template: "I tried {{method}} for {{timeframe}}, and kept only this" },
  { styleKey: "test_drive", templateId: "TD-003", template: "I compared {{number}} ways to do {{task}}. One was better" },
  { styleKey: "test_drive", templateId: "TD-004", template: "I used {{tool}} on {{project}}, and this part helped" },
  { styleKey: "test_drive", templateId: "TD-005", template: "I pushed {{thing}} until it broke" },
  { styleKey: "test_drive", templateId: "TD-006", template: "I followed {{method}} exactly, and this is what failed" },
  { styleKey: "test_drive", templateId: "TD-007", template: "I rebuilt {{thing}} from scratch to see if it worked" },
  { styleKey: "test_drive", templateId: "TD-008", template: "I gave {{thing}} one honest week" },
  { styleKey: "test_drive", templateId: "TD-009", template: "I tried the fast way and slow way to do {{task}}" },
  { styleKey: "test_drive", templateId: "TD-010", template: "I ran {{input}} through {{option_a}} and {{option_b}}" },
  { styleKey: "pattern_break", templateId: "PB-001", template: "The weird way {{method}} got {{result}}" },
  { styleKey: "pattern_break", templateId: "PB-002", template: "This tiny {{action}} saved more time than {{old_way}}" },
  { styleKey: "pattern_break", templateId: "PB-003", template: "I got {{surprising_result}} from something way too simple" },
  { styleKey: "pattern_break", templateId: "PB-004", template: "The ugly version of {{thing}} did better" },
  { styleKey: "pattern_break", templateId: "PB-005", template: "This should not have worked, but it beat {{popular_choice}}" },
  { styleKey: "pattern_break", templateId: "PB-006", template: "I removed {{thing}}, and {{result}} got better" },
  { styleKey: "pattern_break", templateId: "PB-007", template: "The lazy version of {{thing}} got the best response" },
  { styleKey: "pattern_break", templateId: "PB-008", template: "One boring change to {{thing}} made a big difference" },
  { styleKey: "pattern_break", templateId: "PB-009", template: "The thing I almost deleted saved {{project}}" },
  { styleKey: "pattern_break", templateId: "PB-010", template: "{{result}} sounds weird until you understand {{reason}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-001", template: "I almost gave up on {{thing}}, then noticed this" },
  { styleKey: "vulnerable_reveal", templateId: "VR-002", template: "I was embarrassed by {{mistake}}, but it taught me {{lesson}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-003", template: "I avoided {{task}} because I was scared of {{fear}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-004", template: "The hardest part of {{journey}} was not {{thing}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-005", template: "I pretended I understood {{topic}} until {{moment}} exposed me" },
  { styleKey: "vulnerable_reveal", templateId: "VR-006", template: "I lost {{cost}} because I ignored {{warning_sign}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-007", template: "I was wrong about {{belief}}, and it changed {{outcome}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-008", template: "The mistake I would delete from my first {{project}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-009", template: "I did not want to admit this about {{problem}}" },
  { styleKey: "vulnerable_reveal", templateId: "VR-010", template: "The moment I realized {{old_way}} was not working" },
  { styleKey: "viewer_dare", templateId: "VD-001", template: "Most {{audience}} cannot spot the mistake in this {{example}}" },
  { styleKey: "viewer_dare", templateId: "VD-002", template: "Try to find the problem in this {{example}} first" },
  { styleKey: "viewer_dare", templateId: "VD-003", template: "If you can answer this, you understand {{topic}}" },
  { styleKey: "viewer_dare", templateId: "VD-004", template: "Pause and guess which {{thing}} works better" },
  { styleKey: "viewer_dare", templateId: "VD-005", template: "Can you fix this {{task}} in under {{time_limit}}?" },
  { styleKey: "viewer_dare", templateId: "VD-006", template: "Only people who understand {{idea}} will catch this" },
  { styleKey: "viewer_dare", templateId: "VD-007", template: "Which would you choose: {{option_a}} or {{option_b}}?" },
  { styleKey: "viewer_dare", templateId: "VD-008", template: "I bet you will miss this detail in {{example}}" },
  { styleKey: "viewer_dare", templateId: "VD-009", template: "Rank these {{examples}} from worst to best" },
  { styleKey: "viewer_dare", templateId: "VD-010", template: "Before I explain, what would you change about {{thing}}?" },
  { styleKey: "cold_open_story", templateId: "CS-001", template: "{{time_marker}}, I was doing {{normal_task}} when {{unexpected_event}} happened" },
  { styleKey: "cold_open_story", templateId: "CS-002", template: "Someone asked for {{simple_request}}, then {{problem}} showed up" },
  { styleKey: "cold_open_story", templateId: "CS-003", template: "I opened {{thing}} and knew something was wrong" },
  { styleKey: "cold_open_story", templateId: "CS-004", template: "I thought {{task}} would be quick, then found {{surprise}}" },
  { styleKey: "cold_open_story", templateId: "CS-005", template: "A random {{message}} made me rethink {{topic}}" },
  { styleKey: "cold_open_story", templateId: "CS-006", template: "I was about to finish {{project}} when {{problem}} appeared" },
  { styleKey: "cold_open_story", templateId: "CS-007", template: "The first version of {{project}} was bad, but one detail saved it" },
  { styleKey: "cold_open_story", templateId: "CS-008", template: "I ignored {{small_warning}} until it became {{big_problem}}" },
  { styleKey: "cold_open_story", templateId: "CS-009", template: "The best idea came after I almost quit {{project}}" },
  { styleKey: "cold_open_story", templateId: "CS-010", template: "I showed {{thing}} to {{person}}, and their reaction changed everything" },
];
