import type { RawCliprHookTemplate } from "@/lib/clipstitchr/types/RawCliprHookTemplate";

export const rawEducationHookTemplates: RawCliprHookTemplate[] = [
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "direct_diagnosis",
    templateId: "EDU-001",
    template: "3 signs {{audience}} are making {{topic}} harder",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "cost_alert",
    templateId: "EDU-002",
    template: "Avoid these {{topic}} mistakes before they cost you {{result}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "mystery_gap",
    templateId: "EDU-003",
    template: "What will happen if {{audience}} keep ignoring {{problem}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "authority_signal",
    templateId: "EDU-004",
    template: "A simple way to check if {{audience}} understand {{topic}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "pattern_break",
    templateId: "EDU-005",
    template: "The weird reason {{topic}} suddenly feels easier",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "before_after_arc",
    templateId: "EDU-006",
    template: "Before {{old_way}} vs after {{new_way}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "test_drive",
    templateId: "EDU-007",
    template: "I tested {{number}} ways to learn {{topic}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "receipt_stack",
    templateId: "EDU-008",
    template: "The proof showed up after {{timeframe}} of {{method}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "anti_advice",
    templateId: "EDU-009",
    template: "Stop saying {{common_advice}} if you want {{result}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "inside_room",
    templateId: "EDU-010",
    template: "The quiet rule better {{audience}} use for {{topic}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "mystery_gap",
    templateId: "EDU-011",
    template: "Most {{audience}} miss this part of {{topic}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "direct_diagnosis",
    templateId: "EDU-012",
    template: "If {{task}} feels impossible, check {{thing}} first",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "authority_signal",
    templateId: "EDU-013",
    template: "Here is the difference between {{option_a}} and {{option_b}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "pattern_break",
    templateId: "EDU-014",
    template: "{{topic}} sounds confusing until you see this example",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "cost_alert",
    templateId: "EDU-015",
    template: "This is the red flag that {{problem}} is getting worse",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "test_drive",
    templateId: "EDU-016",
    template: "I tried the fast way and slow way to do {{task}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "before_after_arc",
    templateId: "EDU-017",
    template: "How {{audience}} go from {{pain_point}} to {{result}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "inside_room",
    templateId: "EDU-018",
    template: "The part of {{topic}} nobody explains simply",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "anti_advice",
    templateId: "EDU-019",
    template: "You do not need more {{thing}} to improve {{result}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "receipt_stack",
    templateId: "EDU-020",
    template: "I tracked {{thing}} and saw the same {{problem}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "mystery_gap",
    templateId: "EDU-021",
    template: "Why smart {{audience}} still struggle with {{topic}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "authority_signal",
    templateId: "EDU-022",
    template: "A good {{role}} checks this before starting {{task}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "pattern_break",
    templateId: "EDU-023",
    template: "The lazy version of {{task}} got better {{result}}",
  },
  {
    allowedPurposes: ["clipr", "swipr", "stitchr"],
    source: "education_viral_patterns",
    styleKey: "deadline_pull",
    templateId: "EDU-024",
    template: "Learn {{skill}} before {{moment}} makes it harder",
  },
];
