import type { RawCliprHookTemplate } from "@/lib/clipstitchr/types/RawCliprHookTemplate";

export const rawIdentityChallengeHookTemplates: RawCliprHookTemplate[] = [
  {
    styleKey: "identity_challenge",
    templateId: "IC-001",
    template: "{{core_belief}} doesn't work the way {{audience}} think",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-002",
    template: "Stop telling yourself {{core_belief}} is the answer",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-003",
    template: "{{audience}} who still believe in {{core_belief}} are behind",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-004",
    template: "The uncomfortable truth about {{core_belief}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-005",
    template: "{{core_belief}} is a lie {{audience}} keep repeating",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-006",
    template: "{{popular_method}} is why {{audience}} aren't getting results",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-007",
    template: "Every {{audience}} says {{core_belief}} but none of them can prove it",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-008",
    template: "{{popular_method}} made you worse and you don't even know it",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-009",
    template: "If you're still doing {{popular_method}} in {{year}}, I feel bad for you",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-010",
    template: "{{core_belief}} is holding {{audience}} back and nobody will say it",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-011",
    template: "You don't need {{popular_method}}. You need this",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-012",
    template: "{{audience}} will hate me for saying this about {{core_belief}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-013",
    template: "The {{core_belief}} era is over. Here's what replaced it",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-014",
    template: "{{audience}} are wrong about {{core_belief}} and the data proves it",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-015",
    template: "I {{popular_method}} for {{time_period}} and it was a complete waste",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-016",
    template: "{{audience}} are defending {{core_belief}} because it feels safe",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-017",
    template: "{{core_belief}} feels true until {{problem}} shows up",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-018",
    template: "The {{popular_method}} crowd keeps missing the obvious part",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-019",
    template: "{{identity}} are not stuck because they lack effort",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-020",
    template: "Your favorite {{popular_method}} might be the bottleneck",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-021",
    template: "{{common_assumption}} is the trap {{audience}} keep walking into",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-022",
    template: "The loudest {{audience}} are usually wrong about {{core_belief}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-023",
    template: "{{core_belief}} is not a strategy. It is a coping mechanism",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-024",
    template: "If {{popular_method}} worked, {{audience}} would not be this stuck",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-025",
    template: "Most {{identity}} confuse {{popular_method}} with progress",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-026",
    template: "The hard truth: {{core_belief}} is not enough",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-027",
    template: "{{audience}} keep protecting the exact habit causing {{pain_point}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-028",
    template: "The real problem is not {{problem}}. It is {{common_assumption}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-029",
    template: "{{popular_method}} looks productive because the cost is hidden",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-030",
    template: "Nobody wants to admit {{controversial_take}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-031",
    template: "Your {{popular_method}} routine is probably hiding the real issue",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-032",
    template: "{{identity}} love {{core_belief}} because it delays the uncomfortable part",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-033",
    template: "The belief keeping {{audience}} busy is {{core_belief}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-034",
    template: "{{core_belief}} is a great excuse and a weak plan",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-035",
    template: "What if {{popular_method}} is the reason {{result}} still feels impossible?",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-036",
    template: "The {{audience}} who win usually abandon {{core_belief}} first",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-037",
    template: "{{common_assumption}} sounds smart until the output proves otherwise",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-038",
    template: "Your old playbook is not discipline. It is drag",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-039",
    template: "{{audience}} do not need more effort. They need fewer wrong moves",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-040",
    template: "The painful part is {{popular_method}} might be the problem",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-041",
    template: "{{identity}} are treating {{common_assumption}} like a personality",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-042",
    template: "The fastest way to stay average is defending {{core_belief}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-043",
    template: "{{core_belief}} is why your {{workflow}} still feels heavy",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-044",
    template: "Stop calling {{popular_method}} a strategy",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-045",
    template: "{{audience}} are loyal to {{old_way}} for the wrong reason",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-046",
    template: "The thing you trust most is probably creating {{pain_point}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-047",
    template: "{{popular_method}} is not the flex {{audience}} think it is",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-048",
    template: "The uncomfortable part: {{core_belief}} rewards looking busy",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-049",
    template: "Most {{audience}} are not behind. Their belief system is",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-050",
    template: "{{identity}} defend {{popular_method}} because changing it feels personal",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-051",
    template: "The advice {{audience}} repeat is causing the delay",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-052",
    template: "Your {{core_belief}} habit is costing more than you notice",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-053",
    template: "{{common_assumption}} is how smart people waste {{time}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-054",
    template: "The problem with {{popular_method}} is that it feels responsible",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-055",
    template: "{{core_belief}} is only useful until it becomes your ceiling",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-056",
    template: "{{audience}} keep choosing the hard way and calling it quality",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-057",
    template: "The ugly truth about {{popular_method}} is visible in the result",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-058",
    template: "{{identity}} are obsessed with {{popular_method}} and missing {{real_thing}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-059",
    template: "Your audience can tell when {{common_assumption}} is running the show",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-060",
    template: "{{core_belief}} is not wrong. It is incomplete",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-061",
    template: "The reason {{popular_method}} fails is not what {{audience}} think",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-062",
    template: "{{identity}} are solving {{problem}} from the wrong end",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-063",
    template: "The belief sounds noble. The result says otherwise",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-064",
    template: "You are not bad at {{topic}}. You are loyal to {{old_way}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-065",
    template: "{{popular_method}} creates confidence before it creates results",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-066",
    template: "{{audience}} need to hear this: {{controversial_take}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-067",
    template: "The old rule stopped working when {{trend}} changed",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-068",
    template: "{{core_belief}} is a comfort zone with better branding",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-069",
    template: "The thing {{audience}} call discipline is often just delay",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-070",
    template: "If {{core_belief}} were enough, {{pain_point}} would be gone",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-071",
    template: "{{popular_method}} is a ritual, not a result",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-072",
    template: "The strongest {{identity}} question {{core_belief}} first",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-073",
    template: "Your content is not failing because of {{problem}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-074",
    template: "{{audience}} are addicted to the method, not the outcome",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-075",
    template: "The most defended belief is usually the most expensive one",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-076",
    template: "{{common_assumption}} is why {{audience}} keep restarting",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-077",
    template: "{{popular_method}} feels safe because it delays judgment",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-078",
    template: "The hard part is not {{task}}. It is letting go of {{core_belief}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-079",
    template: "{{identity}} who cling to {{old_way}} are choosing friction",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-080",
    template: "The result changed when {{core_belief}} stopped being sacred",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-081",
    template: "{{audience}} confuse effort with evidence",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-082",
    template: "{{popular_method}} is not proof you care",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-083",
    template: "The belief you protect is the bottleneck you keep missing",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-084",
    template: "{{core_belief}} keeps {{audience}} comfortable and inconsistent",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-085",
    template: "The obvious answer is not always the honest answer",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-086",
    template: "{{identity}} are not ready for the {{popular_method}} conversation",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-087",
    template: "{{popular_method}} might be the reason {{goal}} keeps moving away",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-088",
    template: "The expensive mistake is believing {{common_assumption}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-089",
    template: "{{audience}} keep optimizing around the wrong pain",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-090",
    template: "The fastest path is usually the one {{audience}} dismiss",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-091",
    template: "{{core_belief}} is not your edge anymore",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-092",
    template: "Nobody scrolls because your {{popular_method}} was technically correct",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-093",
    template: "The thing you call quality control might be fear",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-094",
    template: "{{identity}} are making {{task}} harder to protect {{core_belief}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-095",
    template: "The wrong belief can make a simple workflow feel impossible",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-096",
    template: "{{popular_method}} is the socially acceptable version of procrastination",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-097",
    template: "The audience does not reward {{common_assumption}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-098",
    template: "{{audience}} keep mistaking motion for proof",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-099",
    template: "The uncomfortable receipt is your {{result}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-100",
    template: "{{core_belief}} works until scale exposes it",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-101",
    template: "The method everyone praises is hiding the weakness",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-102",
    template: "{{identity}} hate hearing that {{old_way}} is optional",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-103",
    template: "{{popular_method}} is why the before still looks like the before",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-104",
    template: "Your best excuse has a workflow problem under it",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-105",
    template: "{{audience}} would rather defend {{core_belief}} than measure the output",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-106",
    template: "The scary part is {{new_way}} makes {{old_way}} look unnecessary",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-107",
    template: "If {{common_assumption}} is true, why is {{pain_point}} still there?",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-108",
    template: "{{popular_method}} creates the feeling of progress before progress",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-109",
    template: "The mistake is treating {{core_belief}} like a law",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-110",
    template: "The people winning at {{topic}} already stopped doing {{old_way}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-111",
    template: "{{identity}} keep blaming {{problem}} instead of the method",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-112",
    template: "The proof gets interesting when {{core_belief}} falls apart",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-113",
    template: "The old answer is too slow for {{timeframe}}",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-114",
    template: "The viewer knows when {{popular_method}} is just theater",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "IC-115",
    template: "{{audience}} are one belief away from cleaner execution",
    source: "clipstitchr",
    allowedPurposes: ["clipr", "swipr", "stitchr"],
  },
];
