import type { RawCliprHookTemplate } from "@/lib/clipstitchr/types/RawCliprHookTemplate";

export const rawPolarizingReactionHookTemplates: RawCliprHookTemplate[] = [
  {
    styleKey: "identity_challenge",
    templateId: "PR-001",
    template: "I thought {{thing}} was a 10 out of 10 until {{problem}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-002",
    template: "{{thing}} looks impressive until {{better_thing}} walks in",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-003",
    template: "Your {{popular_method}} is not the flex you think it is",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-004",
    template: "Stop acting like {{core_belief}} still wins",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-005",
    template: "If {{pain_point}} keeps happening, your {{workflow}} is the problem",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-006",
    template: "Most {{audience}} cannot admit {{controversial_take}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-007",
    template: "{{option_a}} people are not ready for {{option_b}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-008",
    template: "The {{identity}} who get results stopped defending {{core_belief}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-009",
    template: "Everyone praises {{popular_method}} because the cost is hidden",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-010",
    template: "You are behind because of {{common_assumption}}, not {{problem}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-011",
    template: "This made {{popular_method}} look weak",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-012",
    template: "Be honest, would your {{thing}} survive this comparison?",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-013",
    template: "If {{core_belief}} still sounds smart, watch the output",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-014",
    template: "The best {{audience}} are quietly ditching {{popular_method}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-015",
    template: "{{audience}} keep losing to people who stopped doing {{bad_habit}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-016",
    template: "I wanted {{option_a}} to win. {{option_b}} embarrassed it",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-017",
    template: "Your standards are lower than you think if {{thing}} impresses you",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-018",
    template: "The popular answer is popular because it feels comfortable",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-019",
    template: "This is why your {{result}} still looks average",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-020",
    template: "I bet {{audience}} will defend {{popular_method}} anyway",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-021",
    template: "{{thing}} was cute until {{better_thing}} showed up",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-022",
    template: "If your {{workflow}} needs {{tedious_thing}}, it is already broken",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-023",
    template: "Nobody wants to admit {{popular_method}} is the slow lane",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-024",
    template: "You blame {{problem}}, but {{common_assumption}} is doing the damage",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-025",
    template: "The {{audience}} who disagree usually prove the point",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-026",
    template: "{{identity}} love {{core_belief}} because changing would hurt",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-027",
    template: "This exposed how weak {{popular_method}} really is",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-028",
    template: "The old way only looks safe because everyone is doing it",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-029",
    template: "Your {{habit}} is making {{result}} harder than it has to be",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-030",
    template: "If this offends you, it probably applies",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-031",
    template: "{{product_name}} makes the usual {{category}} advice look outdated",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-032",
    template: "If {{product_name}} feels unfair, your old stack was the problem",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-033",
    template: "{{popular_tool}} had a good run. This is better",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-034",
    template: "Your {{tool}} is doing more babysitting than helping",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-035",
    template: "This is what {{audience}} pretend they do not need",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-036",
    template: "{{audience}} are allergic to the thing that would fix {{pain_point}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-037",
    template: "Rank {{option_a}} above {{option_b}} and explain yourself",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-038",
    template: "More {{thing}} is not a strategy. It is avoidance",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-039",
    template: "The issue is not effort. It is the setup you keep defending",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-040",
    template: "The boring option beat the pretty one",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-041",
    template: "People who still worship {{popular_method}} are telling on themselves",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-042",
    template: "The hack everyone repeats is why {{bad_result}} keeps happening",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-043",
    template: "Your {{workflow}} is too fragile for {{goal}}",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-044",
    template: "Only confident {{audience}} will admit this is better",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-045",
    template: "This comparison made the favorite look lazy",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "identity_challenge",
    templateId: "PR-046",
    template: "If {{common_assumption}} is your plan, you are gambling",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "anti_advice",
    templateId: "PR-047",
    template: "{{old_way}} is not discipline. It is wasted motion",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "direct_diagnosis",
    templateId: "PR-048",
    template: "You are calling it {{problem}} because {{real_problem}} sounds worse",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "viewer_dare",
    templateId: "PR-049",
    template: "The answer is obvious, but most {{audience}} will pick wrong",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
  {
    styleKey: "pattern_break",
    templateId: "PR-050",
    template: "{{product_name}} did the part {{popular_tool}} keeps pretending to solve",
    source: "polarizing_reaction_patterns",
    allowedPurposes: ["stitchr"],
  },
];
