export const ugcDiscoveryHookOpenerFamilies = [
  [
    "not me",
    "me, apparently,",
    "POV: you are",
    "the way I am",
    "okay, I am",
    "I fear I am",
    "somehow I am",
    "caught myself",
    "why am I",
    "tell me why I am",
  ],
  [
    "wait, so",
    "hold on, so",
    "you're telling me",
    "so you're saying",
    "okay, apparently",
    "why did nobody tell me",
    "am I really just finding out",
    "not me discovering",
    "the way I just learned",
    "I fear",
  ],
  [
    "I expected",
    "I genuinely thought",
    "me thinking",
    "POV: you assume",
    "not me assuming",
    "the way I thought",
    "apparently I believed",
    "I was fully convinced",
    "tell me why I thought",
    "I fear I assumed",
  ],
] as const;
