import type { ServiceAssertionSigningKey } from "../assertions/ServiceAssertionSigningKey.js";
import type { ProviderTokenCipherKey } from "../tokens/ProviderTokenCipherKey.js";
import type { PublishingServiceRuntimeMode } from "./PublishingServiceRuntimeMode.js";
import type { RedisSecurityNamespace } from "../redis/RedisSecurityNamespace.js";
import type { PublishingProvider } from "../providers/PublishingProvider.js";
import type { MetaGraphVersion } from "../provider-runtime/instagram/MetaGraphVersion.js";

export type PublishingServiceEnvironment = Readonly<{
  studioBetaEnabled: boolean;
  mode: PublishingServiceRuntimeMode;
  host: string | undefined;
  port: number | undefined;
  serviceIssuer: string | undefined;
  serviceAudience: string | undefined;
  serviceAssertionSigningKey: ServiceAssertionSigningKey | undefined;
  dispatchAccessSecret: string | undefined;
  providerTokenCipherKey: ProviderTokenCipherKey | undefined;
  databaseUrl: string | undefined;
  redisUrl: string | undefined;
  redisSecurityNamespace: RedisSecurityNamespace | undefined;
  outboxPollMilliseconds: number;
  outboxLeaseMilliseconds: number;
  outboxLeaseLimit: number;
  outboxConcurrency: number;
  outboxMaximumDeliveryAttempts: number;
  clipStitchrPublicOrigin: string | undefined;
  enabledProviders: readonly PublishingProvider[];
  metaGraphVersion: MetaGraphVersion | undefined;
  facebookAppId: string | undefined;
  facebookAppSecret: string | undefined;
  instagramAppId: string | undefined;
  instagramAppSecret: string | undefined;
  tikTokClientId: string | undefined;
  tikTokClientSecret: string | undefined;
  tikTokVerifiedMediaOrigin: string | undefined;
  googleClientId: string | undefined;
  googleClientSecret: string | undefined;
  r2AccountId: string | undefined;
  r2BucketName: string | undefined;
  r2AccessKeyId: string | undefined;
  r2SecretAccessKey: string | undefined;
  publishingMediaPublicOrigin: string | undefined;
  publishingMediaTokenSecret: string | undefined;
  publishingMediaQuotaSecret: string | undefined;
}>;
