import type { PricingPlan } from "@/lib/clipstitchr/pricing/PricingPlan";

export const pricingPlans: PricingPlan[] = [
  {
    key: "starter",
    name: "Starter",
    price: "$39",
    monthlyPriceUsd: 39,
    bestFor: "Creators getting one product's content moving.",
    products: "1 product",
    credits: "2,000 creation credits/month",
    features: [
      "Stitchr and Swipr",
      "3 Clipr or Swapr videos each month",
      "Hook Lab and clip scoring",
      "One media library",
      "Buy more credits anytime",
    ],
    ctaLabel: "Choose Starter",
    ctaHref: "/sign-up",
  },
  {
    key: "pro",
    name: "Pro",
    price: "$99",
    monthlyPriceUsd: 99,
    bestFor: "Brands making fresh creative every week.",
    products: "3 products",
    credits: "8,000 creation credits/month",
    features: [
      "Everything in Starter",
      "10 Clipr or Swapr videos each month",
      "Daily drafts for 1 product",
      "Faster generation",
      "More jobs active at once",
    ],
    ctaLabel: "Choose Pro",
    ctaHref: "/sign-up",
    isFeatured: true,
  },
  {
    key: "agency",
    name: "Agency",
    price: "$399",
    monthlyPriceUsd: 399,
    bestFor: "Teams producing campaigns across a client roster.",
    products: "10 products",
    credits: "20,000 creation credits/month",
    features: [
      "Everything in Pro",
      "Unlimited stitches",
      "50 Clipr or Swapr videos each month",
      "Daily drafts for all 10 products",
      "More jobs can run at once",
      "Priority support",
    ],
    ctaLabel: "Choose Agency",
    ctaHref: "/sign-up",
  },
];
