import type { PricingPlan } from "@/lib/clipstitchr/pricing/PricingPlan";

export const pricingPlans: PricingPlan[] = [
  {
    key: "starter",
    name: "Starter",
    price: "$39",
    bestFor: "Testing the workflow with a few products.",
    products: "3 products",
    credits: "50 credits/month",
    storage: "25 GB library storage",
    features: [
      "Included Stitchr batches from saved clips",
      "Included clip scoring and video analysis",
      "All creation tools included",
      "Buy more credits anytime",
      "10k Organic Views Challenge included",
    ],
    ctaLabel: "Join the waitlist",
    ctaHref: "/sign-up",
  },
  {
    key: "pro",
    name: "Pro",
    price: "$99",
    bestFor: "Weekly ad testing across a real product catalog.",
    products: "10 products",
    credits: "250 credits/month",
    storage: "250 GB library storage",
    features: [
      "Everything in Starter",
      "Daily drafts for 1 product",
      "Faster generation defaults",
      "Larger clip library included",
      "Stronger challenge reward",
    ],
    ctaLabel: "Join the waitlist",
    ctaHref: "/sign-up",
    isFeatured: true,
  },
  {
    key: "studio",
    name: "Studio",
    price: "$249",
    bestFor: "High-volume teams, agencies, and repeat testing.",
    products: "Unlimited products",
    credits: "750 credits/month",
    storage: "500 GB library storage",
    features: [
      "Everything in Pro",
      "Daily drafts across multiple products",
      "Higher concurrency and faster queues",
      "Priority support",
      "Strongest challenge reward",
    ],
    ctaLabel: "Join the waitlist",
    ctaHref: "/sign-up",
  },
  {
    key: "agency",
    name: "Agency",
    price: "$499+",
    bestFor: "Custom volume, onboarding, and support.",
    products: "Custom products",
    credits: "Custom credits",
    storage: "Custom storage",
    features: [
      "Multi-brand workflows",
      "Custom automation limits",
      "Onboarding help",
      "Priority support",
      "Custom challenge terms",
    ],
    ctaLabel: "Talk to us",
    ctaHref: "/sign-up",
  },
];
