import type { PricingPlan } from "@/lib/clipstitchr/pricing/PricingPlan";

export const pricingPlans: PricingPlan[] = [
  {
    key: "starter",
    name: "Starter",
    price: "$39",
    bestFor: "Trying ClipStitchr with a few products.",
    products: "3 products",
    credits: "50 credits/month",
    storage: "25 GB library storage",
    features: [
      "Included Stitchr ads from saved clips",
      "Included clip scores and video reads",
      "All creation tools included",
      "Buy more credits anytime",
      "10k Organic Views Challenge included",
    ],
    ctaLabel: "Join the waitlist",
    ctaHref: "/sign-up",
  },
  {
    key: "pro",
    name: "Pro",
    price: "$99",
    bestFor: "Regular ads without regular editing days.",
    products: "10 products",
    credits: "250 credits/month",
    storage: "250 GB library storage",
    features: [
      "Everything in Starter",
      "Daily drafts for 1 product",
      "Faster generation defaults",
      "More room for clips",
      "Stronger challenge reward",
    ],
    ctaLabel: "Join the waitlist",
    ctaHref: "/sign-up",
    isFeatured: true,
  },
  {
    key: "studio",
    name: "Studio",
    price: "$249",
    bestFor: "Teams with more products and more clips to keep moving.",
    products: "Unlimited products",
    credits: "750 credits/month",
    storage: "500 GB library storage",
    features: [
      "Everything in Pro",
      "Daily drafts across multiple products",
      "More jobs can run at once",
      "Priority support",
      "Strongest challenge reward",
    ],
    ctaLabel: "Join the waitlist",
    ctaHref: "/sign-up",
  },
  {
    key: "agency",
    name: "Agency",
    price: "$499+",
    bestFor: "Multiple brands, onboarding, and custom support.",
    products: "Custom products",
    credits: "Custom credits",
    storage: "Custom storage",
    features: [
      "Multi-brand workspaces",
      "Custom daily draft limits",
      "Onboarding help",
      "Priority support",
      "Custom challenge terms",
    ],
    ctaLabel: "Talk to us",
    ctaHref: "/sign-up",
  },
];
