import type { CollectionResourceItem } from "@/lib/clipstitchr/tools/resources/CollectionResourceItem";

const ugcOpeningLinePromptEntries = [
  [
    "Problem",
    "The recurring annoyance",
    "Tell me about the small [task] that kept interrupting your day before you tried this app.",
    "Answer like you are sending a voice note to a friend; name the exact moment it happened.",
    "Start with: 'The part that kept getting on my nerves was...'.",
    "Keep it to your real experience and avoid saying everyone has the same problem.",
  ],
  [
    "Problem",
    "The messy workaround",
    "Show the workaround you used before, then explain what made it annoying.",
    "Hold the old notes, tabs, or files in frame before looking back to camera.",
    "Start with: 'This was my system before I found a cleaner way...'.",
    "Do not stage a fake workaround or exaggerate how unusable it was.",
  ],
  [
    "Problem",
    "The stuck moment",
    "Describe the exact point where you would get stuck during [workflow].",
    "Pause after naming the stuck point so the editor has room for a visual cutaway.",
    "Start with: 'I was fine until I got to this part...'.",
    "Do not imply the app removes decisions or work that still belong to the user.",
  ],
  [
    "Problem",
    "The overlooked cost",
    "Explain what [problem] made harder besides the obvious task itself.",
    "Use one concrete consequence, such as another message or a missed handoff, without dramatizing it.",
    "Start with: 'It was not just [task]—it also meant...'.",
    "Avoid financial, health, or performance consequences you cannot document.",
  ],
  [
    "Surprise",
    "The feature you almost missed",
    "Name the small app feature you did not expect to use this often.",
    "Glance toward the phone, then point to where the feature appears on screen.",
    "Start with: 'I downloaded this for [reason], but this is what I keep using...'.",
    "Frame frequency as your own behavior, not a popularity claim.",
  ],
  [
    "Surprise",
    "The simpler answer",
    "Share the part of [workflow] that turned out to need fewer steps than you expected.",
    "Sound pleasantly surprised, then leave a beat before the demo begins.",
    "Start with: 'I thought this would be a whole process, but...'.",
    "Do not hide required setup or claim a step count you cannot show.",
  ],
  [
    "Surprise",
    "The unexpected use case",
    "Describe a useful way you ended up using the app that was not your original plan.",
    "Tell the short before-and-after story in one breath, then show the new use.",
    "Start with: 'I did not download this for [use], but now...'.",
    "Make sure the use is supported and does not violate the product's intended boundaries.",
  ],
  [
    "Surprise",
    "The detail that changed the feel",
    "Point out one tiny design detail that made the workflow feel clearer to you.",
    "Keep the reaction low-key and specific instead of sounding amazed on command.",
    "Start with: 'This is such a small thing, but I noticed it right away...'.",
    "Describe personal preference rather than claiming objective usability.",
  ],
  [
    "Objection",
    "Another-app hesitation",
    "Explain why you did not want another app, then name the one job that made you try it.",
    "Say the objection plainly before softening your tone for the specific use case.",
    "Start with: 'Honestly, I did not want another app for this...'.",
    "Do not pretend reluctance or claim the app replaces tools you still use.",
  ],
  [
    "Objection",
    "Setup hesitation",
    "Talk through the smallest setup you completed before the app became useful.",
    "Count the real steps with your fingers while the editor shows matching footage.",
    "Start with: 'I was worried setup would take forever, so I only did...'.",
    "Do not state a setup time or ease claim unless it matches the captured process.",
  ],
  [
    "Objection",
    "Not-techy hesitation",
    "Describe the first screen or action that made the app feel approachable to you.",
    "Use your natural vocabulary; do not perform confusion for the camera.",
    "Start with: 'I am not someone who wants to learn a complicated system...'.",
    "Keep it personal and do not label whole groups of people as bad with technology.",
  ],
  [
    "Objection",
    "Worth-it hesitation",
    "Name the repeated job you considered when deciding whether the app fit your routine.",
    "Talk about the job you use, not an assumed return on money or time.",
    "Start with: 'The question for me was whether I would actually use it for...'.",
    "Do not make savings, ROI, or performance claims without the viewer's own numbers.",
  ],
  [
    "Demo",
    "Show the first useful step",
    "Introduce the one action a new user should try first, then hand off to the screen recording.",
    "Keep your spoken line short and physically point toward the upcoming demo.",
    "Start with: 'If you are opening this for the first time, start here...'.",
    "Make sure it is a supported starting point for the current app version.",
  ],
  [
    "Demo",
    "Show the saved setup",
    "Explain what you made once and now reuse for a recurring task.",
    "Hold up one finger for the original setup, then gesture forward for the next use.",
    "Start with: 'I set this up once, and now I use it whenever...'.",
    "Do not imply reuse is automatic or needs no review when details still change.",
  ],
  [
    "Demo",
    "Show the handoff",
    "Tell the viewer what another person needs to know when you hand this work over.",
    "Name the receiver and the missing context, then cut directly to the share view.",
    "Start with: 'Before I send this to [person], I make sure they can see...'.",
    "Do not show private data or imply the recipient has access they may not have.",
  ],
  [
    "Demo",
    "Show the recovery path",
    "Describe a small mistake you can undo or correct inside the app.",
    "Let the mistake sound normal, then show the real recovery without a jump cut.",
    "Start with: 'If you accidentally [action], here is where you fix it...'.",
    "Only promise recovery for actions the app can genuinely reverse.",
  ],
  [
    "Confession",
    "The habit you dropped",
    "Admit one unhelpful way you used to handle [task] and what you do differently now.",
    "Smile at the old behavior without shaming yourself or the viewer.",
    "Start with: 'I used to [old behavior] every single time...'.",
    "Keep the story true and avoid implying the change guarantees a result.",
  ],
  [
    "Confession",
    "The feature-first mistake",
    "Share the app feature you ignored because you misunderstood when it was useful.",
    "Sound matter-of-fact, then point to the real moment it finally made sense.",
    "Start with: 'I skipped this feature for way too long because...'.",
    "Do not invent ignorance to make the feature sound more impressive.",
  ],
  [
    "Confession",
    "The overcomplicated system",
    "Describe the unnecessary step you added to your own workflow.",
    "Use a quick visual prop or gesture to show the extra step, then simplify.",
    "Start with: 'I was making this so much harder than it needed to be...'.",
    "Present the simplification as your preference, not the only correct method.",
  ],
  [
    "Confession",
    "The honest limitation",
    "Name one thing the app does not do and the specific job you still use it for.",
    "Deliver the limitation confidently, then transition into the narrow demo.",
    "Start with: 'This will not [unsupported job], but it does help me...'.",
    "Verify the limitation and avoid using honesty as a setup for an exaggerated claim.",
  ],
  [
    "Outcome",
    "The visible finish",
    "Describe what 'done' looks like inside the app for one specific task.",
    "Name the final state, then leave room for the editor to show it clearly.",
    "Start with: 'I know this task is ready when I can see...'.",
    "Do not call the wider job complete if outside approval or action still remains.",
  ],
  [
    "Outcome",
    "The prepared feeling",
    "Explain what you can see before [recurring event] that helps you feel prepared.",
    "Use calm delivery and name the exact information shown in the demo.",
    "Start with: 'Before [event], I like knowing...'.",
    "Keep the claim about preparation, not guaranteed performance or confidence.",
  ],
  [
    "Outcome",
    "The easier handoff",
    "Describe the question you hear less often because the handoff now includes the answer.",
    "Quote the old question naturally, then show where the answer lives.",
    "Start with: 'The question I used to get every time was...'.",
    "Do not claim questions disappear entirely or invent team feedback.",
  ],
  [
    "Outcome",
    "The reusable result",
    "Explain which part of today's work will still be useful for the next version.",
    "Hold the reusable piece in frame, then mention the details that still need changing.",
    "Start with: 'The part I do not have to rebuild next time is...'.",
    "Do not imply the whole result can be reused unchanged.",
  ],
] as const;

export const ugcOpeningLinePrompts: readonly CollectionResourceItem[] =
  ugcOpeningLinePromptEntries.map(
    ([category, title, copyText, delivery, alternate, guardrail], index) => ({
      body: `Delivery: ${delivery} Alternate take: ${alternate} Proof guardrail: ${guardrail}`,
      category,
      copyText,
      eyebrow: `${category} prompt · ${index + 1}`,
      id: `ugc-opening-line-prompt-${String(index + 1).padStart(2, "0")}`,
      tags: [category, "Creator direction"],
      title,
    }),
  );
